import {describe,expect,it} from 'vitest';
import {aggregateUsage,candidateInstructions,chooseDeliberation,JUDGE_MAX_CHARS,judgeInput,judgeInstructions} from './deliberation';

describe('adaptive deliberation policy',()=>{
 it('uses an ensemble for deep tasks',()=>{expect(chooseDeliberation('Diseña una arquitectura completa','deep').mode).toBe('ensemble');});
 it('recognizes the requested intelligence upgrade',()=>{expect(chooseDeliberation('Hazla más inteligente que GPT-5.6 alta','balanced').mode).toBe('ensemble');});
 it('keeps simple requests on a single pass',()=>{const profile=chooseDeliberation('Hola, gracias','fast');expect(profile.mode).toBe('single');expect(profile.candidateCount).toBe(1);});
 it('raises sensitive complex tasks to ensemble mode',()=>{const profile=chooseDeliberation('Compara escenarios financieros, riesgos y sensibilidad antes de recomendar una inversión.','balanced');expect(profile.mode).toBe('ensemble');expect(profile.highStakes).toBe(true);});
 it('honors explicit high reasoning and configuration off',()=>{expect(chooseDeliberation('Explica esto','balanced',{reasoning:'high'}).mode).toBe('ensemble');expect(chooseDeliberation('Audita a fondo esta arquitectura','deep',{},false).mode).toBe('single');expect(chooseDeliberation('Audita a fondo esta arquitectura','deep',{deliberation:'off'}).mode).toBe('single');});
 it('builds independent roles and a private synthesis contract',()=>{const architect=candidateInstructions('BASE','architect','ingeniería',false),adversary=candidateInstructions('BASE','adversary','ingeniería',true),judge=judgeInstructions('BASE','ingeniería',true);expect(architect).toContain('arquitecto principal');expect(adversary).toContain('adversarial independiente');expect(adversary).toContain('tarea sensible');expect(judge).toContain('una sola respuesta final autosuficiente');expect(judge).toContain('No menciones candidatos');});
 it('bounds the complete judge payload',()=>{const text=judgeInput('O'.repeat(20000),[{role:'architect',text:'A'.repeat(50000)},{role:'adversary',text:'B'.repeat(50000)}]);expect(text).toContain('SOLICITUD ORIGINAL');expect(text).toContain('SOLUCIÓN 1 — ARCHITECT');expect(text).toContain('SOLUCIÓN 2 — ADVERSARY');expect(text).toContain('contenido intermedio compactado');expect(text.length).toBeLessThanOrEqual(JUDGE_MAX_CHARS);expect(text).toContain('Entrega la mejor respuesta final posible');});
 it('aggregates usage from all passes',()=>{expect(aggregateUsage([{input_tokens:100,output_tokens:40,input_tokens_details:{cached_tokens:10}},{input_tokens:80,output_tokens:30,input_tokens_details:{cached_tokens:5}},undefined])).toEqual({input_tokens:180,output_tokens:70,input_tokens_details:{cached_tokens:15}});});
});
