import {describe,expect,it} from 'vitest';
import {createExecutionPlan,hashExecutionPlan,verifyExecutionPlan,type ExecutionPlanInput} from './execution-plan';
const input=(overrides:Partial<ExecutionPlanInput>={}):ExecutionPlanInput=>({task:'consulta general',route:{model:'@cf/meta/llama-3.2-3b-instruct',tier:'balanced',reasoning:'medium',needsWeb:false},provider:{requested:'cloudflare',reason:'modelo abierto'},cognition:{mode:'single',passes:1,reason:'una pasada'},allowedModels:['@cf/meta/llama-3.2-3b-instruct'],policySummary:'Chat abierto.',...overrides});
describe('execution plan',()=>{
 it('produce un hash determinista',async()=>{expect(await hashExecutionPlan(input())).toBe(await hashExecutionPlan({...input()}));});
 it('acepta una ejecución abierta exacta',async()=>{const plan=await createExecutionPlan(input());expect(verifyExecutionPlan(plan,{model:'@cf/meta/llama-3.2-3b-instruct',tier:'balanced',provider:'cloudflare',cognitiveMode:'single',deliberationPasses:1})).toMatchObject({ok:true,status:'exact'});});
 it('normaliza Qwen a su modelo real y una inferencia',async()=>{const plan=await createExecutionPlan(input({provider:{requested:'huggingface',reason:'Qwen preferido'},cognition:{mode:'ensemble',passes:3,reason:'profundo'}}));expect(plan.route.model).toBe('Qwen/Qwen3-4B-Instruct-2507');expect(plan.cognition).toMatchObject({mode:'single',passes:1});});
 it('permite Qwen a Cloudflare pero nunca a OpenAI',async()=>{const plan=await createExecutionPlan(input({provider:{requested:'huggingface',reason:'Qwen'},allowedModels:['Qwen/Qwen3-4B-Instruct-2507']}));expect(verifyExecutionPlan(plan,{model:'@cf/meta/llama-3.2-3b-instruct',tier:'balanced',provider:'cloudflare',fallback:true,cognitiveMode:'single',deliberationPasses:1}).status).toBe('allowed-fallback');expect(verifyExecutionPlan(plan,{model:'gpt-any',tier:'balanced',provider:'openai',fallback:true,cognitiveMode:'single',deliberationPasses:1}).status).toBe('drift');});
 it('rechaza OpenAI incluso en un plan legado',async()=>{const plan=await createExecutionPlan(input({provider:{requested:'openai',reason:'legado'},allowedModels:['gpt-any']}));const result=verifyExecutionPlan(plan,{model:'gpt-any',tier:'balanced',provider:'openai',cognitiveMode:'single',deliberationPasses:1});expect(result.ok).toBe(false);expect(result.differences.join(' ')).toMatch(/no está autorizado/);});
 it('acepta reglas y utilidades abiertas registradas',async()=>{const plan=await createExecutionPlan(input());expect(verifyExecutionPlan(plan,{model:'hector-rules-v1',tier:'balanced',provider:'cloudflare',cognitiveMode:'single',deliberationPasses:1}).ok).toBe(true);expect(verifyExecutionPlan(plan,{model:'@cf/ibm-granite/granite-4.0-h-micro',tier:'balanced',provider:'cloudflare',cognitiveMode:'single',deliberationPasses:1}).ok).toBe(true);});
});
