export type ForecastAccuracyRow={model?:string|null;estimated_cost_usd?:number|null;metadata_json?:string|null;created_at?:string|null};
export type ForecastAccuracySample={model:string;tier:string;passes:number;forecastUsd:number;actualUsd:number;ratio:number;absolutePercentError:number;createdAt:string|null};
export type ForecastAccuracySummary={sampleCount:number;meanAbsolutePercentError:number;biasPercent:number;medianRatio:number;recommendedMultiplier:number;calibrationReady:boolean;byModel:Array<{model:string;sampleCount:number;meanAbsolutePercentError:number;biasPercent:number;medianRatio:number;recommendedMultiplier:number}>};

function finitePositive(value:unknown){const n=Number(value);return Number.isFinite(n)&&n>0?n:null;}
function clamp(value:number,min:number,max:number){return Math.min(max,Math.max(min,value));}
function median(values:number[]){if(!values.length)return 1;const sorted=[...values].sort((a,b)=>a-b),mid=Math.floor(sorted.length/2);return sorted.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2;}
function parseProjection(metadata:unknown){if(!metadata||typeof metadata!=='object')return null;const root=metadata as Record<string,unknown>,budget=(root.budgetDecision&&typeof root.budgetDecision==='object'?root.budgetDecision:root) as Record<string,unknown>,projection=(budget.projection&&typeof budget.projection==='object'?budget.projection:null) as Record<string,unknown>|null;if(!projection)return null;const forecastUsd=finitePositive(projection.estimatedCostUsd);if(!forecastUsd)return null;return{forecastUsd,model:String(projection.model||root.pricingModel||''),tier:String(projection.tier||root.tier||'unknown'),passes:Number(projection.passes||root.deliberationPasses||1)};}
export function extractForecastAccuracySample(row:ForecastAccuracyRow):ForecastAccuracySample|null{const actualUsd=finitePositive(row.estimated_cost_usd);if(!actualUsd)return null;let metadata:unknown;try{metadata=JSON.parse(String(row.metadata_json||'{}'));}catch{return null;}const projection=parseProjection(metadata);if(!projection)return null;const ratio=actualUsd/projection.forecastUsd;return{model:projection.model||String(row.model||'unknown'),tier:projection.tier,passes:Number.isFinite(projection.passes)?projection.passes:1,forecastUsd:projection.forecastUsd,actualUsd,ratio,absolutePercentError:Math.abs(actualUsd-projection.forecastUsd)/actualUsd*100,createdAt:row.created_at||null};}
function summarize(samples:ForecastAccuracySample[]){const ratios=samples.map(x=>x.ratio),forecast=samples.reduce((s,x)=>s+x.forecastUsd,0),actual=samples.reduce((s,x)=>s+x.actualUsd,0),mape=samples.length?samples.reduce((s,x)=>s+x.absolutePercentError,0)/samples.length:0,bias=actual?((forecast-actual)/actual)*100:0,medianRatio=median(ratios);return{sampleCount:samples.length,meanAbsolutePercentError:mape,biasPercent:bias,medianRatio,recommendedMultiplier:samples.length>=5?clamp(medianRatio,.5,2):1};}
export function aggregateForecastAccuracy(rows:ForecastAccuracyRow[]):ForecastAccuracySummary{const samples=rows.map(extractForecastAccuracySample).filter((x):x is ForecastAccuracySample=>!!x),overall=summarize(samples),groups=new Map<string,ForecastAccuracySample[]>();for(const sample of samples){const list=groups.get(sample.model)||[];list.push(sample);groups.set(sample.model,list);}const byModel=[...groups.entries()].map(([model,items])=>({model,...summarize(items)})).sort((a,b)=>b.sampleCount-a.sampleCount);return{...overall,calibrationReady:samples.length>=5,byModel};}
export async function loadForecastAccuracy(db:D1Database,userId:string){const rows=(await db.prepare(`SELECT model,estimated_cost_usd,metadata_json,created_at FROM api_usage WHERE user_id=? AND created_at>=datetime('now','-30 days') AND metadata_json IS NOT NULL ORDER BY created_at DESC LIMIT 500`).bind(userId).all<ForecastAccuracyRow>()).results||[];return aggregateForecastAccuracy(rows);}
