import {describe,expect,it} from 'vitest';
import {cloudflareFreeProfile,detectFreeCapability,freeFirstBudget,tryDeterministicFreeInference,withTimeout} from './free-first';
describe('free-first inference',()=>{
 it('clasifica tareas comunes sin llamar a ningún modelo',()=>{const result=tryDeterministicFreeInference('Clasifica: corrige el error de TypeScript y ejecuta pruebas');expect(result).toMatchObject({capability:'classify',source:'rules',advancedCalls:0,freeModelCalls:0});expect(result?.text).toContain('ingeniería de software');});
 it('extrae entidades estructuradas con reglas locales',()=>{const result=tryDeterministicFreeInference('Extrae correos, enlaces, números y fechas: escribe a hector@example.com, abre https://example.com/tarea y paga 250 el 2026-07-22');expect(result?.text).toContain('hector@example.com');expect(result?.text).toContain('https://example.com/tarea');expect(result?.text).toContain('250');expect(result?.text).toContain('2026-07-22');});
 it('enruta y valida JSON sin inferencia',()=>{expect(tryDeterministicFreeInference('Enruta: implementa una arquitectura completa en Cloudflare')?.text).toContain('Ruta: deep');expect(tryDeterministicFreeInference('Valida JSON: {"ok":true}')?.text).toContain('JSON válido');expect(tryDeterministicFreeInference('Valida JSON: {ok:true}')?.text).toContain('JSON inválido');});
 it('limita a cero llamadas avanzadas cuando las reglas bastan',()=>{expect(freeFirstBudget('Clasifica: hola')).toMatchObject({maxFreeModelCalls:0,maxAdvancedCalls:0});expect(freeFirstBudget('Resume: un documento largo')).toMatchObject({capability:'summarize',maxFreeModelCalls:1,maxAdvancedCalls:1});});
 it('permite como máximo una llamada gratuita y un solo fallback en tareas generales',()=>{expect(freeFirstBudget('Explica brevemente este concepto')).toEqual({capability:'general',maxFreeModelCalls:1,maxAdvancedCalls:1,reason:'Se intenta primero Workers AI cuando la política de riesgo y complejidad lo permite.'});});
 it('selecciona Granite para utilidades y un modelo general separado',()=>{expect(detectFreeCapability('Resume: este texto')).toBe('summarize');expect(cloudflareFreeProfile({},'Resume: este texto')).toMatchObject({model:'@cf/ibm-granite/granite-4.0-h-micro',maxTokens:360,temperature:.1});expect(cloudflareFreeProfile({},'Hola, ¿cómo estás?').model).toBe('@cf/meta/llama-3.2-3b-instruct');});
 it('aplica timeout estricto sin afectar respuestas rápidas',async()=>{await expect(withTimeout(Promise.resolve('ok'),20)).resolves.toBe('ok');await expect(withTimeout(new Promise(()=>{}),5)).rejects.toThrow(/excedió/);});
});
