import {classifyReuseRisk,type ReuseRisk} from './runtime-reuse';

export type FreeFirstTaskKind='classification'|'extraction'|'transformation'|'retrieval'|'reasoning'|'web'|'sensitive';
export type FreeFirstPolicy={version:'1.0.0';taskKind:FreeFirstTaskKind;risk:ReuseRisk;cacheable:boolean;freeProviderEligible:boolean;maxAdvancedCalls:1|3;baselineAdvancedCalls:1|3;estimatedAdvancedCallsAvoided:number;contextCharLimit:number;reason:string};
export type ExactInferenceCacheEntry={cacheKey:string;text:string;provider:string;model:string;estimatedCostUsd:number;createdAt:string;hitCount:number};
export type InferenceEventInput={userId:string;executionId:string;taskKind:FreeFirstTaskKind;routeTier:string;requestedProvider:string;actualProvider:string;model:string;modelCalls:number;advancedCalls:number;freeCalls:number;cacheHit:boolean;inputTokens:number;outputTokens:number;estimatedCostUsd:number;estimatedCostAvoidedUsd:number;reason:string};
const CLASSIFY=/\b(clasifica|categoriza|etiqueta|detecta intenci[oó]n|elige ruta|routing|prioriza)\b/i,EXTRACT=/\b(extrae|parsea|identifica campos|estructura|convierte a json|normaliza datos|resume datos)\b/i,TRANSFORM=/\b(traduce|reformula|reescribe|formatea|corrige gram[aá]tica|ordena|deduplica|acorta)\b/i,RETRIEVE=/\b(busca en memoria|recupera|encuentra experiencia|consulta historial|reutiliza|cach[eé])\b/i,WEB=/\b(internet|web|noticias|hoy|actual|reciente|precio|clima|busca fuentes|investiga en l[ií]nea)\b/i,SENSITIVE=/\b(salud|m[eé]dic|dosis|legal|demanda|finanzas|saldo|banco|inversi[oó]n|contrase[nñ]a|secreto|token|vulnerabilidad)\b/i,MULTI_PASS=/\b(doble verificaci[oó]n|dos soluciones independientes|tres pasadas|ensemble|juez de s[ií]ntesis|compara dos respuestas)\b/i;
export function normalizeFreeFirstText(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();}
export function classifyFreeFirstTask(prompt:string,needsWeb=false):FreeFirstTaskKind{if(needsWeb||WEB.test(prompt))return'web';if(SENSITIVE.test(prompt))return'sensitive';if(CLASSIFY.test(prompt))return'classification';if(EXTRACT.test(prompt))return'extraction';if(TRANSFORM.test(prompt))return'transformation';if(RETRIEVE.test(prompt))return'retrieval';return'reasoning';}
export function createFreeFirstPolicy(input:{prompt:string;needsWeb?:boolean;reasoningLevel?:'auto'|'high';enabled?:boolean}):FreeFirstPolicy{const enabled=input.enabled!==false,taskKind=classifyFreeFirstTask(input.prompt,Boolean(input.needsWeb)),risk=classifyReuseRisk(input.prompt),explicitMulti=MULTI_PASS.test(input.prompt),baselineAdvancedCalls:1|3=input.reasoningLevel==='high'||explicitMulti?3:1,maxAdvancedCalls:1|3=!enabled||explicitMulti?baselineAdvancedCalls:1,freeProviderEligible=enabled&&risk!=='high'&&!input.needsWeb&&['classification','extraction','transformation','retrieval'].includes(taskKind),cacheable=enabled&&risk==='low'&&!input.needsWeb&&taskKind!=='web'&&taskKind!=='sensitive',contextCharLimit=taskKind==='reasoning'||taskKind==='sensitive'?24000:12000,avoided=Math.max(0,baselineAdvancedCalls-maxAdvancedCalls),reason=!enabled?'free-first desactivado':explicitMulti?'múltiples pasadas solicitadas explícitamente':avoided?`razonamiento alto conservado en una sola inferencia; ${avoided} llamadas avanzadas evitadas`:(freeProviderEligible?'tarea apta para reglas, caché o Workers AI':'una sola inferencia avanzada como máximo');return{version:'1.0.0',taskKind,risk,cacheable,freeProviderEligible,maxAdvancedCalls,baselineAdvancedCalls,estimatedAdvancedCallsAvoided:avoided,contextCharLimit,reason};}
export function compactFreeFirstContext(value:string,maxChars=12000){const paragraphs=value.split(/\n{2,}/).map(item=>item.trim()).filter(Boolean),seen=new Set<string>(),unique:string[]=[];for(const paragraph of paragraphs){const key=normalizeFreeFirstText(paragraph);if(!key||seen.has(key))continue;seen.add(key);unique.push(paragraph);}const joined=unique.join('\n\n');if(joined.length<=maxChars)return joined;const marker='\n\n[…contexto intermedio compactado por free-first…]\n\n',remaining=Math.max(0,maxChars-marker.length),head=Math.ceil(remaining*.72),tail=Math.max(0,remaining-head);return`${joined.slice(0,head)}${marker}${tail?joined.slice(-tail):''}`;}
export async function createExactInferenceCacheKey(input:{userId:string;prompt:string;context?:string;version?:string}){const canonical=[input.version||'v1',input.userId,normalizeFreeFirstText(input.prompt),normalizeFreeFirstText(input.context||'')].join('\n'),digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical));return[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('');}
export async function loadExactInferenceCache(db:D1Database,userId:string,cacheKey:string):Promise<ExactInferenceCacheEntry|null>{try{const row=await db.prepare("SELECT cache_key,text,provider,model,estimated_cost_usd,created_at,hit_count FROM inference_cache WHERE user_id=? AND cache_key=? AND verified=1 AND (expires_at IS NULL OR expires_at>datetime('now'))").bind(userId,cacheKey).first<any>();if(!row)return null;await db.prepare("UPDATE inference_cache SET hit_count=hit_count+1,last_hit_at=datetime('now') WHERE user_id=? AND cache_key=?").bind(userId,cacheKey).run();return{cacheKey:row.cache_key,text:row.text,provider:row.provider||'local',model:row.model||'hector-exact-cache',estimatedCostUsd:Math.max(0,Number(row.estimated_cost_usd)||0),createdAt:row.created_at,hitCount:Math.max(0,Number(row.hit_count)||0)+1};}catch{return null;}}
export async function saveExactInferenceCache(db:D1Database,input:{userId:string;cacheKey:string;objectiveNormalized:string;text:string;provider:string;model:string;verificationJson:string;estimatedCostUsd:number;ttlSeconds?:number}){try{const ttl=Math.max(300,Math.min(604800,Math.floor(input.ttlSeconds||86400)));await db.prepare("INSERT INTO inference_cache(id,user_id,cache_key,objective_normalized,text,provider,model,verification_json,verified,estimated_cost_usd,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,1,?,datetime('now','+'||?||' seconds'),datetime('now'),datetime('now')) ON CONFLICT(user_id,cache_key) DO UPDATE SET objective_normalized=excluded.objective_normalized,text=excluded.text,provider=excluded.provider,model=excluded.model,verification_json=excluded.verification_json,verified=1,estimated_cost_usd=excluded.estimated_cost_usd,expires_at=excluded.expires_at,updated_at=datetime('now')").bind(crypto.randomUUID(),input.userId,input.cacheKey,input.objectiveNormalized,input.text,input.provider,input.model,input.verificationJson,Math.max(0,input.estimatedCostUsd),String(ttl)).run();}catch{}}
export async function recordInferenceEvent(db:D1Database,input:InferenceEventInput){try{await db.prepare("INSERT INTO inference_events(id,user_id,execution_id,task_kind,route_tier,requested_provider,actual_provider,model,model_calls,advanced_calls,free_calls,cache_hit,input_tokens,output_tokens,estimated_cost_usd,estimated_cost_avoided_usd,reason,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,datetime('now'))").bind(crypto.randomUUID(),input.userId,input.executionId,input.taskKind,input.routeTier,input.requestedProvider,input.actualProvider,input.model,input.modelCalls,input.advancedCalls,input.freeCalls,input.cacheHit?1:0,input.inputTokens,input.outputTokens,input.estimatedCostUsd,input.estimatedCostAvoidedUsd,input.reason.slice(0,1000)).run();}catch{}}
export function freeFirstBenchmark(){const scenarios=[{name:'conocida',advancedCalls:0,freeCalls:0,cacheHit:true,success:true},{name:'parcialmente conocida',advancedCalls:1,freeCalls:0,cacheHit:false,success:true},{name:'nueva',advancedCalls:1,freeCalls:0,cacheHit:false,success:true},{name:'clasificación',advancedCalls:0,freeCalls:1,cacheHit:false,success:true},{name:'alto riesgo',advancedCalls:0,freeCalls:0,cacheHit:false,success:true}],baselineAdvancedCalls=scenarios.length*3,advancedCalls=scenarios.reduce((sum,item)=>sum+item.advancedCalls,0),freeCalls=scenarios.reduce((sum,item)=>sum+item.freeCalls,0),cacheHits=scenarios.filter(item=>item.cacheHit).length;return{scenarios:scenarios.length,successRate:scenarios.filter(item=>item.success).length/scenarios.length,baselineAdvancedCalls,advancedCalls,freeCalls,cacheHits,advancedCallsAvoided:baselineAdvancedCalls-advancedCalls,reductionRate:(baselineAdvancedCalls-advancedCalls)/baselineAdvancedCalls};}
