import {describe,expect,it} from 'vitest';
import {compressMemoryContext,lexicalSimilarity,loadHybridRuntimeCandidates,normalizeMemoryText,rankHybridMemory,shouldUseEmbedding,stablePromptHash,type HybridMemoryItem} from './hybrid-memory';
const item=(o:Partial<HybridMemoryItem>={}):HybridMemoryItem=>({id:'m1',userId:'u1',sourceType:'experience',sourceId:'e1',title:'Corregir compilación TypeScript',content:'Ejecutar typecheck, localizar error y validar pruebas.',normalizedText:'corregir compilacion typescript ejecutar typecheck pruebas',tags:['github-code','typecheck'],verified:true,successRate:.95,confidence:.92,estimatedCostUsd:.02,createdAt:'2026-07-20T00:00:00Z',updatedAt:'2026-07-21T00:00:00Z',...o});
describe('hybrid memory',()=>{
 it('normaliza y compara sin embeddings',()=>{expect(normalizeMemoryText('Compilación MÉDICA')).toBe('compilacion medica');expect(lexicalSimilarity('corrige compilación typescript','corregir compilacion typescript')).toBeGreaterThan(.5);});
 it('excluye no verificados, deduplica y bloquea contaminación',()=>{const hits=rankHybridMemory('corrige error de compilación TypeScript',[item(),item({id:'dup',confidence:.4}),item({id:'medical',sourceId:'med',title:'Evaluar paciente',normalizedText:'evaluar paciente medico',content:'Revisar expediente',tags:['medical']}),item({id:'unsafe',sourceId:'unsafe',verified:false})],{now:Date.parse('2026-07-22T00:00:00Z')});expect(hits.map(h=>h.sourceId)).toEqual(['e1']);});
 it('recomienda embeddings solo en la zona ambigua',()=>{expect(shouldUseEmbedding({query:'corrige compilacion typescript',bestLexicalScore:.8,candidateCount:20})).toBe(false);expect(shouldUseEmbedding({query:'analiza comportamiento inesperado complejo',bestLexicalScore:.3,candidateCount:8})).toBe(true);expect(shouldUseEmbedding({query:'hola',bestLexicalScore:.2,candidateCount:8})).toBe(false);});
 it('comprime contexto y mantiene hash estable',()=>{const hits=rankHybridMemory('corrige compilación TypeScript',[item()],{now:Date.parse('2026-07-22T00:00:00Z')});const context=compressMemoryContext(hits,500);expect(context.length).toBeLessThanOrEqual(500);expect(context).toContain('experience:e1');expect(stablePromptHash(' Corrige compilación ')).toBe(stablePromptHash('corrige compilacion'));});
 it('carga solo experiencias con evidencia verificada',async()=>{const db={prepare:(sql:string)=>({bind:()=>({all:async()=>sql.includes('memory_items_fts')?{results:[]}:{results:[{id:'e1',user_id:'u1',objective:'Corregir compilación TypeScript',objective_normalized:'corregir compilacion typescript',result:'Ejecutar typecheck y pruebas',skills_json:'["github-code"]',verified:1,attempts:1,estimated_cost_usd:.02,created_at:'2026-07-21T00:00:00Z',evidence_json:'[{"verified":true}]'},{id:'bad',user_id:'u1',objective:'Otro',objective_normalized:'otro',result:'No comprobado',skills_json:'[]',verified:1,attempts:1,created_at:'2026-07-21T00:00:00Z',evidence_json:'[]'}]}})})} as any;const candidates=await loadHybridRuntimeCandidates(db,'u1','corrige compilación typescript');expect(candidates.map(c=>c.id)).toEqual(['experience:e1']);});
});
