import {classifyReuseRisk,type RuntimeReuseCandidate} from './runtime-reuse';

export type HybridMemoryItem={id:string;userId:string;sourceType:'experience'|'skill'|'document'|'result'|'rule';sourceId:string;title:string;content:string;normalizedText:string;tags:string[];verified:boolean;successRate:number;confidence:number;estimatedCostUsd:number;createdAt:string|null;updatedAt:string|null};
export type HybridMemoryHit=HybridMemoryItem&{lexicalScore:number;tagScore:number;recencyScore:number;qualityScore:number;finalScore:number};
export type HybridMemoryDb={prepare:(sql:string)=>any};
const STOP=new Set(['para','como','esta','este','esto','desde','hasta','sobre','entre','todos','todas','cada','solo','pero','porque','cuando','donde','quiere','quiero','hacer','hace','hector','the','and','with','from']);
const clamp=(v:number)=>Math.max(0,Math.min(1,Number.isFinite(v)?v:0));
export function normalizeMemoryText(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9\s_-]+/g,' ').replace(/\s+/g,' ').trim();}
export function memoryTokens(v:string){return[...new Set(normalizeMemoryText(v).split(' ').filter(t=>t.length>=3&&!STOP.has(t)))];}
export function lexicalSimilarity(a:string,b:string){const x=new Set(memoryTokens(a)),y=new Set(memoryTokens(b));if(!x.size||!y.size)return 0;let n=0;for(const t of x)if(y.has(t))n++;return clamp((n/(x.size+y.size-n))*.65+(n/Math.max(1,Math.min(x.size,y.size)))*.35);}
export function memoryRecencyScore(v:string|null|undefined,now=Date.now()){const t=v?Date.parse(v):NaN;if(!Number.isFinite(t))return.15;return Math.exp(-Math.max(0,(now-t)/86_400_000)/180);}
export function shouldUseEmbedding(i:{query:string;bestLexicalScore:number;candidateCount:number}){const n=memoryTokens(i.query).length;return n>=3&&i.candidateCount>=4&&i.bestLexicalScore>=.16&&i.bestLexicalScore<.68;}
function parseTags(v:string|null){try{const p=JSON.parse(v||'[]');return Array.isArray(p)?p.filter(x=>typeof x==='string').slice(0,24):[];}catch{return[];}}
function tagScore(q:string,tags:string[]){const set=new Set(memoryTokens(q));if(!tags.length)return 0;let n=0;for(const tag of tags)if(memoryTokens(tag).some(t=>set.has(t)))n++;return clamp(n/tags.length);}
export function rankHybridMemory(query:string,items:HybridMemoryItem[],o:{limit?:number;minScore?:number;now?:number}={}){const out=new Map<string,HybridMemoryHit>(),now=o.now??Date.now();for(const item of items){if(!item.verified)continue;const lexicalScore=lexicalSimilarity(query,`${item.title} ${item.normalizedText} ${item.tags.join(' ')}`),tags=tagScore(query,item.tags);if(lexicalScore<.12&&tags===0)continue;const recencyScore=memoryRecencyScore(item.updatedAt||item.createdAt,now),qualityScore=clamp(item.confidence*.48+item.successRate*.42+.1),finalScore=clamp(lexicalScore*.54+tags*.12+recencyScore*.12+qualityScore*.2+(item.estimatedCostUsd>0?.02:0));if(finalScore<(o.minScore??.28))continue;const hit={...item,lexicalScore,tagScore:tags,recencyScore,qualityScore,finalScore},key=`${item.sourceType}:${item.sourceId}`,old=out.get(key);if(!old||hit.finalScore>old.finalScore)out.set(key,hit);}return[...out.values()].sort((a,b)=>b.finalScore-a.finalScore||b.recencyScore-a.recencyScore).slice(0,Math.max(1,Math.min(20,o.limit??6)));}
export function compressMemoryContext(hits:HybridMemoryHit[],max=4200){const out:string[]=[];let used=0;for(const h of hits){const s=`[${h.sourceType}:${h.sourceId}] ${h.title||h.normalizedText.slice(0,120)}\n${h.content.replace(/\s+/g,' ').trim().slice(0,1200)}\nConfianza ${(h.confidence*100).toFixed(0)}% · Éxito ${(h.successRate*100).toFixed(0)}%`;if(used+s.length>max)continue;out.push(s);used+=s.length;}return out.join('\n\n');}
export async function loadHybridMemory(db:HybridMemoryDb,userId:string,query:string){const items:HybridMemoryItem[]=[];try{const match=memoryTokens(query).map(t=>`"${t}"*`).join(' OR ');if(match){const rows=(await db.prepare(`SELECT m.* FROM memory_items_fts f JOIN memory_items m ON m.id=f.item_id WHERE f.user_id=? AND memory_items_fts MATCH ? AND m.verified=1 ORDER BY bm25(memory_items_fts) LIMIT 80`).bind(userId,match).all()).results;for(const r of rows)items.push({id:r.id,userId:r.user_id,sourceType:r.source_type,sourceId:r.source_id,title:r.title||'',content:r.content||'',normalizedText:r.normalized_text||'',tags:parseTags(r.tags_json),verified:r.verified===1,successRate:clamp(Number(r.success_rate)||0),confidence:clamp(Number(r.confidence)||0),estimatedCostUsd:Math.max(0,Number(r.estimated_cost_usd)||0),createdAt:r.created_at||null,updatedAt:r.updated_at||null});}}catch{}
 try{const rows=(await db.prepare("SELECT id,user_id,objective,objective_normalized,result,skills_json,verified,attempts,estimated_cost_usd,created_at,evidence_json FROM agent_experiences WHERE user_id=? AND status='completed' AND verified=1 AND result IS NOT NULL ORDER BY created_at DESC LIMIT 120").bind(userId).all()).results;for(const r of rows){let evidence:any[]=[];try{evidence=JSON.parse(r.evidence_json||'[]');}catch{}if(!Array.isArray(evidence)||!evidence.some(e=>e?.verified===true))continue;const attempts=Math.max(1,Number(r.attempts)||1),confidence=clamp(.95-(attempts-1)*.06);items.push({id:`experience:${r.id}`,userId:r.user_id,sourceType:'experience',sourceId:r.id,title:r.objective||'',content:r.result||'',normalizedText:r.objective_normalized||normalizeMemoryText(r.objective||''),tags:parseTags(r.skills_json),verified:true,successRate:confidence,confidence,estimatedCostUsd:Math.max(0,Number(r.estimated_cost_usd)||0),createdAt:r.created_at||null,updatedAt:r.created_at||null});}}catch{}
 return items;}
function reusableOutput(v:string){return v.match(/(?:^|\n)REUSABLE_OUTPUT\s*:\s*([\s\S]+)$/i)?.[1]?.trim();}
export async function loadHybridRuntimeCandidates(db:HybridMemoryDb,userId:string,query:string):Promise<RuntimeReuseCandidate[]>{const items=await loadHybridMemory(db,userId,query),hits=rankHybridMemory(query,items,{limit:12});return hits.map(h=>{const output=reusableOutput(h.content);return{id:h.id,source:h.sourceType==='experience'||h.sourceType==='skill'||h.sourceType==='rule'?h.sourceType:'rule',taskType:h.tags[0]||h.sourceType,risk:classifyReuseRisk(`${h.title} ${h.normalizedText}`),confidence:h.confidence,successRate:h.successRate,recencyScore:h.recencyScore,estimatedCostUsd:h.estimatedCostUsd,trigger:h.normalizedText||h.title,procedure:h.content.replace(/(?:^|\n)REUSABLE_OUTPUT\s*:[\s\S]+$/i,'').trim().slice(0,4000),mode:output?'deterministic':'context',deterministicOutput:output};});}
export function stablePromptHash(v:string){let h=2166136261;for(const c of normalizeMemoryText(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');}
export async function readSemanticCache<T>(db:HybridMemoryDb,userId:string,namespace:string,prompt:string):Promise<T|null>{try{const row=await db.prepare("SELECT response_json FROM semantic_cache WHERE user_id=? AND namespace=? AND prompt_hash=? AND (expires_at IS NULL OR expires_at>CURRENT_TIMESTAMP) LIMIT 1").bind(userId,namespace,stablePromptHash(prompt)).first();return row?JSON.parse(row.response_json) as T:null;}catch{return null;}}
export async function writeSemanticCache(db:HybridMemoryDb,i:{userId:string;namespace:string;prompt:string;response:unknown;confidence:number;ttlSeconds?:number}){try{const hash=stablePromptHash(i.prompt),expires=i.ttlSeconds?new Date(Date.now()+Math.max(60,i.ttlSeconds)*1000).toISOString():null;await db.prepare("INSERT INTO semantic_cache(id,user_id,namespace,prompt_hash,normalized_prompt,response_json,confidence,expires_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(user_id,namespace,prompt_hash) DO UPDATE SET response_json=excluded.response_json,confidence=excluded.confidence,expires_at=excluded.expires_at,updated_at=CURRENT_TIMESTAMP").bind(`cache:${i.userId}:${i.namespace}:${hash}`,i.userId,i.namespace,hash,normalizeMemoryText(i.prompt),JSON.stringify(i.response),clamp(i.confidence),expires).run();return true;}catch{return false;}}
export async function invalidateSemanticCache(db:HybridMemoryDb,userId:string,namespace:string){try{await db.prepare('DELETE FROM semantic_cache WHERE user_id=? AND namespace=?').bind(userId,namespace).run();return true;}catch{return false;}}
