import type {DeliberationProfile} from './deliberation';
import type {MetacognitiveProfile} from './metacognitive-calibration';
import type {Route} from './openai';
import type {ProviderDecision,ProviderName} from './providers';

export type StrategyRisk='low'|'medium'|'high';
export type CognitiveStrategy={routeTier:'fast'|'balanced'|'deep';provider:ProviderName;cognitiveMode:'single'|'ensemble'};
export type StrategyOutcomeRow={route_tier:string;requested_provider:string;cognitive_mode:string;success:number|boolean;advanced_calls:number;cost_usd:number;duration_ms:number};
export type StrategyProfile=CognitiveStrategy&{strategyKey:string;sampleCount:number;successes:number;posteriorMean:number;lowerBound:number;uncertainty:number;averageAdvancedCalls:number;averageCostUsd:number;averageDurationMs:number;utility:number};
export type StrategySelection={version:'1.0.0';action:'keep'|'conserve'|'escalate';currentStrategy:string;selectedStrategy:string;sampleCount:number;successEstimate:number;lowerBound:number;expectedCallsSaved:number;reason:string};

type CurrentStrategyPlan={route:Route;provider:ProviderDecision;cognition:DeliberationProfile};
type ModelEnv={OPENAI_MODEL:string;OPENAI_MODEL_FAST?:string;OPENAI_MODEL_BALANCED?:string;OPENAI_MODEL_REASONING?:string};
const clamp=(value:number)=>Math.max(0,Math.min(1,Number.isFinite(value)?value:0));
const calls=(strategy:CognitiveStrategy)=>strategy.provider==='cloudflare'?0:strategy.cognitiveMode==='ensemble'?3:1;
const strength=(strategy:CognitiveStrategy)=>(strategy.routeTier==='fast'?0:strategy.routeTier==='balanced'?1:2)+(strategy.provider==='openai'?1:0)+(strategy.cognitiveMode==='ensemble'?2:0);
export function cognitiveStrategyKey(strategy:CognitiveStrategy){return`${strategy.routeTier}:${strategy.provider}:${strategy.cognitiveMode}`;}
function parse(row:StrategyOutcomeRow):CognitiveStrategy|null{const routeTier=row.route_tier==='fast'||row.route_tier==='balanced'||row.route_tier==='deep'?row.route_tier:null,provider=row.requested_provider==='cloudflare'||row.requested_provider==='openai'?row.requested_provider:null,cognitiveMode=row.cognitive_mode==='single'||row.cognitive_mode==='ensemble'?row.cognitive_mode:null;return routeTier&&provider&&cognitiveMode?{routeTier,provider,cognitiveMode}:null;}
export function summarizeStrategyProfiles(rows:StrategyOutcomeRow[]):StrategyProfile[]{const groups=new Map<string,{strategy:CognitiveStrategy;rows:StrategyOutcomeRow[]}>();for(const row of rows){const strategy=parse(row);if(!strategy)continue;const key=cognitiveStrategyKey(strategy),group=groups.get(key)||{strategy,rows:[]};group.rows.push(row);groups.set(key,group);}return[...groups.entries()].map(([strategyKey,group])=>{const sampleCount=group.rows.length,successes=group.rows.filter(row=>Boolean(Number(row.success))).length,alpha=successes+1,beta=sampleCount-successes+1,posteriorMean=alpha/(alpha+beta),variance=alpha*beta/((alpha+beta)**2*(alpha+beta+1)),uncertainty=Math.sqrt(variance),lowerBound=clamp(posteriorMean-1.64*uncertainty),averageAdvancedCalls=group.rows.reduce((sum,row)=>sum+Math.max(0,Number(row.advanced_calls)||0),0)/Math.max(1,sampleCount),averageCostUsd=group.rows.reduce((sum,row)=>sum+Math.max(0,Number(row.cost_usd)||0),0)/Math.max(1,sampleCount),averageDurationMs=group.rows.reduce((sum,row)=>sum+Math.max(0,Number(row.duration_ms)||0),0)/Math.max(1,sampleCount),utility=clamp(posteriorMean-Math.min(.22,averageAdvancedCalls*.045)-Math.min(.2,averageCostUsd*4));return{...group.strategy,strategyKey,sampleCount,successes,posteriorMean,lowerBound,uncertainty,averageAdvancedCalls,averageCostUsd,averageDurationMs,utility};}).sort((a,b)=>b.utility-a.utility||b.sampleCount-a.sampleCount);}
function current(plan:CurrentStrategyPlan):CognitiveStrategy{return{routeTier:plan.route.tier,provider:plan.provider.provider,cognitiveMode:plan.cognition.mode};}
function compatible(profile:StrategyProfile,input:{risk:StrategyRisk;needsWeb:boolean;reasoningLevel:'auto'|'high'}){if(input.needsWeb&&profile.provider!=='openai')return false;if(input.risk!=='low'&&profile.provider==='cloudflare')return false;if(input.reasoningLevel==='high'&&profile.routeTier!=='deep')return false;return true;}
export function selectMetacognitiveStrategy(input:CurrentStrategyPlan&{profiles:StrategyProfile[];risk:StrategyRisk;reasoningLevel:'auto'|'high';calibration:MetacognitiveProfile}):StrategySelection{const active=current(input),activeKey=cognitiveStrategyKey(active),activeProfile=input.profiles.find(profile=>profile.strategyKey===activeKey),eligible=input.profiles.filter(profile=>profile.sampleCount>=8&&compatible(profile,{risk:input.risk,needsWeb:input.route.needsWeb,reasoningLevel:input.reasoningLevel}));if(input.reasoningLevel==='auto'&&input.risk==='low'&&!input.route.needsWeb&&!input.calibration.preferDeep&&!input.calibration.requireVerification){const cheaper=eligible.filter(profile=>profile.lowerBound>=.75&&calls(profile)<calls(active)&&profile.utility>=(activeProfile?.utility??0)-.02).sort((a,b)=>b.utility-a.utility||a.averageAdvancedCalls-b.averageAdvancedCalls)[0];if(cheaper)return{version:'1.0.0',action:'conserve',currentStrategy:activeKey,selectedStrategy:cheaper.strategyKey,sampleCount:cheaper.sampleCount,successEstimate:cheaper.posteriorMean,lowerBound:cheaper.lowerBound,expectedCallsSaved:Math.max(0,calls(active)-calls(cheaper)),reason:`La estrategia ${cheaper.strategyKey} conserva un límite inferior ${(cheaper.lowerBound*100).toFixed(0)}% con menos llamadas.`};}if(activeProfile&&activeProfile.sampleCount>=6&&activeProfile.lowerBound<.55){const stronger=eligible.filter(profile=>strength(profile)>strength(active)&&profile.lowerBound>=.65&&profile.posteriorMean>=activeProfile.posteriorMean+.12).sort((a,b)=>b.utility-a.utility)[0];if(stronger)return{version:'1.0.0',action:'escalate',currentStrategy:activeKey,selectedStrategy:stronger.strategyKey,sampleCount:stronger.sampleCount,successEstimate:stronger.posteriorMean,lowerBound:stronger.lowerBound,expectedCallsSaved:Math.min(0,calls(active)-calls(stronger)),reason:`La estrategia actual solo sostiene un límite inferior ${(activeProfile.lowerBound*100).toFixed(0)}%; ${stronger.strategyKey} posee evidencia superior.`};}return{version:'1.0.0',action:'keep',currentStrategy:activeKey,selectedStrategy:activeKey,sampleCount:activeProfile?.sampleCount||0,successEstimate:activeProfile?.posteriorMean??input.calibration.accuracy,lowerBound:activeProfile?.lowerBound??Math.max(0,input.calibration.accuracy-.2),expectedCallsSaved:0,reason:activeProfile?'La estrategia actual sigue dentro de los umbrales de evidencia.':'Aún no hay suficientes resultados por estrategia; se conserva el plan calibrado global.'};}
function parseKey(value:string):CognitiveStrategy|null{const[route_tier,requested_provider,cognitive_mode]=value.split(':');return parse({route_tier,requested_provider,cognitive_mode,success:0,advanced_calls:0,cost_usd:0,duration_ms:0});}
function modelFor(env:ModelEnv,tier:CognitiveStrategy['routeTier']){return tier==='fast'?env.OPENAI_MODEL_FAST||env.OPENAI_MODEL:tier==='balanced'?env.OPENAI_MODEL_BALANCED||env.OPENAI_MODEL:env.OPENAI_MODEL_REASONING||env.OPENAI_MODEL_BALANCED||env.OPENAI_MODEL;}
export function applyStrategySelection(env:ModelEnv,plan:CurrentStrategyPlan,selection:StrategySelection):CurrentStrategyPlan{const selected=parseKey(selection.selectedStrategy);if(!selected||selection.action==='keep')return plan;return{route:{...plan.route,tier:selected.routeTier,model:modelFor(env,selected.routeTier),reason:`${plan.route.reason}; selección metacognitiva: ${selection.reason}`,reasoning:selected.routeTier==='fast'?'low':selected.routeTier==='balanced'?'medium':'high'},provider:{provider:selected.provider,reason:`selección metacognitiva basada en resultados: ${selection.reason}`},cognition:{...plan.cognition,mode:selected.cognitiveMode,candidateCount:selected.cognitiveMode==='ensemble'?2:1,reason:`selección metacognitiva basada en resultados: ${selection.reason}`}};}
export async function loadStrategyProfiles(db:D1Database,userId:string,task:string){try{const result=await db.prepare(`SELECT route_tier,requested_provider,cognitive_mode,success,advanced_calls,cost_usd,duration_ms FROM metacognitive_strategy_outcomes WHERE user_id=? AND task=? AND created_at>=datetime('now','-180 days') ORDER BY created_at DESC LIMIT 240`).bind(userId,task).all<StrategyOutcomeRow>();return summarizeStrategyProfiles(result.results||[]);}catch{return[];}}
export async function recordStrategyOutcome(db:D1Database,input:{userId:string;task:string;strategy:CognitiveStrategy;actualProvider:ProviderName;success:boolean;verificationOk:boolean;qualityAccepted:boolean;fallback:boolean;advancedCalls:number;costUsd:number;durationMs:number}){try{await db.prepare(`INSERT INTO metacognitive_strategy_outcomes(id,user_id,task,strategy_key,route_tier,requested_provider,actual_provider,cognitive_mode,success,verification_ok,quality_accepted,fallback,advanced_calls,cost_usd,duration_ms) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),input.userId,input.task,cognitiveStrategyKey(input.strategy),input.strategy.routeTier,input.strategy.provider,input.actualProvider,input.strategy.cognitiveMode,input.success?1:0,input.verificationOk?1:0,input.qualityAccepted?1:0,input.fallback?1:0,Math.max(0,input.advancedCalls),Math.max(0,input.costUsd),Math.max(0,input.durationMs)).run();return true;}catch{return false;}}
export function strategySelectionBenchmark(){const rows:StrategyOutcomeRow[]=[];const add=(strategy:CognitiveStrategy,successes:number,failures:number,advancedCalls:number)=>{for(let index=0;index<successes+failures;index++)rows.push({route_tier:strategy.routeTier,requested_provider:strategy.provider,cognitive_mode:strategy.cognitiveMode,success:index<successes?1:0,advanced_calls:advancedCalls,cost_usd:advancedCalls*.01,duration_ms:advancedCalls*1000});};add({routeTier:'fast',provider:'cloudflare',cognitiveMode:'single'},19,1,0);add({routeTier:'deep',provider:'openai',cognitiveMode:'ensemble'},8,0,3);const calibration={sampleCount:10,accuracy:.9,meanConfidence:.88,brierScore:.08,calibrationGap:.02,overconfidence:0,preferDeep:false,requireVerification:false,reason:'calibrado'},selection=selectMetacognitiveStrategy({route:{model:'deep',tier:'deep',reason:'benchmark',reasoning:'high',task:'general',needsWeb:false},provider:{provider:'openai',reason:'benchmark'},cognition:{mode:'ensemble',reason:'benchmark',candidateCount:2,highStakes:false},profiles:summarizeStrategyProfiles(rows),risk:'low',reasoningLevel:'auto',calibration});return{action:selection.action,selectedStrategy:selection.selectedStrategy,baselineAdvancedCalls:3,selectedAdvancedCalls:0,advancedCallsAvoided:selection.expectedCallsSaved};}
