import type {Route} from './openai';
export type CalibrationRow={predicted_confidence:number;correct:number|boolean;route_tier:string;provider:string;created_at?:string|null};
export type MetacognitiveProfile={sampleCount:number;accuracy:number;meanConfidence:number;brierScore:number;calibrationGap:number;overconfidence:number;preferDeep:boolean;requireVerification:boolean;reason:string};
export const METACOGNITIVE_POLICY={windowDays:45,sampleLimit:80,minSamples:8,maxBrier:.22,maxOverconfidence:.16,minAccuracyForFast:.72};
const clamp=(value:number)=>Math.max(0,Math.min(1,Number.isFinite(value)?value:0));
export function normalizeConfidence(score:number){const numeric=Number(score);return clamp(numeric>1?numeric/100:numeric);}
export function summarizeMetacognitiveCalibration(rows:CalibrationRow[]):MetacognitiveProfile{
 const sampleCount=rows.length;if(!sampleCount)return{sampleCount:0,accuracy:1,meanConfidence:1,brierScore:0,calibrationGap:0,overconfidence:0,preferDeep:false,requireVerification:false,reason:'sin muestras de calibración; se conserva el enrutamiento actual'};
 const confidences=rows.map(row=>clamp(Number(row.predicted_confidence))),outcomes=rows.map(row=>Number(row.correct)?1:0),accuracy=outcomes.reduce((a,b)=>a+b,0)/sampleCount,meanConfidence=confidences.reduce((a,b)=>a+b,0)/sampleCount,brierScore=confidences.reduce((sum,confidence,index)=>sum+(confidence-outcomes[index])**2,0)/sampleCount,calibrationGap=Math.abs(meanConfidence-accuracy),overconfidence=Math.max(0,meanConfidence-accuracy),enough=sampleCount>=METACOGNITIVE_POLICY.minSamples,preferDeep=enough&&(brierScore>METACOGNITIVE_POLICY.maxBrier||overconfidence>METACOGNITIVE_POLICY.maxOverconfidence||accuracy<METACOGNITIVE_POLICY.minAccuracyForFast),requireVerification=enough&&(calibrationGap>.1||brierScore>.18),reason=!enough?'muestras insuficientes; exploración controlada':preferDeep?`confianza mal calibrada: Brier ${brierScore.toFixed(3)}, exceso ${overconfidence.toFixed(3)}, precisión ${accuracy.toFixed(3)}`:requireVerification?`calibración moderada; exige verificación adicional (gap ${calibrationGap.toFixed(3)})`:'confianza reciente calibrada dentro de umbrales';
 return{sampleCount,accuracy,meanConfidence,brierScore,calibrationGap,overconfidence,preferDeep,requireVerification,reason};
}
export function applyMetacognitiveRouting(route:Route,profile:MetacognitiveProfile):Route{
 if(!profile.preferDeep||route.tier==='deep')return route;
 return{...route,tier:'deep',reasoning:'high',reason:`${route.reason}; escalamiento metacognitivo: ${profile.reason}`};
}
export async function loadMetacognitiveProfile(db:D1Database,userId:string,task:string):Promise<MetacognitiveProfile>{try{const result=await db.prepare(`SELECT predicted_confidence,correct,route_tier,provider,created_at FROM metacognitive_calibration_events WHERE user_id=? AND task=? AND created_at>=datetime('now',?) ORDER BY created_at DESC LIMIT ?`).bind(userId,task,`-${METACOGNITIVE_POLICY.windowDays} days`,METACOGNITIVE_POLICY.sampleLimit).all<CalibrationRow>();return summarizeMetacognitiveCalibration(result.results||[]);}catch{return summarizeMetacognitiveCalibration([]);}}
export async function recordMetacognitiveOutcome(db:D1Database,input:{userId:string;task:string;routeTier:string;provider:string;model:string;qualityScore:number;qualityAccepted:boolean;verificationOk:boolean;fallback:boolean}){try{const confidence=normalizeConfidence(input.qualityScore),correct=input.qualityAccepted&&input.verificationOk?1:0,brier=(confidence-correct)**2;await db.prepare(`INSERT INTO metacognitive_calibration_events(id,user_id,task,route_tier,provider,model,predicted_confidence,correct,verification_ok,quality_accepted,fallback,brier_score) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),input.userId,input.task,input.routeTier,input.provider,input.model,confidence,correct,+input.verificationOk,+input.qualityAccepted,+input.fallback,brier).run();return true;}catch{return false;}}
export function calibrationBenchmark(){const calibrated=summarizeMetacognitiveCalibration(Array.from({length:10},(_,i)=>({predicted_confidence:i<8?.8:.3,correct:i<8?1:0,route_tier:'fast',provider:'cloudflare'}))),overconfident=summarizeMetacognitiveCalibration(Array.from({length:10},()=>({predicted_confidence:.95,correct:0,route_tier:'fast',provider:'cloudflare'})));return{calibratedPreferDeep:calibrated.preferDeep,overconfidentPreferDeep:overconfident.preferDeep,calibratedBrier:calibrated.brierScore,overconfidentBrier:overconfident.brierScore};}