import {describe,expect,it} from 'vitest';
import {applyStrategySelection,cognitiveStrategyKey,recordStrategyOutcome,selectMetacognitiveStrategy,strategySelectionBenchmark,summarizeStrategyProfiles,type CognitiveStrategy,type StrategyOutcomeRow} from './metacognitive-strategy';

const calibration={sampleCount:10,accuracy:.9,meanConfidence:.88,brierScore:.08,calibrationGap:.02,overconfidence:0,preferDeep:false,requireVerification:false,reason:'calibrado'};
const row=(strategy:CognitiveStrategy,success:boolean,overrides:Partial<StrategyOutcomeRow>={}):StrategyOutcomeRow=>({route_tier:strategy.routeTier,requested_provider:strategy.provider,cognitive_mode:strategy.cognitiveMode,success:success?1:0,advanced_calls:strategy.provider==='cloudflare'?0:strategy.cognitiveMode==='ensemble'?3:1,cost_usd:strategy.provider==='cloudflare'?0:.02,duration_ms:1000,...overrides});
const plan={route:{model:'deep',tier:'deep' as const,reason:'test',reasoning:'high' as const,task:'general',needsWeb:false},provider:{provider:'openai' as const,reason:'test'},cognition:{mode:'ensemble' as const,reason:'test',candidateCount:2 as const,highStakes:false}};

describe('metacognitive strategy selection',()=>{
 it('resume éxito, límite inferior y costo por estrategia',()=>{const strategy={routeTier:'balanced',provider:'openai',cognitiveMode:'single'} as const,profile=summarizeStrategyProfiles([row(strategy,true),row(strategy,true),row(strategy,false)])[0];expect(profile).toMatchObject({sampleCount:3,successes:2,averageAdvancedCalls:1});expect(profile.posteriorMean).toBeCloseTo(.6,5);expect(profile.lowerBound).toBeLessThan(profile.posteriorMean);});
 it('conserva la estrategia barata solo con evidencia fuerte',()=>{const cheap={routeTier:'fast',provider:'cloudflare',cognitiveMode:'single'} as const,profiles=summarizeStrategyProfiles(Array.from({length:20},(_,index)=>row(cheap,index<19))),selection=selectMetacognitiveStrategy({...plan,profiles,risk:'low',reasoningLevel:'auto',calibration});expect(selection).toMatchObject({action:'conserve',selectedStrategy:'fast:cloudflare:single',expectedCallsSaved:3});});
 it('no degrada cuando la calibración global exige profundidad',()=>{const cheap={routeTier:'fast',provider:'cloudflare',cognitiveMode:'single'} as const,profiles=summarizeStrategyProfiles(Array.from({length:20},()=>row(cheap,true))),selection=selectMetacognitiveStrategy({...plan,profiles,risk:'low',reasoningLevel:'auto',calibration:{...calibration,preferDeep:true,reason:'sobreconfianza'}});expect(selection.action).toBe('keep');});
 it('no degrada razonamiento alto explícito',()=>{const cheap={routeTier:'fast',provider:'cloudflare',cognitiveMode:'single'} as const,profiles=summarizeStrategyProfiles(Array.from({length:20},()=>row(cheap,true))),selection=selectMetacognitiveStrategy({...plan,profiles,risk:'low',reasoningLevel:'high',calibration});expect(selection.action).toBe('keep');});
 it('no degrada tareas de riesgo medio aunque la ruta barata esté probada',()=>{const cheap={routeTier:'fast',provider:'cloudflare',cognitiveMode:'single'} as const,profiles=summarizeStrategyProfiles(Array.from({length:20},()=>row(cheap,true))),selection=selectMetacognitiveStrategy({...plan,profiles,risk:'medium',reasoningLevel:'auto',calibration});expect(selection.action).toBe('keep');});
 it('escala cuando la estrategia activa falla y existe alternativa probada',()=>{const weak={routeTier:'fast',provider:'cloudflare',cognitiveMode:'single'} as const,strong={routeTier:'deep',provider:'openai',cognitiveMode:'single'} as const,profiles=summarizeStrategyProfiles([...Array.from({length:10},(_,index)=>row(weak,index===0)),...Array.from({length:10},(_,index)=>row(strong,index<9))]),selection=selectMetacognitiveStrategy({route:{model:'fast',tier:'fast',reason:'test',reasoning:'low',task:'code',needsWeb:false},provider:{provider:'cloudflare',reason:'test'},cognition:{mode:'single',reason:'test',candidateCount:1,highStakes:false},profiles,risk:'low',reasoningLevel:'auto',calibration});expect(selection).toMatchObject({action:'escalate',selectedStrategy:'deep:openai:single'});});
 it('aplica la ruta seleccionada sin alterar la tarea',()=>{const selection={version:'1.0.0',action:'conserve',currentStrategy:'deep:openai:ensemble',selectedStrategy:'fast:cloudflare:single',sampleCount:20,successEstimate:.9,lowerBound:.8,expectedCallsSaved:3,reason:'probada'} as const,adapted=applyStrategySelection({OPENAI_MODEL:'base',OPENAI_MODEL_FAST:'fast'},plan,selection);expect(adapted.route).toMatchObject({tier:'fast',model:'fast',task:'general',needsWeb:false});expect(adapted.provider.provider).toBe('cloudflare');expect(adapted.cognition.mode).toBe('single');});
 it('registra métricas por usuario sin guardar prompts ni respuestas',async()=>{let sql='',values:unknown[]=[],runs=0;const db={prepare:(statement:string)=>{sql=statement;return{bind:(...bound:unknown[])=>{values=bound;return{run:async()=>{runs+=1;return{success:true};}};}};}} as any,strategy={routeTier:'fast',provider:'cloudflare',cognitiveMode:'single'} as const;await recordStrategyOutcome(db,{userId:'user-1',task:'general',strategy,actualProvider:'cloudflare',success:true,verificationOk:true,qualityAccepted:true,fallback:false,advancedCalls:0,costUsd:0,durationMs:25});expect(sql).toContain('metacognitive_strategy_outcomes');expect(values).toContain('user-1');expect(values).toContain(cognitiveStrategyKey(strategy));expect(runs).toBe(1);});
 it('benchmark demuestra cero llamadas avanzadas para una ruta probada',()=>{expect(strategySelectionBenchmark()).toMatchObject({action:'conserve',selectedStrategy:'fast:cloudflare:single',baselineAdvancedCalls:3,selectedAdvancedCalls:0,advancedCallsAvoided:3});});
});
