import {describe,expect,it} from 'vitest';
import {classify,conversationInput,relevantMemories,routeModel} from './openai';
import type {Bindings} from '../types';
const env={OPENAI_MODEL:'gpt-5.6-terra',OPENAI_MODEL_FAST:'gpt-5.6-luna',OPENAI_MODEL_BALANCED:'gpt-5.6-terra',OPENAI_MODEL_REASONING:'gpt-5.6-sol'} as Bindings;
describe('Héctor OS model routing benchmark',()=>{
 const cases=[['hola','fast','consulta general',false],['Explícame cómo funciona un transformador','balanced','explicación técnica',false],['Diseña e implementa una arquitectura completa en Cloudflare Workers, D1 y R2.','deep','ingeniería de software',false],['Busca noticias recientes','balanced','consulta general',true],['¿Qué es Héctor OS?','deep','autoconocimiento y productos de IA',false],['¿Qué modelo GPT-5.6 está disponible actualmente?','deep','autoconocimiento y productos de IA',true]] as const;
 it.each(cases)('routes %s',(input,tier,task,needsWeb)=>{expect(routeModel(env,input,true)).toMatchObject({tier,task,needsWeb});});
 it('usa los modelos y esfuerzos configurados',()=>{expect(routeModel(env,'hola',true)).toMatchObject({model:'gpt-5.6-luna',reasoning:'low'});expect(routeModel(env,'Explícame un transformador',true)).toMatchObject({model:'gpt-5.6-terra',reasoning:'medium'});expect(routeModel(env,'Audita e implementa una arquitectura completa',true)).toMatchObject({model:'gpt-5.6-sol',reasoning:'xhigh'});});
 it('respeta web desactivada',()=>{expect(routeModel(env,'¿Qué modelo GPT-5.6 está disponible actualmente?',false).needsWeb).toBe(false);});
});
describe('classification',()=>{it.each([['Corrige este workflow','ingeniería de software'],['¿Qué hace Codex?','autoconocimiento y productos de IA'],['Tengo dolor después de una cirugía','salud y análisis de riesgo'],['Calcula mi presupuesto','finanzas personales'],['Ayúdame a decidir un plan','planificación y toma de decisiones'],['Explica cómo emerge la química','explicación técnica'],['¿Qué opinas?','consulta general']] as const)('%s',(input,expected)=>expect(classify(input)).toBe(expected));});
describe('memory retrieval',()=>{const memories=['Saldo BBVA registrado: 4,396.50 MXN.','El usuario prefiere explicaciones técnicas como ingeniero.','La lesión fue en el dedo índice.','Héctor OS usa Cloudflare Workers, D1 y R2.'];it('prioriza coincidencias relevantes',()=>{expect(relevantMemories('saldo 4,396.50',memories)[0]).toContain('4,396.50');expect(relevantMemories('arquitectura Cloudflare',memories)[0]).toContain('Cloudflare');});it('excluye recuerdos no relacionados',()=>expect(relevantMemories('capital de Japón',memories)).toEqual([]));it('limita a ocho',()=>expect(relevantMemories('arquitectura proyecto',Array.from({length:20},(_,i)=>`arquitectura proyecto ${i}`))).toHaveLength(8));});
describe('conversation assembly',()=>{it('no duplica el turno actual',()=>{const input='Continúa';expect(conversationInput([{role:'user',content:input}],input)).toEqual([{role:'user',content:input}]);});it('limita historial y agrega el nuevo turno',()=>{const history=Array.from({length:20},(_,i)=>({role:i%2?'assistant' as const:'user' as const,content:`Turno ${i}`})),result=conversationInput(history,'Nuevo');expect(result).toHaveLength(17);expect(result[0].content).toBe('Turno 4');expect(result.at(-1)?.content).toBe('Nuevo');});});
