import type {Bindings} from '../types';
import {applyBudgetRouting,applyFeedbackRouting,routeModel,type ResponseOptions} from './openai';
import {executePlannedContextual,estimatePlannedCost} from './planned-response';
import {loadFeedbackRoutingProfile} from './feedback-routing';
import {loadCognitiveBudget,projectCognitiveCost} from './cognitive-budget';
import {loadCloudflareHealth} from './provider-quality';
import {chooseProvider} from './providers';
import {chooseDeliberation} from './deliberation';
import {createExecutionPlan,verifyExecutionPlan,type ExecutionPlan} from './execution-plan';
import {classifyReuseRisk,runWithRuntimeReuse,type RuntimeReuseCandidate} from './runtime-reuse';
import {loadHybridRuntimeCandidates,readSemanticCache,stablePromptHash,writeSemanticCache} from './hybrid-memory';
import {createCallGovernor,decideCallBudget,governExecutionPlan,type CallGovernorMetrics,type ReuseDisposition} from './call-governor';
import {recordCallGovernorEvent} from './call-governor-ledger';

export type PlannedWorkInput={userId:string;prompt:string;allowWeb:boolean;reasoningLevel:'auto'|'high';context?:string;authorizedHighRisk?:boolean};
export function workResponseOptions(input:Pick<PlannedWorkInput,'userId'|'reasoningLevel'>):ResponseOptions{return{reasoning:input.reasoningLevel,deliberation:input.reasoningLevel==='high'?'force':'auto',userId:input.userId};}
function forecastPasses(env:Bindings,input:string,route:ReturnType<typeof routeModel>,options:ResponseOptions):1|3{return chooseDeliberation(input,route.tier,options,env.HECTOR_DELIBERATION_ENABLED!=='false').mode==='ensemble'?3:1;}
export async function prepareWorkExecutionPlan(env:Bindings,input:PlannedWorkInput):Promise<{plan:ExecutionPlan;feedback:Awaited<ReturnType<typeof loadFeedbackRoutingProfile>>;budgetDecision:unknown}>{
 const options=workResponseOptions(input),base=routeModel(env,input.prompt,input.allowWeb),forced=options.reasoning==='high'?{...base,model:env.OPENAI_MODEL_REASONING||base.model,tier:'deep' as const,reasoning:'high' as const,reason:'trabajo persistente con razonamiento alto solicitado'}:base;
 const feedback=await loadFeedbackRoutingProfile(env.DB,input.userId,forced.task);let route=applyFeedbackRouting(env,forced,feedback),budgetDecision:unknown=null,budgetSummary='sin presupuesto configurado';const budget=await loadCognitiveBudget(env.DB,input.userId);
 if(budget){const initial=projectCognitiveCost(budget,route.model,route.tier,input.prompt.length,(input.context||'').length,forecastPasses(env,input.prompt,route,options));const applied=applyBudgetRouting(env,route,input.prompt,options,budget,initial);route=applied.route;budgetDecision=applied.decision;budgetSummary=applied.decision.reason;}
 const enabled=env.CLOUDFLARE_AI_ENABLED!=='false',health=route.tier==='fast'&&enabled?await loadCloudflareHealth(env.DB):undefined,provider=chooseProvider(input.prompt,route.tier,route.needsWeb,enabled,health,feedback),cognition=chooseDeliberation(input.prompt,route.tier,options,env.HECTOR_DELIBERATION_ENABLED!=='false'),allowedModels=[route.model];
 if(provider.provider==='cloudflare')allowedModels.push('hector-rules-v1',env.CLOUDFLARE_MODEL_UTILITY||'@cf/ibm-granite/granite-4.0-h-micro',env.CLOUDFLARE_MODEL_FAST||'@cf/meta/llama-3.2-3b-instruct');if(cognition.mode==='ensemble')allowedModels.push(env.OPENAI_MODEL_CRITIC||route.model);
 const plan=await createExecutionPlan({task:route.task,route:{model:route.model,tier:route.tier,reasoning:route.reasoning,needsWeb:route.needsWeb},provider:{requested:provider.provider,reason:provider.reason},cognition:{mode:cognition.mode,passes:cognition.mode==='ensemble'?3:1,reason:cognition.reason},allowedModels,policySummary:`Trabajo persistente. Feedback: ${feedback.reason}. Presupuesto: ${budgetSummary}.`});return{plan,feedback,budgetDecision};
}
function deterministicWorkOutput(output:string,candidate:RuntimeReuseCandidate,prepared:Awaited<ReturnType<typeof prepareWorkExecutionPlan>>){return{id:`reuse:${candidate.id}`,text:output,usage:{input_tokens:0,output_tokens:0},searchedWeb:false,model:'hector-runtime-reuse',provider:'cloudflare' as const,requestedProvider:'cloudflare' as const,providerReason:'Procedimiento determinista local reutilizado',fallback:false,qualityScore:1,qualityAccepted:true,cognitiveMode:'single' as const,deliberationPasses:0,deliberationReason:'No fue necesaria inferencia del modelo.',modelTier:prepared.plan.route.tier,modelReason:prepared.plan.policySummary,task:prepared.plan.task,feedbackAdaptation:{sampleCount:prepared.feedback.sampleCount,preferDeep:prepared.feedback.preferDeep,avoidCloudflare:prepared.feedback.avoidCloudflare,guidanceApplied:prepared.feedback.guidance.length,reason:prepared.feedback.reason},budgetDecision:prepared.budgetDecision};}
function zeroCallMetrics(plan:ExecutionPlan,prompt:string,reason?:string):CallGovernorMetrics{const decision=decideCallBudget({prompt,reuse:'deterministic',requestedPasses:plan.cognition.passes,reasoningLevel:'high'});return{advancedCalls:0,deduplicatedCalls:0,blockedCalls:0,requestedPasses:decision.requestedPasses,executedPasses:0,estimatedAdvancedCallsSaved:decision.estimatedAdvancedCallsSaved,justifications:[reason||decision.justification]};}
export async function executePlannedWork(env:Bindings,input:PlannedWorkInput){
 const risk=classifyReuseRisk(input.prompt),cacheNamespace=`planned-work:v1:${input.allowWeb?'web':'offline'}:${input.reasoningLevel}`,cacheable=risk==='low'&&!input.allowWeb;
 if(cacheable){const cached=await readSemanticCache<any>(env.DB,input.userId,cacheNamespace,input.prompt);if(cached){const prior=cached?.callGovernor as CallGovernorMetrics|undefined,requested=Math.max(1,Number(prior?.requestedPasses||1));await recordCallGovernorEvent(env.DB,{userId:input.userId,requestKey:cached?.plan?.hash||stablePromptHash(input.prompt),metrics:{advancedCalls:0,deduplicatedCalls:0,semanticCacheHits:1,blockedCalls:0,requestedPasses:requested,executedPasses:0,estimatedAdvancedCallsSaved:requested,justifications:['Respuesta recuperada de la caché semántica verificada.']}});return{...cached,usage:{...(cached.usage||{}),input:0,cached:0,cacheWrite:0,output:0,costUsd:0,longContext:false},semanticCache:{status:'hit',advancedCallsSaved:requested}};}}
 const prepared=await prepareWorkExecutionPlan(env,input),candidates=await loadHybridRuntimeCandidates(env.DB,input.userId,input.prompt),baseContext=input.context||'Trabajo persistente ejecutado fuera del chat.';let activePlan=prepared.plan,governorMetrics:CallGovernorMetrics|undefined;
 const executeModel=async(reuseContext:string,disposition:ReuseDisposition)=>{const governed=await governExecutionPlan(prepared.plan,{prompt:input.prompt,reuse:disposition,reasoningLevel:input.reasoningLevel});activePlan=governed.plan;const governor=createCallGovernor(governed.decision),context=reuseContext?`${baseContext}\n\n${reuseContext}`:baseContext,value=await governor.advanced({key:`${input.userId}:${activePlan.hash}:${input.prompt}:${context}`,justification:`Ejecutar ${activePlan.route.model} para la parte no resuelta de ${activePlan.task}.`,execute:()=>executePlannedContextual(env,input.prompt,[],context,activePlan,{feedback:prepared.feedback,budgetDecision:prepared.budgetDecision})});governorMetrics=governor.metrics;return value;};
 const executed=candidates.length?await runWithRuntimeReuse({prompt:input.prompt,candidates,authorizedHighRisk:input.authorizedHighRisk,modelCostUsd:.02,model:reuseContext=>executeModel(reuseContext,reuseContext?'assist':'escalate'),deterministic:(output,candidate)=>deterministicWorkOutput(output,candidate,prepared)}):{value:await executeModel('','escalate'),decision:{kind:'escalate' as const,reason:'No había experiencias reutilizables.',risk:'low' as const,candidate:null,reusedFraction:0},modelCalls:1};
 const out=executed.value,localRules=out.model==='hector-rules-v1';if(executed.decision.kind==='deterministic')governorMetrics=zeroCallMetrics(prepared.plan,input.prompt);else if(localRules)governorMetrics=zeroCallMetrics(activePlan,input.prompt,'Operación resuelta por hector-rules-v1 sin inferencia externa.');
 const verification=verifyExecutionPlan(activePlan,{model:out.model,tier:out.modelTier,provider:out.provider,requestedProvider:out.requestedProvider,cognitiveMode:out.cognitiveMode,deliberationPasses:out.deliberationPasses,fallback:out.fallback});let usage=estimatePlannedCost(out.usage,out.model);if(out.searchedWeb)usage.costUsd+=.01;
 const sharedInference=Boolean(governorMetrics&&governorMetrics.advancedCalls===0&&governorMetrics.deduplicatedCalls>0);if(sharedInference||localRules)usage={...usage,input:0,cached:0,cacheWrite:0,output:0,costUsd:0,longContext:false};
 const result={out,plan:activePlan,verification,usage,reuse:{kind:executed.decision.kind,candidateId:executed.decision.kind==='assist'||executed.decision.kind==='deterministic'?executed.decision.candidate.id:null,reusedFraction:executed.decision.reusedFraction,modelCalls:localRules?0:executed.modelCalls,reason:localRules?'Operación resuelta por reglas locales; cero llamadas de modelo.':executed.decision.reason},callGovernor:governorMetrics,semanticCache:{status:'miss' as const,advancedCallsSaved:0}};
 if(governorMetrics)await recordCallGovernorEvent(env.DB,{userId:input.userId,requestKey:activePlan.hash,metrics:{...governorMetrics,semanticCacheHits:0}});
 if(cacheable&&verification.ok&&!out.searchedWeb)await writeSemanticCache(env.DB,{userId:input.userId,namespace:cacheNamespace,prompt:input.prompt,response:result,confidence:out.qualityAccepted?.95:.75,ttlSeconds:21600});
 return result;
}
