import {afterEach,describe,expect,it,vi} from 'vitest';
import {createExecutionPlan} from './execution-plan';
import {estimatePlannedCost,executePlannedContextual} from './planned-response';
afterEach(()=>vi.restoreAllMocks());
const feedback={sampleCount:0,negativeRate:0,nonDeepSampleCount:0,nonDeepNegativeRate:0,cloudflareSampleCount:0,cloudflareNegativeRate:0,preferDeep:false,avoidCloudflare:false,guidance:[],reason:'neutral'};
describe('planned response authority',()=>{
 it('mantiene el plan abierto inmutable',async()=>{const plan=await createExecutionPlan({task:'consulta',route:{model:'Qwen/Qwen3-4B-Instruct-2507',tier:'balanced',reasoning:'medium',needsWeb:false},provider:{requested:'huggingface',reason:'Qwen'},cognition:{mode:'single',passes:1,reason:'una inferencia'},allowedModels:['Qwen/Qwen3-4B-Instruct-2507'],policySummary:'Chat abierto.'});expect(plan.provider.requested).toBe('huggingface');expect(Object.isFrozen(plan)).toBe(true);});
 it('ejecuta Qwen sin OpenAI',async()=>{const plan=await createExecutionPlan({task:'consulta',route:{model:'Qwen/Qwen3-4B-Instruct-2507',tier:'balanced',reasoning:'medium',needsWeb:false},provider:{requested:'huggingface',reason:'Qwen'},cognition:{mode:'single',passes:1,reason:'una'},allowedModels:['Qwen/Qwen3-4B-Instruct-2507'],policySummary:'Qwen.'});const run=vi.fn(async()=>({success:true})),bind=vi.fn(()=>({run})),prepare=vi.fn(()=>({bind}));vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({id:'hf',choices:[{message:{content:'Respuesta Qwen.'}}]}),{status:200,headers:{'Content-Type':'application/json'}})));const out=await executePlannedContextual({HUGGINGFACE_TOKEN:'test',DB:{prepare} as any} as any,'hola',[],'contexto',plan,{feedback,budgetDecision:null});expect(out).toMatchObject({provider:'huggingface',model:'Qwen/Qwen3-4B-Instruct-2507',fallback:false});});
 it('cae de Qwen a Workers AI, no a OpenAI',async()=>{const plan=await createExecutionPlan({task:'consulta',route:{model:'Qwen/Qwen3-4B-Instruct-2507',tier:'fast',reasoning:'low',needsWeb:false},provider:{requested:'huggingface',reason:'Qwen'},cognition:{mode:'single',passes:1,reason:'una'},allowedModels:['Qwen/Qwen3-4B-Instruct-2507'],policySummary:'Qwen.'});const run=vi.fn(async()=>({response:'Respuesta abierta.'})),bind=vi.fn(()=>({run:vi.fn(async()=>({success:true}))})),prepare=vi.fn(()=>({bind}));const out=await executePlannedContextual({AI:{run} as any,DB:{prepare} as any} as any,'hola',[],'contexto',plan,{feedback,budgetDecision:null});expect(out.provider).toBe('cloudflare');expect(out.fallback).toBe(true);expect(out.providerReason).toMatch(/Qwen no disponible/);});
 it('conserva cálculo de costo',()=>{const cost=estimatePlannedCost({input_tokens:1000,output_tokens:500},'@cf/meta/llama-3.2-3b-instruct');expect(cost.input).toBe(1000);expect(cost.output).toBe(500);});
});
