import {describe,expect,it} from 'vitest';
import {createExecutionPlan} from './execution-plan';
import {classifyDriftCause,latestActions,normalizeDriftIncident,recoveryPrompt,restoreExecutionPlan,retryLocked} from './plan-drift-incidents';

describe('plan drift incidents',()=>{
 it('clasifica causas sin confundir proveedor con router',()=>{expect(classifyDriftCause(['proveedor previsto cloudflare, observado openai'])).toBe('provider');expect(classifyDriftCause(['tier previsto balanced, observado deep'])).toBe('router');expect(classifyDriftCause(['pasadas previstas 1, observadas 3'])).toBe('cognition');});
 it('construye un prompt de recuperación acotado al plan',()=>{const prompt=recoveryPrompt({task:'consulta general',planHash:'abcdef1234567890',cause:'router',differences:['tier distinto']});expect(prompt).toContain('abcdef123456');expect(prompt).toContain('No cambies modelo');});
 it('normaliza filas válidas y detecta si pueden reintentarse',()=>{const row={id:'i1',model:'gpt-x',estimated_cost_usd:.1,created_at:'2026-07-21',metadata_json:JSON.stringify({planHash:'abcdef1234567890',planVersion:'1.0.0',task:'consulta general',conversationId:'c1',userMessageId:'m1',executionPlan:{task:'x'},verification:{summary:'bloqueada',differences:['modelo no autorizado x']}})};const incident=normalizeDriftIncident(row,new Map([['i1',{status:'acknowledged',createdAt:'2026-07-21T10:00:00Z'}]]));expect(incident).toMatchObject({id:'i1',status:'acknowledged',cause:'router',retryAvailable:true,lastActionAt:'2026-07-21T10:00:00Z'});expect(normalizeDriftIncident({...row,metadata_json:'{'},new Map())).toBeNull();});
 it('conserva solo la acción más reciente por incidente',()=>{const actions=latestActions([{created_at:'2026-07-21T12:00:00Z',metadata_json:JSON.stringify({incidentId:'i1',action:'recovery-requested'})},{created_at:'2026-07-21T11:00:00Z',metadata_json:JSON.stringify({incidentId:'i1',action:'acknowledged'})}]);expect(actions.get('i1')).toEqual({status:'recovery-requested',createdAt:'2026-07-21T12:00:00Z'});});
 it('restaura únicamente planes cuyo hash coincide',async()=>{const plan=await createExecutionPlan({task:'consulta general',route:{model:'gpt-x',tier:'balanced',reasoning:'medium',needsWeb:false},provider:{requested:'openai',reason:'prueba'},cognition:{mode:'single',passes:1,reason:'prueba'},allowedModels:['gpt-x'],policySummary:'prueba'});expect((await restoreExecutionPlan(plan,plan.hash))?.hash).toBe(plan.hash);expect(await restoreExecutionPlan({...plan,policySummary:'alterado'},plan.hash)).toBeNull();});
 it('bloquea duplicados en curso y recuperados',()=>{expect(retryLocked({status:'retrying',createdAt:'2026-07-21T12:00:00Z'},Date.parse('2026-07-21T12:04:00Z'))).toBe(true);expect(retryLocked({status:'retrying',createdAt:'2026-07-21T12:00:00Z'},Date.parse('2026-07-21T12:06:00Z'))).toBe(false);expect(retryLocked({status:'recovered',createdAt:'2026-07-21T12:00:00Z'})).toBe(true);});
});
