import {afterEach,describe,expect,it,vi} from 'vitest';
import {callCloudflare,callHuggingFaceQwen,chooseProvider,CHAT_RUNTIME_POLICY,HECTOR_BASE_RUNTIME,HECTOR_QWEN_RUNTIME} from './providers';
import type {ProviderHealth} from './provider-quality';
import type {FeedbackRoutingProfile} from './feedback-routing';
const health=(overrides:Partial<ProviderHealth>={}):ProviderHealth=>({sampleCount:12,acceptedRate:.95,fallbackRate:.05,averageLatencyMs:400,healthy:true,circuitOpen:false,reason:'calidad reciente dentro de umbrales',mostRecentAt:'2026-07-21 15:00:00',...overrides});
const feedback=(overrides:Partial<FeedbackRoutingProfile>={}):FeedbackRoutingProfile=>({sampleCount:8,negativeRate:.2,nonDeepSampleCount:6,nonDeepNegativeRate:.2,cloudflareSampleCount:4,cloudflareNegativeRate:.2,preferDeep:false,avoidCloudflare:false,guidance:[],reason:'aún no existe evidencia suficiente para cambiar el enrutamiento',...overrides});
afterEach(()=>vi.restoreAllMocks());
describe('chooseProvider',()=>{
 it('prefiere Héctor Qwen para conversación cuando está habilitado',()=>{const decision=chooseProvider('hola','fast',false,true,health(),feedback());expect(decision.provider).toBe('huggingface');expect(decision.reason).toMatch(/Qwen/);expect(CHAT_RUNTIME_POLICY.openAIAllowed).toBe(false);});
 it('mantiene web, complejidad y datos sensibles dentro de modelos abiertos',()=>{for(const decision of [chooseProvider('busca noticias de hoy','fast',true,true,health()),chooseProvider('diseña la arquitectura completa','deep',false,true,health()),chooseProvider('revisa mi saldo bancario','fast',false,true,health())])expect(decision.provider).not.toBe('openai');});
 it('permite forzar Workers AI de forma explícita',()=>{expect(chooseProvider('Héctor Base: explícame una arquitectura','deep',false,true,health()).provider).toBe('cloudflare');});
 it('usa Workers AI cuando Qwen se declara no configurado',()=>{expect(chooseProvider('hola','fast',false,true,health(),feedback(),false).provider).toBe('cloudflare');});
 it('resuelve utilidades deterministas aunque los modelos estén apagados',()=>{const decision=chooseProvider('Clasifica: corrige un error de TypeScript','balanced',false,false);expect(decision.provider).toBe('cloudflare');expect(decision.reason).toMatch(/reglas locales/);});
 it('no habilita OpenAI por degradación o feedback',()=>{expect(chooseProvider('hola','fast',false,true,health({circuitOpen:true,reason:'circuito abierto'}),feedback(),false).provider).toBe('cloudflare');expect(chooseProvider('hola','fast',false,true,health(),feedback({avoidCloudflare:true,reason:'baja utilidad'}),false).provider).toBe('cloudflare');});
 it('ejecuta clasificación local con cero tokens y registra Héctor Base',async()=>{const out=await callCloudflare({} as any,'instrucciones','Clasifica: crea una API en TypeScript');expect(out).toMatchObject({model:'hector-rules-v1',usage:{input_tokens:0,output_tokens:0},capability:'classify',runtime:HECTOR_BASE_RUNTIME});});
 it('falla visiblemente sin Workers AI, sin fallback externo',async()=>{await expect(callCloudflare({CLOUDFLARE_AI_ENABLED:'true'} as any,'instrucciones','hola')).rejects.toThrow(/no enviará el mensaje a OpenAI/);});
 it('rechaza Qwen cuando falta el secreto',async()=>{await expect(callHuggingFaceQwen({HECTOR_QWEN_ENABLED:'true'} as any,'instrucciones','hola')).rejects.toThrow(/HUGGINGFACE_TOKEN/);});
 it('conserva historial y registra el runtime Qwen',async()=>{vi.stubGlobal('fetch',vi.fn(async(_url:string,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));expect(body.messages.at(-1)).toEqual({role:'user',content:'hola'});return new Response(JSON.stringify({id:'hf-test',choices:[{message:{content:'Hola'}}],usage:{prompt_tokens:12,completion_tokens:9}}),{status:200,headers:{'Content-Type':'application/json'}});}));const out=await callHuggingFaceQwen({HUGGINGFACE_TOKEN:'test'} as any,'instrucciones',[{role:'user',content:'Héctor Qwen: hola'}]);expect(out).toMatchObject({id:'hf-test',runtime:HECTOR_QWEN_RUNTIME});});
});
