import {describe,expect,it} from 'vitest';
import {callCloudflare,chooseProvider,CHAT_RUNTIME_POLICY,HECTOR_BASE_RUNTIME} from './providers';
import type {ProviderHealth} from './provider-quality';
import type {FeedbackRoutingProfile} from './feedback-routing';
const health=(overrides:Partial<ProviderHealth>={}):ProviderHealth=>({sampleCount:12,acceptedRate:.95,fallbackRate:.05,averageLatencyMs:400,healthy:true,circuitOpen:false,reason:'calidad reciente dentro de umbrales',mostRecentAt:'2026-07-21 15:00:00',...overrides});
const feedback=(overrides:Partial<FeedbackRoutingProfile>={}):FeedbackRoutingProfile=>({sampleCount:8,negativeRate:.2,nonDeepSampleCount:6,nonDeepNegativeRate:.2,cloudflareSampleCount:4,cloudflareNegativeRate:.2,preferDeep:false,avoidCloudflare:false,guidance:[],reason:'aún no existe evidencia suficiente para cambiar el enrutamiento',...overrides});
describe('chooseProvider',()=>{
 it('autoriza únicamente Héctor Base para conversación ordinaria',()=>{const decision=chooseProvider('hola, resume esto','fast',false,true,health(),feedback());expect(decision.provider).toBe('cloudflare');expect(decision.reason).toMatch(/Héctor Base/);expect(CHAT_RUNTIME_POLICY.openAIAllowed).toBe(false);});
 it('mantiene fuera de OpenAI las tareas con web, complejas y sensibles',()=>{expect(chooseProvider('busca noticias de hoy','fast',true,true,health()).provider).toBe('cloudflare');expect(chooseProvider('diseña la arquitectura completa','deep',false,true,health()).provider).toBe('cloudflare');expect(chooseProvider('revisa mi saldo bancario','fast',false,true,health()).provider).toBe('cloudflare');});
 it('no habilita OpenAI aunque Workers AI esté apagado o degradado',()=>{expect(chooseProvider('hola','fast',false,false).provider).toBe('cloudflare');expect(chooseProvider('hola','fast',false,true,health({healthy:false,circuitOpen:true,reason:'circuito abierto'})).provider).toBe('cloudflare');expect(chooseProvider('hola','fast',false,true,health(),feedback({avoidCloudflare:true,reason:'baja utilidad'})).provider).toBe('cloudflare');});
 it('permite pedir Héctor Base explícitamente',()=>{expect(chooseProvider('Héctor Base: explícame una arquitectura','deep',false,true,health()).provider).toBe('cloudflare');});
 it('resuelve utilidades deterministas aunque Workers AI esté apagado',()=>{const decision=chooseProvider('Clasifica: corrige un error de TypeScript','balanced',false,false);expect(decision.provider).toBe('cloudflare');expect(decision.reason).toMatch(/reglas locales/);});
 it('ejecuta clasificación local con cero tokens y registra Héctor Base',async()=>{const out=await callCloudflare({} as any,'instrucciones','Clasifica: crea una API en TypeScript');expect(out).toMatchObject({model:'hector-rules-v1',usage:{input_tokens:0,output_tokens:0},capability:'classify',runtime:HECTOR_BASE_RUNTIME});expect(out.text).toContain('ingeniería de software');});
 it('falla de forma visible sin binding AI en vez de usar OpenAI',async()=>{await expect(callCloudflare({CLOUDFLARE_AI_ENABLED:'true'} as any,'instrucciones','Hola, explícame algo')).rejects.toThrow(/no enviará el mensaje a OpenAI/);});
});
