import type {Bindings} from '../types';

export const QWEN_397_OPERATIONAL={runtimeId:'hector-qwen397',repository:'Qwen/Qwen3.5-397B-A17B',label:'Héctor Qwen 397B',role:'operational-multimodal-moe',totalParameters:'397B',activeParameters:'17B',contextLength:262144,extendedContextLength:1010000,multimodal:true,thinking:true,trainable:true,license:'Apache-2.0',customWeights:false} as const;
export function hasQwen397Endpoint(env:Bindings){return env.QWEN_397B_ENABLED!=='false'&&Boolean(env.QWEN_397B_BASE_URL?.trim())&&Boolean(env.QWEN_397B_TOKEN?.trim())}
export function qwen397Status(env:Bindings){const endpointConfigured=hasQwen397Endpoint(env);return{...QWEN_397_OPERATIONAL,model:env.QWEN_397B_MODEL?.trim()||QWEN_397_OPERATIONAL.repository,label:env.QWEN_397B_LABEL?.trim()||QWEN_397_OPERATIONAL.label,enabled:env.QWEN_397B_ENABLED!=='false',endpointConfigured,mode:!endpointConfigured?'pending-endpoint':'endpoint',reason:endpointConfigured?'Qwen3.5-397B-A17B está conectado mediante un endpoint OpenAI-compatible.':'Qwen3.5-397B-A17B está integrado como cerebro principal; falta configurar endpoint y secreto.'} as const}
function chatEndpoint(baseUrl:string){const normalized=baseUrl.replace(/\/$/,'');if(normalized.endsWith('/chat/completions'))return normalized;if(normalized.endsWith('/v1'))return`${normalized}/chat/completions`;return`${normalized}/v1/chat/completions`}
type QwenContent=string|Array<{type:'text';text:string}|{type:'image_url';image_url:{url:string}}>;
type QwenMessage={role:'system'|'user'|'assistant';content:QwenContent};
type QwenChatResponse={id?:string;choices?:Array<{message?:{content?:string;reasoning_content?:string}}>;usage?:{prompt_tokens?:number;completion_tokens?:number};error?:string|{message?:string}};
async function requestQwen397(env:Bindings,messages:QwenMessage[],maxTokens:number){if(env.QWEN_397B_ENABLED==='false')throw new Error('Qwen 397B está desactivado');if(!hasQwen397Endpoint(env))throw new Error('Qwen 397B está integrado, pero falta conectar su endpoint');const configured=Number(env.QWEN_397B_TIMEOUT_MS),timeoutMs=Number.isFinite(configured)&&configured>=1000?Math.min(240_000,configured):180_000,controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs),model=env.QWEN_397B_MODEL?.trim()||QWEN_397_OPERATIONAL.repository;try{const response=await fetch(chatEndpoint(env.QWEN_397B_BASE_URL!),{method:'POST',headers:{Authorization:`Bearer ${env.QWEN_397B_TOKEN!.trim()}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages,max_tokens:maxTokens,temperature:.6,top_p:.95,stream:false}),signal:controller.signal});const data=await response.json() as QwenChatResponse,error=typeof data.error==='string'?data.error:data.error?.message;if(!response.ok)throw new Error(error||`El endpoint de Qwen respondió ${response.status}`);const text=data.choices?.[0]?.message?.content||'';if(!text.trim())throw new Error('Qwen 397B devolvió una respuesta vacía');return{text,reasoningContent:data.choices?.[0]?.message?.reasoning_content,id:data.id||`qwen397-${crypto.randomUUID()}`,model,usage:{input_tokens:data.usage?.prompt_tokens,output_tokens:data.usage?.completion_tokens},runtime:QWEN_397_OPERATIONAL}}catch(error){if(error instanceof DOMException&&error.name==='AbortError')throw new Error('Qwen 397B excedió el tiempo permitido');throw error}finally{clearTimeout(timer)}}
export function callQwen397(env:Bindings,instructions:string,messages:Array<{role:'user'|'assistant';content:string}>){return requestQwen397(env,[{role:'system',content:instructions},...messages],4096)}
export function callQwen397Vision(env:Bindings,prompt:string,dataUrl:string){const system='Eres el cerebro visual principal de Hector ASI. Analiza la imagen con precisión, distingue observaciones de inferencias y responde en español salvo petición contraria.';return requestQwen397(env,[{role:'system',content:system},{role:'user',content:[{type:'text',text:prompt},{type:'image_url',image_url:{url:dataUrl}}]}],2048)}
