import {describe,expect,it} from 'vitest';
import {cleanWorkModeOutput,deriveWorkTitle,isPersistentWorkPrompt,nextWorkModeDelayMinutes,parseWorkModeOutcome,unwrapWorkObjective,workModeExecutionPrompt,wrapWorkObjective} from './work-mode';

describe('work mode',()=>{
 it('guarda el objetivo sin exigir configuración técnica',()=>{const stored=wrapWorkObjective('Construye y valida la aplicación completa.');expect(isPersistentWorkPrompt(stored)).toBe(true);expect(unwrapWorkObjective(stored)).toBe('Construye y valida la aplicación completa.');expect(deriveWorkTitle('Construye y valida la aplicación completa. Después despliega.')).toBe('Construye y valida la aplicación completa');});
 it('ordena continuar sin preguntas innecesarias y conserva el checkpoint',()=>{const prompt=workModeExecutionPrompt(wrapWorkObjective('Corrige la app.'),'Se verificó autenticación.\nWORK_STATE: continue\nWORK_WAIT_MINUTES: 0',3);expect(prompt).toContain('No hagas preguntas innecesarias');expect(prompt).toContain('Se verificó autenticación.');expect(prompt).not.toContain('WORK_STATE: continue\nWORK_WAIT_MINUTES: 0\n\nREGLAS');expect(prompt).toContain('completed|continue|waiting');});
 it('interpreta finalización, continuación y espera explícitas',()=>{expect(parseWorkModeOutcome('Listo\nWORK_STATE: completed\nWORK_WAIT_MINUTES: 0').state).toBe('completed');expect(parseWorkModeOutcome('Falta validar\nWORK_STATE: continue\nWORK_WAIT_MINUTES: 0').state).toBe('continue');expect(parseWorkModeOutcome('Esperando CI\nWORK_STATE: waiting\nWORK_WAIT_MINUTES: 90')).toEqual({state:'waiting',waitMinutes:60,explicit:true});});
 it('usa heurística conservadora cuando falta el contrato',()=>{expect(parseWorkModeOutcome('Existe un error pendiente; intentaré otra estrategia.').state).toBe('continue');expect(parseWorkModeOutcome('La operación está en curso y debo quedar en espera.')).toMatchObject({state:'waiting',waitMinutes:10});});
 it('aplica espera progresiva sin detener definitivamente el trabajo',()=>{expect(nextWorkModeDelayMinutes({state:'continue',waitMinutes:0,explicit:true},1)).toBe(2);expect(nextWorkModeDelayMinutes({state:'continue',waitMinutes:0,explicit:true},13)).toBe(15);expect(nextWorkModeDelayMinutes({state:'waiting',waitMinutes:7,explicit:true},2)).toBe(7);});
 it('oculta el contrato interno en la interfaz',()=>{expect(cleanWorkModeOutput('Avance visible\nWORK_STATE: continue\nWORK_WAIT_MINUTES: 0')).toBe('Avance visible');});
});
