PRAGMA foreign_keys = ON;

DROP INDEX IF EXISTS idx_coordination_claim_active_scope;
CREATE INDEX IF NOT EXISTS idx_coordination_claim_scope_active ON coordination_claims(user_id,scope,status,lease_expires_at);

INSERT OR REPLACE INTO system_context(context_key,category,content,priority,active,updated_at) VALUES
('pwa_canonical_registry','project','CURRENT SURFACE MAP: Héctor OS at / is the general owner UI; Héctor Agent at /agent/ owns autonomous goals/jobs/approvals; Pendientes at /turno-rx/ owns the clinical workflow. Héctor Bridge and Context Hub are shared capabilities currently attached to Héctor OS. This map is advisory shared state, not a permission gate. Source of truth: config/pwa-registry.json.',5,1,CURRENT_TIMESTAMP),
('pwa_creation_governance','rules','INTELLIGENT SURFACE COORDINATION: Before creating or splitting a surface, inspect current main, open PRs, Context Hub, config/pwa-registry.json and GitHub issue #958. Prefer reuse when it is simpler, but do not block a better architecture. If a new PWA/surface has a concrete advantage and the requested work authorizes the needed code change, it may be created; explain the reason, avoid service-worker/cache collisions and update shared state.',5,1,CURRENT_TIMESTAMP),
('cross_chat_sync_protocol','rules','CROSS-CHAT SYNC PROTOCOL V2: sessions bootstrap shared context before substantial work, announce scopes with advisory claims, compare overlapping work, and commit structured handoffs after meaningful work. Claims are not locks and must never block another session. Multiple sessions may work on the same scope when useful; they should reuse, integrate, replace or deliberately diverge based on evidence. Durable D1/R2/GitHub state is the shared source of truth, not any single transcript.',5,1,CURRENT_TIMESTAMP),
('cross_agent_coordination','rules','CROSS-CHAT/AGENT COORDINATION: Treat Context Hub, Context Sync, current GitHub state and GitHub issue #958 as shared durable context. Before meaningful work, hydrate relevant prior decisions and active work. After meaningful work, publish a compact handoff with objective, evidence, changes, decision and next step. Shared context improves judgment and continuity; it is not an approval gate.',5,1,CURRENT_TIMESTAMP),
('shared_context_operating_model','project','SHARED CONTEXT MODEL: Complete history remains durable in storage. Each turn reconstructs the useful working set from the current conversation, semantic memories, summaries and relevant signals from other conversations, active Context Hub records, structured cross-chat commits, current jobs and exact GitHub artifacts when needed. Expand on demand instead of discarding history or stuffing every transcript token into every prompt.',5,1,CURRENT_TIMESTAMP);
