export const PRODUCT_KNOWLEDGE_VERSION='1.4.0';
export const PRODUCT_KNOWLEDGE_VERIFIED_AT='2026-07-22';
export type KnowledgeFact={id:string;subject:'hector-os'|'openai'|'work'|'codex'|'gpt-5.6'|'owner';statement:string;stability:'runtime'|'stable'|'time-sensitive';source:string};
export const PRODUCT_FACTS:KnowledgeFact[]=[
 {id:'hector-system',subject:'hector-os',statement:'Héctor OS es el sistema compuesto por PWA, Cloudflare Worker, D1, R2, memoria, routing, deliberación abierta, herramientas, tareas, pruebas y workflows; no es idéntico a un único modelo.',stability:'runtime',source:'repositorio y bindings desplegables'},
 {id:'hector-base-operational',subject:'hector-os',statement:'Héctor Base es el único runtime autorizado para el chat interactivo. Usa modelos abiertos ya entrenados en Cloudflare Workers AI: Llama 3.2 3B Instruct para conversación, Granite 4.0 H Micro para utilidades y reglas locales para operaciones deterministas.',stability:'runtime',source:'worker/lib/free-first.ts, worker/lib/providers.ts, worker/lib/planned-response.ts y runtime-registry.json'},
 {id:'hector-base-boundary',subject:'hector-os',statement:'Hablar con Héctor Base significa usar una base abierta bajo la identidad, memoria, herramientas, routing y controles de Héctor OS. Sus pesos todavía no son una adaptación personalizada. El chat no usa OpenAI, no tiene búsqueda web en vivo y falla de forma visible si Workers AI no está disponible.',stability:'runtime',source:'routing efectivo, trazas de proveedor/modelo y registro del runtime'},
 {id:'hector-model-project',subject:'hector-os',statement:'Hector ASI sí incluye un proyecto de modelo personalizado derivado de Qwen3-4B-Instruct-2507 mediante QLoRA + SFT, con dataset versionado, puertas de promoción y árbol de candidatos.',stability:'runtime',source:'model/hector-asi/model-registry.json y README del modelo'},
 {id:'hector-model-boundary',subject:'hector-os',statement:'El candidato Qwen personalizado continúa separado de Héctor Base. Todavía está planeado, no tiene adaptador entrenado ni existe un campeón propio validado; no debe afirmarse lo contrario.',stability:'runtime',source:'model/hector-asi/model-registry.json y runtime efectivo'},
 {id:'hector-evidence',subject:'hector-os',statement:'Solo debe afirmar una capacidad cuando existe componente, permiso y evidencia. Debe distinguir reglas propias, base abierta operativa, proveedor maestro de entrenamiento, candidato personalizado y campeón promovido.',stability:'stable',source:'contratos, trazas y política de evidencia'},
 {id:'openai-role',subject:'openai',statement:'Dentro de Hector ASI, OpenAI está reservado para generar datos con licencia compatible, crítica maestra, preferencias, evaluación de candidatos y diagnóstico del pipeline de entrenamiento. No está autorizado para responder el chat interactivo ni como fallback silencioso.',stability:'runtime',source:'model/hector-asi/runtime-registry.json y contratos del runtime conversacional'},
 {id:'openai-api',subject:'openai',statement:'La disponibilidad, modelos, precios y límites de la API de OpenAI cambian con el tiempo y deben verificarse en documentación oficial antes de ejecutar un trabajo de entrenamiento o evaluación pagado.',stability:'time-sensitive',source:'https://developers.openai.com/api/docs/'},
 {id:'work-role',subject:'work',statement:'ChatGPT Work está orientado a trabajos largos y multi‑paso, investigación, análisis y entregables. Puede ejecutarse una vez, programarse o vigilar cambios desde la nube.',stability:'time-sensitive',source:'https://help.openai.com/en/articles/20001275/'},
 {id:'work-boundary',subject:'work',statement:'Work no es la identidad ni la memoria de Héctor OS; es una superficie externa de OpenAI y referencia para su sistema de trabajos.',stability:'stable',source:'arquitectura de Héctor OS + OpenAI Help Center'},
 {id:'codex-role',subject:'codex',statement:'Codex es el agente de programación de OpenAI para inspeccionar repositorios, escribir y depurar código, ejecutar comandos y pruebas y proponer cambios revisables.',stability:'time-sensitive',source:'https://help.openai.com/en/articles/11369540-using-codex-with-your-chatgpt-plan'},
 {id:'codex-boundary',subject:'codex',statement:'El runner de Héctor OS adopta el patrón Codex —inspeccionar, editar, probar, corregir y abrir PR— sin convertir a Codex en el modelo del chat.',stability:'runtime',source:'agent-code-runner.yml y rutas runner'},
 {id:'gpt56-family',subject:'gpt-5.6',statement:'La familia y disponibilidad de modelos GPT‑5.6 son hechos temporales que requieren verificación oficial antes de cualquier uso pagado.',stability:'time-sensitive',source:'https://developers.openai.com/api/docs/models'},
 {id:'gpt56-runtime',subject:'gpt-5.6',statement:'Los modelos de OpenAI configurados en el entorno quedan fuera del chat interactivo. Pueden utilizarse únicamente en procesos separados de generación de datos, crítica, evaluación y entrenamiento con presupuesto y trazabilidad.',stability:'runtime',source:'runtime-registry.json, proveedores y pipeline de entrenamiento'},
 {id:'gpt56-evidence',subject:'gpt-5.6',statement:'Toda utilización como maestro o evaluador debe registrar modelo devuelto, propósito, costo, dataset o candidato afectado y trazas; una variable de entorno aislada no demuestra uso efectivo.',stability:'stable',source:'api_usage, manifiestos de entrenamiento y reportes de evaluación'},
 {id:'owner-profile',subject:'owner',statement:'El propietario es Héctor Raúl Hernández Ruiz, técnico en electromecánica y estudiante de ingeniería biomédica. Prefiere el modelo completo, nivel ingeniería, decisiones directas, continuidad y autonomía segura.',stability:'runtime',source:'perfil explícito y memoria privada'},
 {id:'owner-goal',subject:'owner',statement:'Su objetivo es un asistente privado para iPhone/PWA, persistente, modular y cada vez más independiente, con aprobación humana para acciones irreversibles.',stability:'runtime',source:'objetivo explícito del proyecto'}
];
export const CAPABILITY_MATRIX=[
 {capability:'Base abierta operativa',components:['hector-rules-v1','Llama 3.2 3B Instruct','Granite 4.0 H Micro','Workers AI','router adaptativo'],evidence:'provider, model, tier, fallback y response trace',limit:'no son todavía pesos personalizados; no hay web en vivo y no existe fallback a OpenAI'},
 {capability:'Identidad y autoconocimiento',components:['bootstrap','product-knowledge','system_context'],evidence:'manifiesto, estado y evaluaciones',limit:'las instrucciones no cambian los pesos del modelo'},
 {capability:'Memoria personal',components:['D1','memories','embeddings','summaries'],evidence:'centro de memoria y recuperación contextual',limit:'puede estar incompleta o desactualizada'},
 {capability:'Deliberación abierta multiagente',components:['Llama 3.2 3B Instruct','arquitecto','adversario','juez','feedback routing'],evidence:'modelo abierto, modo cognitivo, pasadas, calidad y trazas',limit:'más pasadas aumentan latencia y no sustituyen verificación externa'},
 {capability:'Programación autónoma',components:['GitHub Actions','runner','ramas','PRs','checks'],evidence:'commit, PR y pruebas',limit:'depende de permisos, checks y despliegue verificable'},
 {capability:'Investigación con evidencia aportada',components:['contexto','archivos','fuentes proporcionadas','response contract'],evidence:'fuentes incluidas, archivos y fecha',limit:'el chat no navega la web en vivo'},
 {capability:'Trabajo programado',components:['scheduled_tasks','cron','leases','work_jobs'],evidence:'ejecuciones persistidas',limit:'evita solapamientos y puede aplazarse'},
 {capability:'Archivos y evidencia',components:['R2','files','work evidence'],evidence:'objetos privados autenticados',limit:'no crea URLs públicas'},
 {capability:'Aprendizaje correctivo',components:['response_traces','feedback routing','provider quality','contracts'],evidence:'recomendaciones, fallos, costo y memoria usada',limit:'las heurísticas no garantizan verdad factual'}
] as const;
export function knowledgeNeedsFreshSource(subject:KnowledgeFact['subject']){return PRODUCT_FACTS.some(f=>f.subject===subject&&f.stability==='time-sensitive');}
export function renderProductKnowledge(){const facts=PRODUCT_FACTS.map(f=>`- [${f.subject}; ${f.stability}; fuente: ${f.source}] ${f.statement}`).join('\n'),caps=CAPABILITY_MATRIX.map(x=>`- ${x.capability}. Componentes: ${x.components.join(', ')}. Evidencia: ${x.evidence}. Límite: ${x.limit}.`).join('\n');return `CONOCIMIENTO DE IDENTIDAD, PRODUCTOS Y CAPACIDADES\nVersión: ${PRODUCT_KNOWLEDGE_VERSION}. Verificado: ${PRODUCT_KNOWLEDGE_VERIFIED_AT}.\n${facts}\n\nMATRIZ DE CAPACIDADES\n${caps}\n\nLos hechos time-sensitive sobre OpenAI, Work, Codex o GPT‑5.6 deben comprobarse únicamente con fuentes oficiales actuales.`;}
