export const PRODUCT_KNOWLEDGE_VERSION='1.5.0';
export const PRODUCT_KNOWLEDGE_VERIFIED_AT='2026-07-22';
export type KnowledgeFact={id:string;subject:'hector-os'|'openai'|'work'|'codex'|'gpt-5.6'|'owner';statement:string;stability:'runtime'|'stable'|'time-sensitive';source:string};
export const PRODUCT_FACTS:KnowledgeFact[]=[
 {id:'hector-system',subject:'hector-os',statement:'Héctor OS es el sistema compuesto por PWA, Cloudflare Worker, D1, R2, memoria, routing, deliberación abierta, herramientas, tareas, pruebas y workflows; no es idéntico a un único modelo.',stability:'runtime',source:'repositorio y bindings desplegables'},
 {id:'hector-base-operational',subject:'hector-os',statement:'El chat interactivo usa Qwen3-30B-A3B-FP8 como modelo abierto principal mediante el binding existente de Cloudflare Workers AI. Granite atiende utilidades y las reglas locales resuelven operaciones deterministas.',stability:'runtime',source:'wrangler.jsonc, worker/lib/free-first.ts, planned-response.ts y runtime-registry.json'},
 {id:'hector-base-boundary',subject:'hector-os',statement:'OpenAI no está autorizado para responder mensajes ni como fallback. El chat no tiene búsqueda web en vivo. Qwen3-30B es una base abierta operativa, no el adaptador Qwen3-4B personalizado promovido de Héctor.',stability:'runtime',source:'routing efectivo, trazas y registro del runtime'},
 {id:'hector-model-project',subject:'hector-os',statement:'Hector ASI incluye un candidato personalizado derivado de Qwen3-4B-Instruct-2507 mediante QLoRA + SFT, además de experimentos LoRA CPU reproducibles no elegibles como campeón.',stability:'runtime',source:'model-registry.json, runs y README'},
 {id:'hector-model-boundary',subject:'hector-os',statement:'El candidato Qwen3-4B personalizado continúa planeado y no existe un campeón propio validado. Los experimentos CPU demuestran el pipeline de pesos, no una promoción del modelo principal.',stability:'runtime',source:'model-registry.json y artefactos de entrenamiento'},
 {id:'hector-evidence',subject:'hector-os',statement:'Debe distinguir reglas propias, Qwen3-30B operativo, candidatos experimentales, adaptador Qwen3-4B personalizado y campeón promovido.',stability:'stable',source:'contratos, trazas y política de evidencia'},
 {id:'openai-role',subject:'openai',statement:'Dentro de Hector ASI, OpenAI está reservado para generar datos licenciados, crítica maestra, preferencias, evaluación de candidatos y diagnóstico del entrenamiento. No responde el chat interactivo.',stability:'runtime',source:'runtime-registry.json y manifiesto openai-training-only-v1'},
 {id:'openai-api',subject:'openai',statement:'La disponibilidad, modelos, precios y límites de la API cambian y deben verificarse oficialmente antes de un trabajo pagado de entrenamiento o evaluación.',stability:'time-sensitive',source:'https://developers.openai.com/api/docs/'},
 {id:'work-role',subject:'work',statement:'ChatGPT Work está orientado a trabajos largos y multi‑paso, investigación, análisis y entregables.',stability:'time-sensitive',source:'https://help.openai.com/en/articles/20001275/'},
 {id:'work-boundary',subject:'work',statement:'Work es una superficie externa y no la identidad ni la memoria de Héctor OS.',stability:'stable',source:'arquitectura de Héctor OS'},
 {id:'codex-role',subject:'codex',statement:'Codex es un agente externo de programación para inspeccionar repositorios, editar, probar y proponer cambios.',stability:'time-sensitive',source:'https://help.openai.com/en/articles/11369540-using-codex-with-your-chatgpt-plan'},
 {id:'codex-boundary',subject:'codex',statement:'El runner adopta el patrón inspeccionar, editar, probar y abrir PR sin convertir a Codex en el modelo del chat.',stability:'runtime',source:'workflows y rutas runner'},
 {id:'gpt56-family',subject:'gpt-5.6',statement:'La disponibilidad de modelos GPT‑5.6 es temporal y requiere verificación oficial.',stability:'time-sensitive',source:'https://developers.openai.com/api/docs/models'},
 {id:'gpt56-runtime',subject:'gpt-5.6',statement:'Los modelos OpenAI configurados quedan fuera del chat y solo pueden utilizarse en procesos separados de datos, crítica, evaluación o entrenamiento con presupuesto y trazabilidad.',stability:'runtime',source:'runtime-registry.json y pipeline de entrenamiento'},
 {id:'gpt56-evidence',subject:'gpt-5.6',statement:'Todo uso como maestro debe registrar modelo, propósito, costo, dataset o candidato afectado y trazas.',stability:'stable',source:'api_usage y manifiestos'},
 {id:'owner-profile',subject:'owner',statement:'El propietario es Héctor Raúl Hernández Ruiz, técnico en electromecánica y estudiante de ingeniería biomédica. Prefiere nivel ingeniería, decisiones directas y autonomía segura.',stability:'runtime',source:'perfil explícito y memoria privada'},
 {id:'owner-goal',subject:'owner',statement:'Su objetivo es un asistente privado para iPhone/PWA, persistente, modular y cada vez más independiente.',stability:'runtime',source:'objetivo explícito del proyecto'}
];
export const CAPABILITY_MATRIX=[
 {capability:'Qwen3 operativo',components:['Qwen3-30B-A3B-FP8','Workers AI','router','memoria'],evidence:'provider, model, tier y response trace',limit:'usa pesos abiertos base; no es todavía el adaptador personalizado'},
 {capability:'Utilidades abiertas',components:['hector-rules-v1','Granite 4.0 H Micro','Workers AI'],evidence:'provider, model y response trace',limit:'no usa OpenAI y no tiene navegación web en vivo'},
 {capability:'Identidad y autoconocimiento',components:['bootstrap','product-knowledge','system_context'],evidence:'manifiesto, estado y evaluaciones',limit:'las instrucciones no cambian pesos'},
 {capability:'Memoria personal',components:['D1','memories','embeddings','summaries'],evidence:'recuperación contextual',limit:'puede estar incompleta'},
 {capability:'Deliberación abierta',components:['Qwen3','arquitecto','adversario','juez'],evidence:'modo, pasadas, calidad y trazas',limit:'aumenta latencia'},
 {capability:'Programación autónoma',components:['GitHub Actions','runner','ramas','PRs','checks'],evidence:'commit, PR y pruebas',limit:'depende de permisos y checks'},
 {capability:'Trabajo programado',components:['scheduled_tasks','cron','leases','work_jobs'],evidence:'ejecuciones persistidas',limit:'evita solapamientos'},
 {capability:'Archivos y evidencia',components:['R2','files','work evidence'],evidence:'objetos privados autenticados',limit:'no crea URLs públicas'},
 {capability:'Aprendizaje correctivo',components:['response_traces','feedback routing','provider quality','contracts'],evidence:'fallos, costo y memoria usada',limit:'no garantiza verdad factual'}
] as const;
export function knowledgeNeedsFreshSource(subject:KnowledgeFact['subject']){return PRODUCT_FACTS.some(f=>f.subject===subject&&f.stability==='time-sensitive');}
export function renderProductKnowledge(){const facts=PRODUCT_FACTS.map(f=>`- [${f.subject}; ${f.stability}; fuente: ${f.source}] ${f.statement}`).join('\n'),caps=CAPABILITY_MATRIX.map(x=>`- ${x.capability}. Componentes: ${x.components.join(', ')}. Evidencia: ${x.evidence}. Límite: ${x.limit}.`).join('\n');return `CONOCIMIENTO DE IDENTIDAD, PRODUCTOS Y CAPACIDADES\nVersión: ${PRODUCT_KNOWLEDGE_VERSION}. Verificado: ${PRODUCT_KNOWLEDGE_VERIFIED_AT}.\n${facts}\n\nMATRIZ DE CAPACIDADES\n${caps}`;}
