import { Hono } from 'hono'; import { setCookie, deleteCookie } from 'hono/cookie'; import { z } from 'zod';
import type { Bindings, Variables } from '../types'; import { hashPassword, randomToken, sha256, verifyPassword } from '../lib/crypto'; import { requireAuth } from '../lib/auth';
export const auth = new Hono<{Bindings:Bindings;Variables:Variables}>();
const credentials=z.object({email:z.string().email(),password:z.string().min(10).max(128),name:z.string().min(2).max(60).optional()});
const cookie=(c:any,token:string)=>setCookie(c,'hector_session',token,{httpOnly:true,secure:true,sameSite:'Strict',path:'/',maxAge:60*60*24*30});
auth.post('/register',async c=>{const parsed=credentials.safeParse(await c.req.json());if(!parsed.success)return c.json({error:'Datos inválidos',details:parsed.error.flatten()},400);const count=await c.env.DB.prepare('SELECT COUNT(*) n FROM users').first<{n:number}>();if((count?.n||0)>0)return c.json({error:'El propietario ya fue registrado'},409);const id=crypto.randomUUID(),{hash,salt}=await hashPassword(parsed.data.password);await c.env.DB.prepare('INSERT INTO users(id,email,name,password_hash,password_salt) VALUES(?,?,?,?,?)').bind(id,parsed.data.email.toLowerCase(),parsed.data.name||'Héctor',hash,salt).run();const token=randomToken(),sid=crypto.randomUUID();await c.env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,datetime('now','+30 days'))").bind(sid,id,await sha256(token)).run();cookie(c,token);return c.json({user:{id,name:parsed.data.name||'Héctor'}})});
auth.post('/login',async c=>{const parsed=credentials.safeParse(await c.req.json());if(!parsed.success)return c.json({error:'Credenciales inválidas'},400);const u=await c.env.DB.prepare('SELECT * FROM users WHERE email=?').bind(parsed.data.email.toLowerCase()).first<any>();if(!u||!await verifyPassword(parsed.data.password,u.password_salt,u.password_hash))return c.json({error:'Credenciales inválidas'},401);const token=randomToken();await c.env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,datetime('now','+30 days'))").bind(crypto.randomUUID(),u.id,await sha256(token)).run();cookie(c,token);return c.json({user:{id:u.id,name:u.name}})});
auth.post('/logout',requireAuth,async c=>{const raw=(await import('hono/cookie')).getCookie(c,'hector_session');if(raw)await c.env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(raw)).run();deleteCookie(c,'hector_session',{path:'/'});return c.json({ok:true})});
auth.get('/me',requireAuth,c=>c.json({user:{id:c.get('userId'),name:c.get('userName')}}));
