import { Hono } from 'hono';
import { z } from 'zod';
import type { Bindings } from '../types';
import { sha256 } from '../lib/crypto';

export const control=new Hono<{Bindings:Bindings}>();
control.use('*',async(c,next)=>{const supplied=(c.req.header('Authorization')||'').replace(/^Bearer\s+/i,'').trim(),expected=c.env.REMOTE_CONTROL_TOKEN?.trim();if(!expected||!supplied||(await sha256(supplied))!==(await sha256(expected)))return c.json({error:'No autorizado'},401);await next()});
const audit=(db:D1Database,action:string,target:string,status:string,details?:unknown)=>db.prepare('INSERT INTO control_audit(id,actor,action,target,status,details_json) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),'codex-bridge',action,target,status,details?JSON.stringify(details):null).run();
control.get('/status',async c=>{const [projects,jobs,apis,usage]=await Promise.all([c.env.DB.prepare('SELECT COUNT(*) n FROM app_projects').first<any>(),c.env.DB.prepare("SELECT COUNT(*) n FROM work_jobs WHERE status IN ('queued','working')").first<any>(),c.env.DB.prepare("SELECT COUNT(*) n FROM generated_apis WHERE status='active'").first<any>(),c.env.DB.prepare("SELECT COALESCE(SUM(estimated_cost_usd),0) usd FROM api_usage WHERE created_at>=datetime('now','start of month')").first<any>()]);await audit(c.env.DB,'read_status','hector-os','success');return c.json({ok:true,service:c.env.APP_NAME,github:{repository:'Hector35/Hector-IA',branch:'main'},cloudflare:{worker:'hector-os'},counts:{projects:projects?.n||0,activeJobs:jobs?.n||0,apis:apis?.n||0},monthEstimatedCostUsd:usage?.usd||0})});
control.get('/projects',async c=>c.json({items:(await c.env.DB.prepare('SELECT id,name,template,status,deployment_url,created_at,updated_at FROM app_projects ORDER BY created_at DESC LIMIT 50').all()).results}));
control.get('/tasks',async c=>c.json({items:(await c.env.DB.prepare('SELECT id,kind,title,status,progress,result,heartbeat_at,created_at,updated_at FROM work_jobs ORDER BY created_at DESC LIMIT 50').all()).results}));
control.get('/audit',async c=>c.json({items:(await c.env.DB.prepare('SELECT * FROM control_audit ORDER BY created_at DESC LIMIT 100').all()).results}));
control.post('/tasks',async c=>{const p=z.object({kind:z.enum(['research','learning','programming','automation','agent','api','skill','update']),title:z.string().min(3).max(100),prompt:z.string().min(10).max(8000)}).safeParse(await c.req.json());if(!p.success)return c.json({error:'Trabajo inválido'},400);const owner=await c.env.DB.prepare('SELECT id FROM users ORDER BY created_at LIMIT 1').first<any>();if(!owner)return c.json({error:'Propietario no configurado'},409);const id=crypto.randomUUID();await c.env.DB.batch([c.env.DB.prepare('INSERT INTO work_jobs(id,user_id,kind,title,prompt,heartbeat_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP)').bind(id,owner.id,p.data.kind,p.data.title,p.data.prompt),c.env.DB.prepare("INSERT INTO work_events(id,job_id,message,progress) VALUES(?,?, 'Solicitud recibida por el puente Codex',0)").bind(crypto.randomUUID(),id)]);let runner='not-required',runnerStatus:number|undefined;if(['programming','automation','agent','api','skill','update'].includes(p.data.kind)){const token=c.env.GITHUB_RUNNER_TOKEN?.trim();if(!token)runner='unavailable';else{const r=await fetch('https://api.github.com/repos/Hector35/Hector-IA/actions/workflows/hector-runner.yml/dispatches',{method:'POST',headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','User-Agent':'Hector-OS-Control'},body:JSON.stringify({ref:'main',inputs:{task:`${p.data.title}: ${p.data.prompt}`.slice(0,5000)}})});runnerStatus=r.status;runner=r.status===204?'accepted':'rejected'}}await audit(c.env.DB,'create_task',id,runner==='rejected'?'blocked':'accepted',{kind:p.data.kind,runner,runnerStatus});return c.json({id,status:'queued',runner,runnerStatus},201)});
