import { Hono } from 'hono';
import { z } from 'zod';
import type { Bindings } from '../types';
import { sha256 } from '../lib/crypto';

export const generated = new Hono<{Bindings:Bindings}>();
const field=z.object({name:z.string().regex(/^[a-z][a-z0-9_]{0,39}$/),type:z.enum(['string','number','boolean','date','json']),required:z.boolean().default(false)});

function openapi(origin:string,api:any){const fields=z.array(field).parse(JSON.parse(api.schema_json));const properties=Object.fromEntries(fields.map(x=>[x.name,{type:x.type==='date'?'string':x.type==='json'?'object':x.type,format:x.type==='date'?'date-time':undefined}]));return {openapi:'3.1.0',info:{title:api.name,version:'1.0.0',description:api.description},servers:[{url:`${origin}/generated/${api.slug}`}],components:{securitySchemes:{apiKey:{type:'http',scheme:'bearer'}},schemas:{Record:{type:'object',properties,required:fields.filter(x=>x.required).map(x=>x.name)}}},security:[{apiKey:[]}],paths:{'/records':{get:{summary:'Listar registros'},post:{summary:'Crear registro',requestBody:{required:true,content:{'application/json':{schema:{$ref:'#/components/schemas/Record'}}}}}},'/records/{id}':{get:{summary:'Obtener registro'},put:{summary:'Actualizar registro'},delete:{summary:'Eliminar registro'}}}}}
async function access(c:any,write=false){const raw=(c.req.header('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!raw)return null;const row=await c.env.DB.prepare(`SELECT a.*,k.id key_id,k.scopes_json FROM generated_apis a JOIN generated_api_keys k ON k.api_id=a.id WHERE a.slug=? AND a.status='active' AND k.token_hash=? AND (k.expires_at IS NULL OR k.expires_at>CURRENT_TIMESTAMP)`).bind(c.req.param('slug'),await sha256(raw)).first();if(!row)return null;const scopes=JSON.parse(row.scopes_json);if(write&&!scopes.includes('write'))return null;await c.env.DB.prepare('UPDATE generated_api_keys SET last_used_at=CURRENT_TIMESTAMP WHERE id=?').bind(row.key_id).run();return row}
function validData(api:any,input:unknown){if(!input||typeof input!=='object'||Array.isArray(input))return null;const fields=z.array(field).parse(JSON.parse(api.schema_json)),source=input as Record<string,unknown>,out:Record<string,unknown>={};for(const f of fields){const v=source[f.name];if(v===undefined||v===null){if(f.required)return null;continue}if(f.type==='string'&&typeof v!=='string'||f.type==='number'&&typeof v!=='number'||f.type==='boolean'&&typeof v!=='boolean'||f.type==='date'&&(typeof v!=='string'||Number.isNaN(Date.parse(v)))||f.type==='json'&&(typeof v!=='object'||Array.isArray(v)))return null;out[f.name]=v}return out}
generated.get('/:slug/openapi.json',async c=>{const api=await c.env.DB.prepare("SELECT * FROM generated_apis WHERE slug=? AND status='active'").bind(c.req.param('slug')).first<any>();return api?c.json(openapi(new URL(c.req.url).origin,api)):c.json({error:'API no encontrada'},404)});
generated.get('/:slug/records',async c=>{const api=await access(c);if(!api)return c.json({error:'Clave inválida o sin alcance'},401);const rows=(await c.env.DB.prepare('SELECT id,data_json,created_at,updated_at FROM generated_api_records WHERE api_id=? ORDER BY created_at DESC LIMIT 100').bind(api.id).all<any>()).results.map((x:any)=>({...x,data:JSON.parse(x.data_json)}));return c.json({items:rows})});
generated.post('/:slug/records',async c=>{const api=await access(c,true);if(!api)return c.json({error:'Clave inválida o sin alcance'},401);const data=validData(api,await c.req.json());if(!data)return c.json({error:'Registro no coincide con el esquema'},400);const id=crypto.randomUUID();await c.env.DB.prepare('INSERT INTO generated_api_records(id,api_id,data_json) VALUES(?,?,?)').bind(id,api.id,JSON.stringify(data)).run();return c.json({id,data},201)});
generated.get('/:slug/records/:id',async c=>{const api=await access(c);if(!api)return c.json({error:'Clave inválida o sin alcance'},401);const row=await c.env.DB.prepare('SELECT id,data_json,created_at,updated_at FROM generated_api_records WHERE id=? AND api_id=?').bind(c.req.param('id'),api.id).first<any>();return row?c.json({...row,data:JSON.parse(row.data_json)}):c.json({error:'No encontrado'},404)});
generated.put('/:slug/records/:id',async c=>{const api=await access(c,true);if(!api)return c.json({error:'Clave inválida o sin alcance'},401);const data=validData(api,await c.req.json());if(!data)return c.json({error:'Registro no coincide con el esquema'},400);const r=await c.env.DB.prepare('UPDATE generated_api_records SET data_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND api_id=?').bind(JSON.stringify(data),c.req.param('id'),api.id).run();return r.meta.changes?c.json({id:c.req.param('id'),data}):c.json({error:'No encontrado'},404)});
generated.delete('/:slug/records/:id',async c=>{const api=await access(c,true);if(!api)return c.json({error:'Clave inválida o sin alcance'},401);const r=await c.env.DB.prepare('DELETE FROM generated_api_records WHERE id=? AND api_id=?').bind(c.req.param('id'),api.id).run();return r.meta.changes?c.json({ok:true}):c.json({error:'No encontrado'},404)});
