import {Hono} from 'hono';
import {z} from 'zod';
import type {Bindings,Variables} from '../types';
import {requireAuth} from '../lib/auth';

export const pwaFactory=new Hono<{Bindings:Bindings;Variables:Variables}>();
pwaFactory.use('*',requireAuth);

const createSchema=z.object({
  name:z.string().min(2).max(80),
  objective:z.string().min(10).max(6000),
  description:z.string().max(500).optional(),
  themeColor:z.string().regex(/^#[0-9a-fA-F]{6}$/).default('#111827'),
  backgroundColor:z.string().regex(/^#[0-9a-fA-F]{6}$/).default('#ffffff'),
  offline:z.boolean().default(true)
});

function slugify(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48)||`pwa-${Date.now()}`;}
function esc(value:string){return value.replace(/\\/g,'\\\\').replace(/`/g,'\\`').replace(/\$\{/g,'\\${');}

function sourceFiles(spec:{name:string;slug:string;objective:string;description:string;themeColor:string;backgroundColor:string;offline:boolean}){
 const pkg={name:spec.slug,private:true,version:'0.1.0',type:'module',scripts:{dev:'vite',build:'tsc -b && vite build',typecheck:'tsc -b'},dependencies:{'@vitejs/plugin-react':'latest',vite:'latest',typescript:'latest',react:'latest','react-dom':'latest'},devDependencies:{'@types/react':'latest','@types/react-dom':'latest'}};
 const manifest={name:spec.name,short_name:spec.name.slice(0,18),description:spec.description||spec.objective.slice(0,140),id:'/',start_url:'/',scope:'/',display:'standalone',background_color:spec.backgroundColor,theme_color:spec.themeColor,orientation:'portrait-primary',icons:[{src:'/icon.svg',sizes:'any',type:'image/svg+xml',purpose:'any maskable'}]};
 const app=`import {useState} from 'react';\nimport './style.css';\nexport default function App(){const [items,setItems]=useState<string[]>([]),[value,setValue]=useState('');return <main><section className=\"card\"><p className=\"eyebrow\">PWA creada por Héctor OS</p><h1>${esc(spec.name)}</h1><p>${esc(spec.objective)}</p><form onSubmit={e=>{e.preventDefault();const v=value.trim();if(v){setItems(x=>[...x,v]);setValue('')}}}><input aria-label=\"Nuevo elemento\" value={value} onChange={e=>setValue(e.target.value)} placeholder=\"Escribe algo\"/><button>Agregar</button></form><ul>{items.map((item,i)=><li key={i}>{item}</li>)}</ul></section></main>}\n`;
 const style=`:root{font-family:Inter,system-ui,sans-serif;color:#111827;background:${spec.backgroundColor};font-synthesis:none}*{box-sizing:border-box}body{margin:0;min-width:320px;min-height:100vh;background:linear-gradient(160deg,${spec.backgroundColor},#e5e7eb)}main{min-height:100vh;display:grid;place-items:center;padding:max(24px,env(safe-area-inset-top)) 18px max(24px,env(safe-area-inset-bottom))}.card{width:min(100%,560px);padding:28px;border-radius:28px;background:rgba(255,255,255,.88);box-shadow:0 20px 60px rgba(15,23,42,.14);backdrop-filter:blur(20px)}.eyebrow{font-size:.78rem;text-transform:uppercase;letter-spacing:.12em;color:#64748b}h1{font-size:clamp(2rem,8vw,4rem);margin:.25rem 0}form{display:flex;gap:8px;margin:24px 0}input,button{font:inherit;border-radius:14px;padding:12px 14px}input{flex:1;border:1px solid #cbd5e1}button{border:0;background:${spec.themeColor};color:white;font-weight:700}li{padding:10px 0;border-bottom:1px solid #e2e8f0}`;
 const sw=`const CACHE='${spec.slug}-v1';const SHELL=['/','/manifest.webmanifest','/icon.svg'];self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting())));self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;e.respondWith(fetch(e.request).then(r=>{if(r.ok){const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy))}return r}).catch(()=>caches.match(e.request).then(r=>r||caches.match('/'))))});`;
 return {
  'package.json':JSON.stringify(pkg,null,2),
  'tsconfig.json':JSON.stringify({files:[],references:[{path:'./tsconfig.app.json'}]},null,2),
  'tsconfig.app.json':JSON.stringify({compilerOptions:{target:'ES2022',useDefineForClassFields:true,lib:['ES2022','DOM','DOM.Iterable'],allowJs:false,skipLibCheck:true,esModuleInterop:true,allowSyntheticDefaultImports:true,strict:true,forceConsistentCasingInFileNames:true,module:'ESNext',moduleResolution:'Bundler',resolveJsonModule:true,isolatedModules:true,noEmit:true,jsx:'react-jsx'},include:['src']},null,2),
  'vite.config.ts':"import {defineConfig} from 'vite';import react from '@vitejs/plugin-react';export default defineConfig({plugins:[react()]});",
  'index.html':`<!doctype html><html lang=\"es\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,viewport-fit=cover\"><meta name=\"theme-color\" content=\"${spec.themeColor}\"><meta name=\"apple-mobile-web-app-capable\" content=\"yes\"><meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\"><meta name=\"apple-mobile-web-app-title\" content=\"${esc(spec.name)}\"><link rel=\"manifest\" href=\"/manifest.webmanifest\"><link rel=\"apple-touch-icon\" href=\"/icon.svg\"><title>${esc(spec.name)}</title></head><body><div id=\"root\"></div><script type=\"module\" src=\"/src/main.tsx\"></script></body></html>`,
  'public/manifest.webmanifest':JSON.stringify(manifest,null,2),
  'public/icon.svg':`<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><rect width=\"512\" height=\"512\" rx=\"112\" fill=\"${spec.themeColor}\"/><text x=\"256\" y=\"305\" text-anchor=\"middle\" font-size=\"220\" font-family=\"system-ui\" font-weight=\"800\" fill=\"white\">${esc(spec.name.slice(0,1).toUpperCase())}</text></svg>`,
  'public/sw.js':sw,
  'src/main.tsx':"import React from 'react';import ReactDOM from 'react-dom/client';import App from './App';ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));",
  'src/App.tsx':app,
  'src/style.css':style
 };
}

async function gh(token:string,path:string,init:RequestInit={}){const r=await fetch(`https://api.github.com/repos/Hector35/Hector-IA${path}`,{...init,headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','User-Agent':'Hector-OS-PWA-Factory','Content-Type':'application/json',...(init.headers||{})}});const d=await r.json<any>().catch(()=>({}));if(!r.ok)throw new Error(`GitHub ${r.status}: ${d?.message||'error'}`);return d;}

pwaFactory.post('/',async c=>{const parsed=createSchema.safeParse(await c.req.json());if(!parsed.success)return c.json({error:'Especificación inválida',details:parsed.error.flatten()},400);const uid=c.get('userId'),id=crypto.randomUUID(),slug=slugify(parsed.data.name),spec={...parsed.data,slug,description:parsed.data.description||''};const files=sourceFiles(spec);await c.env.DB.batch([c.env.DB.prepare("INSERT INTO pwa_projects(id,user_id,name,slug,objective,specification_json,status,current_version) VALUES(?,?,?,?,?,?,'draft',1)").bind(id,uid,spec.name,slug,spec.objective,JSON.stringify(spec)),c.env.DB.prepare("INSERT INTO pwa_project_versions(id,project_id,version,source_json,build_status) VALUES(?,?,1,?,'pending')").bind(crypto.randomUUID(),id,JSON.stringify(files))]);return c.json({id,name:spec.name,slug,status:'draft',version:1,fileCount:Object.keys(files).length},201);});

pwaFactory.get('/',async c=>c.json({items:(await c.env.DB.prepare('SELECT id,name,slug,objective,status,repository,branch,preview_url,production_url,current_version,last_error,created_at,updated_at FROM pwa_projects WHERE user_id=? ORDER BY updated_at DESC LIMIT 100').bind(c.get('userId')).all()).results}));

pwaFactory.get('/:id',async c=>{const project=await c.env.DB.prepare('SELECT * FROM pwa_projects WHERE id=? AND user_id=?').bind(c.req.param('id'),c.get('userId')).first<any>();if(!project)return c.json({error:'PWA no encontrada'},404);const versions=(await c.env.DB.prepare('SELECT id,version,commit_sha,build_status,build_run_id,preview_url,production_url,created_at FROM pwa_project_versions WHERE project_id=? ORDER BY version DESC').bind(project.id).all()).results;return c.json({project,versions});});

pwaFactory.post('/:id/publish-source',async c=>{const uid=c.get('userId'),id=c.req.param('id'),project=await c.env.DB.prepare('SELECT * FROM pwa_projects WHERE id=? AND user_id=?').bind(id,uid).first<any>();if(!project)return c.json({error:'PWA no encontrada'},404);const version=await c.env.DB.prepare('SELECT * FROM pwa_project_versions WHERE project_id=? AND version=?').bind(id,project.current_version).first<any>();if(!version)return c.json({error:'Versión no encontrada'},404);const token=c.env.GITHUB_RUNNER_TOKEN?.trim();if(!token)return c.json({error:'GITHUB_RUNNER_TOKEN no configurado'},503);const main=await gh(token,'/git/ref/heads/main'),branch=`pwa/${project.slug}-${id.slice(0,8)}-v${version.version}`;try{await gh(token,'/git/refs',{method:'POST',body:JSON.stringify({ref:`refs/heads/${branch}`,sha:main.object.sha})});}catch(e){if(!String(e).includes('Reference already exists'))throw e;}const files=JSON.parse(version.source_json) as Record<string,string>;let lastSha='';for(const [path,content] of Object.entries(files)){const repoPath=`generated-pwas/${project.slug}/${path}`;const result=await gh(token,`/contents/${repoPath}`,{method:'PUT',body:JSON.stringify({message:`feat(pwa): generate ${project.slug} v${version.version}`,content:btoa(unescape(encodeURIComponent(content))),branch})});lastSha=result.commit?.sha||lastSha;}await c.env.DB.batch([c.env.DB.prepare("UPDATE pwa_projects SET status='source_published',repository='Hector35/Hector-IA',branch=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(branch,id),c.env.DB.prepare("UPDATE pwa_project_versions SET commit_sha=?,build_status='queued' WHERE project_id=? AND version=?").bind(lastSha,id,version.version)]);const dispatch=await fetch('https://api.github.com/repos/Hector35/Hector-IA/actions/workflows/pwa-factory.yml/dispatches',{method:'POST',headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','User-Agent':'Hector-OS-PWA-Factory','Content-Type':'application/json'},body:JSON.stringify({ref:branch,inputs:{project_id:id,slug:project.slug,version:String(version.version),project_path:`generated-pwas/${project.slug}`}})});if(!dispatch.ok){const d=await dispatch.json<any>().catch(()=>({}));await c.env.DB.prepare("UPDATE pwa_projects SET status='blocked',last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(`Workflow ${dispatch.status}: ${d?.message||'error'}`,id).run();return c.json({error:'Fuente publicada, pero no se pudo iniciar la verificación',branch,commitSha:lastSha},502);}return c.json({id,status:'verifying',branch,commitSha:lastSha});});

pwaFactory.post('/:id/rollback/:version',async c=>{const uid=c.get('userId'),id=c.req.param('id'),target=Number(c.req.param('version'));if(!Number.isInteger(target)||target<1)return c.json({error:'Versión inválida'},400);const project=await c.env.DB.prepare('SELECT id FROM pwa_projects WHERE id=? AND user_id=?').bind(id,uid).first();if(!project)return c.json({error:'PWA no encontrada'},404);const version=await c.env.DB.prepare('SELECT version FROM pwa_project_versions WHERE project_id=? AND version=?').bind(id,target).first();if(!version)return c.json({error:'Versión no encontrada'},404);await c.env.DB.prepare("UPDATE pwa_projects SET current_version=?,status='rollback_ready',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(target,id).run();return c.json({id,currentVersion:target,status:'rollback_ready'});});
