import {Hono} from 'hono';
import {z} from 'zod';
import type {Bindings} from '../types';
import {verifyGitHubActionsToken} from '../lib/github-oidc';

const audience='hector-os-agent-runner';
const repository='Hector35/Hector-IA';
const allowedFiles=[
 'src/CodexApp.tsx','src/api.ts','src/MarkdownMessage.tsx','src/chat-content.css','src/codex-ui.css','src/codex-mobile.css',
 'worker/index.ts','worker/types.ts','worker/lib/openai.ts','worker/lib/context.ts','worker/routes/agent.ts','worker/routes/intelligence.ts','worker/routes/system.ts',
 'worker/agent/planner.ts','worker/agent/skills.ts','worker/agent/learning.ts'
];
const file=z.object({path:z.string(),content:z.string().max(90000)});
const proposalRequest=z.object({jobId:z.string().uuid(),task:z.string().min(10).max(10000),attempt:z.number().int().min(1).max(3),failure:z.string().max(12000).optional(),files:z.array(file).min(1).max(20)});
const proposal=z.object({summary:z.string().min(1).max(3000),risk:z.literal('low'),hypothesis:z.string().max(3000).optional(),acceptance:z.array(z.string().max(500)).max(20).optional(),changes:z.array(file).max(6)});
const statusSchema=z.object({jobId:z.string().uuid(),status:z.enum(['working','testing','repairing','completed','blocked']),progress:z.number().int().min(0).max(100),message:z.string().min(1).max(4000),result:z.string().max(20000).optional()});
const publishSchema=z.object({jobId:z.string().uuid(),proposal,verification:z.object({typecheck:z.literal(true),tests:z.literal(true),build:z.literal(true)}),runId:z.string().regex(/^\d+$/),runAttempt:z.string().regex(/^\d+$/)});

export const runner=new Hono<{Bindings:Bindings}>();

async function auth(c:any){const token=(c.req.header('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!token)throw new Error('OIDC requerido');return verifyGitHubActionsToken(token,audience);}
function validate(changes:Array<{path:string;content:string}>){let total=0;if(changes.length>6)throw new Error('Demasiados archivos');for(const x of changes){if(!allowedFiles.includes(x.path)||x.path.includes('..'))throw new Error(`Archivo no permitido: ${x.path}`);total+=x.content.length;}if(total>120000)throw new Error('Propuesta demasiado grande');}
async function gh(token:string,path:string,init:RequestInit={}){const r=await fetch(`https://api.github.com/repos/${repository}${path}`,{...init,headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','User-Agent':'Hector-OS-Agent-Runner','Content-Type':'application/json',...(init.headers||{})}});const d=await r.json<any>().catch(()=>({}));if(!r.ok)throw new Error(`GitHub ${r.status}: ${d?.message||'error'}`);return d;}

runner.post('/proposal',async c=>{try{await auth(c);const parsed=proposalRequest.safeParse(await c.req.json());if(!parsed.success)return c.json({error:'Payload inválido'},400);for(const f of parsed.data.files)if(!allowedFiles.includes(f.path))return c.json({error:`Archivo no permitido: ${f.path}`},400);const source=parsed.data.files.map(x=>`\n===== ${x.path} =====\n${x.content}`).join('\n').slice(0,260000);const instructions=`Eres el runner de ingeniería de Héctor OS. Resuelve una tarea real dentro del repositorio usando cambios mínimos, completos y verificables.\nREGLAS\n- Solo modifica archivos permitidos.\n- Máximo 6 archivos y 120000 caracteres.\n- No toques secretos, autenticación, workflows, migraciones ni infraestructura.\n- No borres archivos ni agregues dependencias.\n- Devuelve JSON puro: {"summary":"...","risk":"low","hypothesis":"...","acceptance":["..."],"changes":[{"path":"...","content":"archivo completo"}]}.\n- Si el intento anterior falló, corrige la causa indicada y cambia de estrategia.\n- Conserva compatibilidad de API y agrega o ajusta pruebas cuando sea posible.`;const input=`JOB ${parsed.data.jobId}\nINTENTO ${parsed.data.attempt}/3\nTAREA\n${parsed.data.task}\n\nFALLO ANTERIOR\n${parsed.data.failure||'ninguno'}\n\nARCHIVOS PERMITIDOS\n${allowedFiles.join('\n')}\n\nCÓDIGO\n${source}`;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${c.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:c.env.OPENAI_MODEL_REASONING||'gpt-5.4',instructions,input,store:false,reasoning:{effort:'high'},max_output_tokens:50000})});const data=await r.json<any>();if(!r.ok)return c.json({error:data?.error?.message||'Error de OpenAI'},502);const text=String(data.output_text||data.output?.flatMap((x:any)=>x.content||[]).map((x:any)=>x.text||'').join('')||'').trim();let raw:any;try{raw=JSON.parse(text)}catch{const m=text.match(/\{[\s\S]*\}/);if(!m)throw new Error('Respuesta no JSON');raw=JSON.parse(m[0]);}const safe=proposal.parse(raw);validate(safe.changes);return c.json(safe);}catch(e){return c.json({error:e instanceof Error?e.message:'Error'},401);}});

runner.post('/status',async c=>{try{await auth(c);const p=statusSchema.safeParse(await c.req.json());if(!p.success)return c.json({error:'Estado inválido'},400);const x=p.data;await c.env.DB.batch([c.env.DB.prepare('UPDATE work_jobs SET status=?,progress=?,result=COALESCE(?,result),heartbeat_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(x.status,x.progress,x.result||null,x.jobId),c.env.DB.prepare('INSERT INTO work_events(id,job_id,message,progress) VALUES(?,?,?,?)').bind(crypto.randomUUID(),x.jobId,x.message,x.progress)]);return c.json({ok:true});}catch(e){return c.json({error:e instanceof Error?e.message:'Error'},401);}});

runner.post('/publish',async c=>{try{await auth(c);const p=publishSchema.safeParse(await c.req.json());if(!p.success)return c.json({error:'Publicación inválida'},400);validate(p.data.proposal.changes);if(!p.data.proposal.changes.length)return c.json({published:false,reason:'Sin cambios'});const token=c.env.GITHUB_RUNNER_TOKEN?.trim();if(!token)return c.json({error:'GITHUB_RUNNER_TOKEN no configurado'},503);const main=await gh(token,'/git/ref/heads/main');const branch=`hector-agent/${p.data.jobId.slice(0,8)}-${p.data.runId}`;await gh(token,'/git/refs',{method:'POST',body:JSON.stringify({ref:`refs/heads/${branch}`,sha:main.object.sha})});for(const change of p.data.proposal.changes){const current=await gh(token,`/contents/${change.path}?ref=main`);await gh(token,`/contents/${change.path}`,{method:'PUT',body:JSON.stringify({message:'feat(agent): verified autonomous task',content:btoa(unescape(encodeURIComponent(change.content))),sha:current.sha,branch})});}const pr=await gh(token,'/pulls',{method:'POST',body:JSON.stringify({title:`Héctor OS agente: ${p.data.proposal.summary.slice(0,100)}`,head:branch,base:'main',body:`Trabajo ${p.data.jobId}\n\n${p.data.proposal.summary}\n\nVerificación: typecheck, tests y build exitosos.`})});await c.env.DB.batch([c.env.DB.prepare("UPDATE work_jobs SET status='completed',progress=100,result=?,heartbeat_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(`PR verificado: ${pr.html_url}`,p.data.jobId),c.env.DB.prepare("INSERT INTO work_events(id,job_id,message,progress) VALUES(?,?,?,100)").bind(crypto.randomUUID(),p.data.jobId,`PR publicado: ${pr.html_url}`)]);return c.json({published:true,branch,prUrl:pr.html_url});}catch(e){return c.json({error:e instanceof Error?e.message:'Error'},502);}});
