export type User={id:string;name:string};
async function request<T>(path:string,init?:RequestInit):Promise<T>{const res=await fetch(`/api${path}`,{...init,headers:{...(init?.body instanceof FormData?{}:{'Content-Type':'application/json'}),...init?.headers}});const data=await res.json().catch(()=>({}));if(!res.ok){const error=new Error(data.error||'Error de conexión') as Error&{data?:any};error.data=data;throw error}return data}
export const api={
 me:()=>request<{user:User}>('/auth/me'),login:(email:string,password:string)=>request<{user:User}>('/auth/login',{method:'POST',body:JSON.stringify({email,password})}),register:(name:string,email:string,password:string)=>request<{user:User}>('/auth/register',{method:'POST',body:JSON.stringify({name,email,password})}),logout:()=>request('/auth/logout',{method:'POST'}),
 dashboard:()=>request<any>('/dashboard'),conversations:()=>request<any>('/conversations'),conversationMessages:(id:string)=>request<any>(`/conversations/${id}/messages`),chat:(message:string,conversationId?:string)=>request<any>('/intelligence/chat',{method:'POST',body:JSON.stringify({message,conversationId})}),
 delegations:()=>request<any>('/delegations'),delegation:(id:string)=>request<any>(`/delegations/${id}`),createDelegation:(data:{sourceConversationId:string;target:string;instruction:string;maxIterations:number;stopOnSuccess?:boolean})=>request<any>('/delegations',{method:'POST',body:JSON.stringify(data)}),pauseDelegation:(id:string)=>request<any>(`/delegations/${id}/pause`,{method:'POST'}),resumeDelegation:(id:string)=>request<any>(`/delegations/${id}/resume`,{method:'POST'}),setConversationAlias:(conversationId:string,alias:string)=>request<any>(`/delegations/aliases/${conversationId}`,{method:'PUT',body:JSON.stringify({alias})}),
 projects:()=>request<any>('/projects'),project:(id:string)=>request<any>(`/projects/${id}`),projectTaskMessages:(projectId:string,taskId:string)=>request<any>(`/projects/${projectId}/tasks/${taskId}/messages`),createProjectFromMessage:(data:any)=>request<any>('/projects/from-message',{method:'POST',body:JSON.stringify(data)}),pauseProject:(id:string)=>request<any>(`/projects/${id}/pause`,{method:'POST'}),resumeProject:(id:string)=>request<any>(`/projects/${id}/resume`,{method:'POST'}),
 intelligenceStatus:()=>request<any>('/intelligence/status'),selfEvaluate:()=>request<any>('/intelligence/self-evaluate',{method:'POST'}),improvementPrompts:()=>request<any>('/intelligence/prompts'),markPromptSent:(id:string)=>request<any>(`/intelligence/prompts/${id}/sent`,{method:'POST'}),
 agentJobs:()=>request<any>('/agent/jobs'),agentJob:(id:string)=>request<any>(`/agent/jobs/${id}`),createAgentJob:(data:any)=>request<any>('/agent/jobs',{method:'POST',body:JSON.stringify(data)}),retryAgentJob:(id:string)=>request<any>(`/agent/jobs/${id}/retry`,{method:'POST'}),
 vision:(image:File,prompt:string)=>{const f=new FormData();f.append('image',image);f.append('prompt',prompt);return request<any>('/vision',{method:'POST',body:f})},usage:()=>request<any>('/usage'),assistantContext:()=>request<any>('/assistant/context'),assistantSkills:()=>request<any>('/assistant/skills'),assistantSettings:()=>request<any>('/assistant/settings'),saveAssistantSettings:(settings:any)=>request<any>('/assistant/settings',{method:'PUT',body:JSON.stringify(settings)}),requestUpdate:(requestText:string)=>request<any>('/assistant/updates',{method:'POST',body:JSON.stringify({request:requestText})}),
 factoryProjects:()=>request<any>('/factory/projects'),cloneApp:(name:string)=>request<any>('/factory/clone',{method:'POST',body:JSON.stringify({name})}),generatedApis:()=>request<any>('/api-factory/apis'),createGeneratedApi:(data:any)=>request<any>('/api-factory/apis',{method:'POST',body:JSON.stringify(data)}),
 workJobs:()=>request<any>('/work/jobs'),createWork:(data:any)=>request<any>('/work/jobs',{method:'POST',body:JSON.stringify(data)}),workJob:(id:string)=>request<any>(`/work/jobs/${id}`),trackAction:(action:string)=>request('/assistant/event',{method:'POST',body:JSON.stringify({action})}),
 memories:()=>request<any>('/memories'),addMemory:(content:string)=>request('/memories',{method:'POST',body:JSON.stringify({content,importance:3})}),removeMemory:(id:string)=>request(`/memories/${id}`,{method:'DELETE'}),files:()=>request<any>('/files'),upload:(file:File)=>{const f=new FormData();f.append('file',file);return request('/files',{method:'POST',body:f})}
};
