import {summarizeQualityProtectionImpact,type QualityImpactResponse,type QualityImpactSummary,type QualityImpactWindow} from './quality-impact-summary';

type AlertState='active'|'resolved';
type QualityAlert={id:string;task:string;state:AlertState;reason:string;triggers:string[];sampleCount:number;firstSeenAt:string;lastSeenAt:string;acknowledgedAt:string|null;mutedUntil:string|null;resolvedAt:string|null;muted:boolean};
type GovernanceMode='auto'|'frozen'|'excluded';
type Policy={category:string;strategy:'baseline'|'adaptive';status:string;governance_mode?:GovernanceMode;governance_reason?:string|null};
type GovernanceAction='freeze'|'unfreeze'|'include'|'manual_rollback';
export type QualityGovernanceProposal={action:GovernanceAction;label:string;title:string;detail:string;reason:string;warning:string|null};

const api=async<T>(path:string,init?:RequestInit):Promise<T>=>{const headers=new Headers(init?.headers);headers.set('Accept','application/json');if(init?.body)headers.set('Content-Type','application/json');const response=await fetch(path,{credentials:'include',...init,headers});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'No disponible');return data as T;};
const el=<K extends keyof HTMLElementTagNameMap>(tag:K,className?:string,text?:string)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
const date=(value:string|null)=>{if(!value)return'—';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'—':parsed.toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'});};
const pct=(value:number|null)=>value===null?'—':`${Math.round(value*100)}%`;
const score=(value:number|null)=>value===null?'—':value.toFixed(1);
const money=(value:number)=>`US$${value.toFixed(value<.01?4:3)}`;
export function activeVisibleAlerts(items:QualityAlert[],nowMs=Date.now()){return items.filter(item=>item.state==='active'&&(!item.mutedUntil||new Date(item.mutedUntil).getTime()<=nowMs));}
export function qualityImpactRecommendation(summary:QualityImpactSummary){switch(summary.verdict){case'effective':return'Mantener protección y revisar de nuevo cuando aumente la muestra.';case'recovered-reasonable-cost':return'Conservar protección hasta ejecutar una prueba controlada.';case'high-cost-no-proof':return'Volver a automático o probar Terra de forma controlada.';case'candidate-probe':return'Iniciar una prueba controlada antes de mantener Sol.';case'too-early':return'Esperar más evidencia antes de cambiar el gobierno.';default:return'Mantener el modo actual y seguir observando.';}}
export function qualityGovernanceProposal(summary:QualityImpactSummary,policy?:Policy):QualityGovernanceProposal|null{
 if(!policy||summary.verdict==='too-early'||summary.verdict==='inconclusive')return null;
 const mode=policy.governance_mode||'auto';
 if(summary.verdict==='effective'){
  if(mode==='frozen')return null;
  return{action:'freeze',label:'Mantener protección',title:'Congelar la estrategia actual',detail:`Mantendrá ${policy.strategy==='adaptive'?'la ruta adaptativa de alta calidad':'la estrategia actual'} para ${policy.category} y evitará cambios automáticos.`,reason:'Protección mantenida desde la evidencia de impacto en Ajustes',warning:'La estrategia permanecerá congelada hasta que Héctor la vuelva a Automático.'};
 }
 if(summary.verdict==='high-cost-no-proof'){
  if(mode==='frozen')return{action:'unfreeze',label:'Volver a automático',title:'Reactivar gobierno automático',detail:`Héctor OS volverá a decidir la estrategia de ${policy.category} con feedback, calidad y costo.`,reason:'Retorno a automático por costo alto sin mejora demostrable',warning:null};
  if(mode==='excluded')return{action:'include',label:'Volver a automático',title:'Reactivar la categoría',detail:`La categoría ${policy.category} volverá al gobierno automático y dejará de estar excluida.`,reason:'Reactivación por revisión del impacto de calidad',warning:null};
 }
 if(summary.verdict==='candidate-probe'||summary.verdict==='recovered-reasonable-cost'||summary.verdict==='high-cost-no-proof'){
  return{action:'manual_rollback',label:'Iniciar prueba controlada',title:'Probar la estrategia base',detail:`Cambiará ${policy.category} a la estrategia base y la congelará para observar calidad y costo sin cambios automáticos.`,reason:'Prueba controlada iniciada desde el análisis de impacto',warning:'La prueba no termina sola: al concluir, usa Volver a automático para reanudar la adaptación.'};
 }
 return null;
}
function findSettingsPage(){return[...document.querySelectorAll<HTMLElement>('.cxPage')].find(page=>page.querySelector('h1')?.textContent?.trim()==='Ajustes');}
function windowTable(before:QualityImpactWindow,protectedWindow:QualityImpactWindow){const table=el('div','cxQualityImpactWindows');for(const [label,value] of [['Muestras',`${before.sampleCount} / ${protectedWindow.sampleCount}`],['Aceptación',`${pct(before.acceptanceRate)} / ${pct(protectedWindow.acceptanceRate)}`],['Calidad',`${score(before.averageQualityScore)} / ${score(protectedWindow.averageQualityScore)}`],['Costo medio',`${money(before.averageCostUsd)} / ${money(protectedWindow.averageCostUsd)}`],['Rechazos',`${before.rejectedCount} / ${protectedWindow.rejectedCount}`],['Correcciones',`${before.corrections} / ${protectedWindow.corrections}`],['Uso profundo',`${pct(before.deepShare)} / ${pct(protectedWindow.deepShare)}`]] as const){const row=el('div');row.append(el('span',undefined,label),el('strong',undefined,value));table.append(row);}return table;}

export function installBudgetQualityAlertsEnhancer(){
 let mounted:HTMLElement|undefined,loadVersion=0;
 const render=async(root:HTMLElement)=>{
  if(root.dataset.qualityAlertsReady==='1')return;
  root.dataset.qualityAlertsReady='1';mounted=root;
  const section=el('section','cxQualityAlerts'),head=el('div','cxQualityAlertsHead'),copy=el('div'),badge=el('span','cxQualityAlertsBadge','Cargando'),list=el('div','cxQualityAlertsList'),notice=el('p','cxQualityAlertsNotice');
  copy.append(el('span',undefined,'Supervisión activa'),el('h2',undefined,'Alertas de calidad'),el('p',undefined,'Avisa cuando Héctor OS suspende el ahorro, mide el impacto y permite gobernar la estrategia con vista previa.'));
  head.append(copy,badge);section.append(head,list,notice);
  const act=async(id:string,action:'acknowledge'|'mute'|'unmute',button:HTMLButtonElement)=>{button.disabled=true;try{await api(`/api/intelligence/budget/quality-alerts/${id}/action`,{method:'POST',body:JSON.stringify({action,muteHours:24})});await load();}catch(error){notice.textContent=error instanceof Error?error.message:'No se pudo actualizar';notice.className='cxQualityAlertsNotice bad';}finally{button.disabled=false;}};
  const governancePreview=(proposal:QualityGovernanceProposal,policy:Policy,host:HTMLElement)=>{const preview=el('section','cxQualityGovPreview'),head=el('div','cxQualityGovPreviewHead'),actions=el('div','cxQualityGovPreviewActions'),confirm=el('button','primary','Aplicar cambio'),cancel=el('button',undefined,'Cancelar');head.append(el('strong',undefined,proposal.title),el('span',undefined,policy.governance_mode||'auto'));preview.append(head,el('p',undefined,proposal.detail));if(proposal.warning)preview.append(el('p','cxQualityGovWarning',proposal.warning));confirm.type='button';cancel.type='button';cancel.onclick=()=>preview.remove();confirm.onclick=async()=>{confirm.disabled=true;cancel.disabled=true;confirm.textContent='Aplicando…';try{await api(`/api/intelligence/benchmark/policies/${encodeURIComponent(policy.category)}/governance`,{method:'PUT',body:JSON.stringify({action:proposal.action,reason:proposal.reason})});notice.textContent=`Gobierno actualizado para ${policy.category}.`;notice.className='cxQualityAlertsNotice good';await load();}catch(error){confirm.disabled=false;cancel.disabled=false;confirm.textContent='Reintentar';const message=el('p','cxQualityGovError',error instanceof Error?error.message:'No se pudo aplicar');preview.append(message);}};actions.append(confirm,cancel);preview.append(actions);host.replaceChildren(preview);};
  const loadImpact=async(item:QualityAlert,policy:Policy|undefined,button:HTMLButtonElement,host:HTMLElement,version:number)=>{button.disabled=true;button.textContent='Analizando…';try{const data=await api<QualityImpactResponse>(`/api/intelligence/budget/quality-alerts/${item.id}/impact`);if(version!==loadVersion||!document.body.contains(host))return;const summary=summarizeQualityProtectionImpact(data),panel=el('section',`cxQualityImpact ${summary.tone}`),top=el('div','cxQualityImpactTop');top.append(el('strong',undefined,summary.title),el('span','cxQualityImpactConfidence',`Confianza ${data.impact.confidence}`));panel.append(top,el('p',undefined,summary.detail),windowTable(data.impact.before,data.impact.protected));const metrics=el('div','cxQualityImpactMetrics');summary.metrics.forEach(value=>metrics.append(el('span',undefined,value)));panel.append(metrics,el('p','cxQualityImpactRecommendation',qualityImpactRecommendation(summary)));if(data.impact.recoveryObserved)panel.append(el('small',undefined,`Recuperación observada en ${data.impact.recoveryHours??0} h · ${date(data.impact.recoveredAt)}`));const proposal=qualityGovernanceProposal(summary,policy);if(proposal){const governanceHost=el('div','cxQualityGovHost'),govern=el('button','cxQualityGovAction',proposal.label);govern.type='button';govern.onclick=()=>governancePreview(proposal,policy!,governanceHost);panel.append(govern,governanceHost);}else if(policy)panel.append(el('small','cxQualityGovCurrent',`Gobierno actual: ${policy.governance_mode||'auto'} · ${policy.strategy}`));host.replaceChildren(panel);button.textContent='Ocultar impacto';button.disabled=false;button.onclick=()=>{host.replaceChildren();button.textContent='Ver impacto';button.onclick=()=>void loadImpact(item,policy,button,host,loadVersion);};}catch(error){host.replaceChildren(el('p','cxQualityImpactError',error instanceof Error?error.message:'No se pudo calcular el impacto'));button.textContent='Reintentar impacto';button.disabled=false;}};
  const load=async()=>{const version=++loadVersion;try{const [alertsData,policiesData]=await Promise.all([api<{items:QualityAlert[]}>('/api/intelligence/budget/quality-alerts'),api<{items:Policy[]}>('/api/intelligence/benchmark/policies').catch(()=>({items:[]}))]);if(version!==loadVersion)return;const items=alertsData.items||[],policies=new Map((policiesData.items||[]).map(policy=>[policy.category,policy])),active=items.filter(x=>x.state==='active'),visible=activeVisibleAlerts(items);badge.textContent=active.length?`${active.length} activa${active.length===1?'':'s'}`:'Sin alertas';badge.className=`cxQualityAlertsBadge ${active.length?'bad':'good'}`;list.replaceChildren();if(!items.length)list.append(el('p','cxQualityAlertsMuted','Todavía no existen transiciones registradas.'));for(const item of items.slice(0,20)){const policy=policies.get(item.task),card=el('article',`cxQualityAlert ${item.state}`),top=el('div','cxQualityAlertTop'),title=el('div'),state=el('strong',item.state,item.state==='active'?'Protección activa':'Recuperada');title.append(el('strong',undefined,item.task),el('small',undefined,item.reason));top.append(title,state);const meta=el('p','cxQualityAlertMeta',`${item.sampleCount} muestras · vista ${date(item.firstSeenAt)} · última señal ${date(item.lastSeenAt)}`),controls=el('div','cxQualityAlertControls'),impactHost=el('div','cxQualityImpactHost'),impactButton=el('button',undefined,'Ver impacto');impactButton.type='button';impactButton.onclick=()=>void loadImpact(item,policy,impactButton,impactHost,version);controls.append(impactButton);if(item.state==='active'){if(!item.acknowledgedAt){const acknowledge=el('button',undefined,'Reconocer');acknowledge.type='button';acknowledge.onclick=()=>void act(item.id,'acknowledge',acknowledge);controls.append(acknowledge);}else controls.append(el('span','cxQualityAlertAck',`Reconocida ${date(item.acknowledgedAt)}`));const mute=el('button',undefined,item.muted?'Reactivar':'Silenciar 24 h');mute.type='button';mute.onclick=()=>void act(item.id,item.muted?'unmute':'mute',mute);controls.append(mute);}else controls.append(el('span','cxQualityAlertAck',`Resuelta ${date(item.resolvedAt)}`));card.append(top,meta,controls,impactHost);list.append(card);}notice.textContent=visible.length?`${visible.length} alerta${visible.length===1?'':'s'} requiere${visible.length===1?'':'n'} atención.`:active.length?'Las alertas activas están silenciadas temporalmente.':'La calidad no requiere intervención.';notice.className=`cxQualityAlertsNotice ${visible.length?'bad':'good'}`;}catch(error){if(version!==loadVersion)return;badge.textContent='No disponible';badge.className='cxQualityAlertsBadge bad';notice.textContent=error instanceof Error?error.message:'No se pudo cargar';notice.className='cxQualityAlertsNotice bad';}};
  const anchor=root.querySelector('.cxCognitiveBudget')||root.querySelector('.cxSelfModel')||root.querySelector('.cxStatus');anchor?.insertAdjacentElement('beforebegin',section);await load();
 };
 const scan=()=>{const page=findSettingsPage();if(page&&!page.dataset.qualityAlertsReady)void render(page);if(mounted&&!document.body.contains(mounted))mounted=undefined;};
 const observer=new MutationObserver(scan);observer.observe(document.body,{childList:true,subtree:true});scan();return()=>observer.disconnect();
}
