type AlertState='active'|'resolved';
type QualityAlert={id:string;task:string;state:AlertState;reason:string;triggers:string[];sampleCount:number;firstSeenAt:string;lastSeenAt:string;acknowledgedAt:string|null;mutedUntil:string|null;resolvedAt:string|null;muted:boolean};

const api=async<T>(path:string,init?:RequestInit):Promise<T>=>{const headers=new Headers(init?.headers);headers.set('Accept','application/json');if(init?.body)headers.set('Content-Type','application/json');const response=await fetch(path,{credentials:'include',...init,headers});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'No disponible');return data as T;};
const el=<K extends keyof HTMLElementTagNameMap>(tag:K,className?:string,text?:string)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
const date=(value:string|null)=>{if(!value)return'—';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'—':parsed.toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'});};
export function activeVisibleAlerts(items:QualityAlert[],nowMs=Date.now()){return items.filter(item=>item.state==='active'&&(!item.mutedUntil||new Date(item.mutedUntil).getTime()<=nowMs));}
function findSettingsPage(){return[...document.querySelectorAll<HTMLElement>('.cxPage')].find(page=>page.querySelector('h1')?.textContent?.trim()==='Ajustes');}

export function installBudgetQualityAlertsEnhancer(){
 let mounted:HTMLElement|undefined;
 const render=async(root:HTMLElement)=>{
  if(root.dataset.qualityAlertsReady==='1')return;
  root.dataset.qualityAlertsReady='1';mounted=root;
  const section=el('section','cxQualityAlerts'),head=el('div','cxQualityAlertsHead'),copy=el('div'),badge=el('span','cxQualityAlertsBadge','Cargando'),list=el('div','cxQualityAlertsList'),notice=el('p','cxQualityAlertsNotice');
  copy.append(el('span',undefined,'Supervisión activa'),el('h2',undefined,'Alertas de calidad'),el('p',undefined,'Avisa cuando Héctor OS suspende el ahorro y cierra la alerta al recuperarse.'));
  head.append(copy,badge);section.append(head,list,notice);
  const act=async(id:string,action:'acknowledge'|'mute'|'unmute',button:HTMLButtonElement)=>{button.disabled=true;try{await api(`/api/intelligence/budget/quality-alerts/${id}/action`,{method:'POST',body:JSON.stringify({action,muteHours:24})});await load();}catch(error){notice.textContent=error instanceof Error?error.message:'No se pudo actualizar';notice.className='cxQualityAlertsNotice bad';}finally{button.disabled=false;}};
  const load=async()=>{try{const data=await api<{items:QualityAlert[]}>('/api/intelligence/budget/quality-alerts'),items=data.items||[],active=items.filter(x=>x.state==='active'),visible=activeVisibleAlerts(items);badge.textContent=active.length?`${active.length} activa${active.length===1?'':'s'}`:'Sin alertas';badge.className=`cxQualityAlertsBadge ${active.length?'bad':'good'}`;list.replaceChildren();if(!items.length)list.append(el('p','cxQualityAlertsMuted','Todavía no existen transiciones registradas.'));for(const item of items.slice(0,20)){const card=el('article',`cxQualityAlert ${item.state}`),top=el('div','cxQualityAlertTop'),title=el('div'),state=el('strong',item.state,item.state==='active'?'Protección activa':'Recuperada');title.append(el('strong',undefined,item.task),el('small',undefined,item.reason));top.append(title,state);const meta=el('p','cxQualityAlertMeta',`${item.sampleCount} muestras · vista ${date(item.firstSeenAt)} · última señal ${date(item.lastSeenAt)}`),controls=el('div','cxQualityAlertControls');if(item.state==='active'){if(!item.acknowledgedAt){const acknowledge=el('button',undefined,'Reconocer');acknowledge.type='button';acknowledge.onclick=()=>void act(item.id,'acknowledge',acknowledge);controls.append(acknowledge);}else controls.append(el('span','cxQualityAlertAck',`Reconocida ${date(item.acknowledgedAt)}`));const mute=el('button',undefined,item.muted?'Reactivar':'Silenciar 24 h');mute.type='button';mute.onclick=()=>void act(item.id,item.muted?'unmute':'mute',mute);controls.append(mute);}else controls.append(el('span','cxQualityAlertAck',`Resuelta ${date(item.resolvedAt)}`));card.append(top,meta,controls);list.append(card);}notice.textContent=visible.length?`${visible.length} alerta${visible.length===1?'':'s'} requiere${visible.length===1?'':'n'} atención.`:active.length?'Las alertas activas están silenciadas temporalmente.':'La calidad no requiere intervención.';notice.className=`cxQualityAlertsNotice ${visible.length?'bad':'good'}`;}catch(error){badge.textContent='No disponible';badge.className='cxQualityAlertsBadge bad';notice.textContent=error instanceof Error?error.message:'No se pudo cargar';notice.className='cxQualityAlertsNotice bad';}};
  const anchor=root.querySelector('.cxCognitiveBudget')||root.querySelector('.cxSelfModel')||root.querySelector('.cxStatus');anchor?.insertAdjacentElement('beforebegin',section);await load();
 };
 const scan=()=>{const page=findSettingsPage();if(page&&!page.dataset.qualityAlertsReady)void render(page);if(mounted&&!document.body.contains(mounted))mounted=undefined;};
 const observer=new MutationObserver(scan);observer.observe(document.body,{childList:true,subtree:true});scan();return()=>observer.disconnect();
}
