export function cleanCopiedAnswer(value:string){return value.replace(/\n{3,}/g,'\n\n').trim();}

function answerText(container:HTMLElement){const clone=container.cloneNode(true) as HTMLElement;clone.querySelectorAll('.cxProvider,.cxMessageActions,.hxCopyAnswer').forEach(node=>node.remove());return cleanCopiedAnswer(clone.innerText||clone.textContent||'');}

async function copyText(value:string){if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(value);return;}const area=document.createElement('textarea');area.value=value;area.readOnly=true;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();const copied=document.execCommand('copy');area.remove();if(!copied)throw new Error('No se pudo copiar');}

function decorate(message:HTMLElement){if(message.dataset.copyReady==='1')return;const content=message.querySelector<HTMLElement>(':scope > div');if(!content)return;message.dataset.copyReady='1';const button=document.createElement('button');button.type='button';button.className='hxCopyAnswer';button.setAttribute('aria-label','Copiar respuesta');button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></svg><span>Copiar</span>';button.onclick=async()=>{const value=answerText(content);if(!value)return;button.disabled=true;try{await copyText(value);button.classList.add('copied');button.querySelector('span')!.textContent='Copiado';window.setTimeout(()=>{button.classList.remove('copied');button.querySelector('span')!.textContent='Copiar';},1800);}catch{button.classList.add('failed');button.querySelector('span')!.textContent='Error';window.setTimeout(()=>{button.classList.remove('failed');button.querySelector('span')!.textContent='Copiar';},1800);}finally{button.disabled=false;}};content.append(button);}

export function installChatCopyEnhancer(){const scan=()=>document.querySelectorAll<HTMLElement>('.cxMessage.assistant').forEach(decorate);const observer=new MutationObserver(scan);observer.observe(document.body,{childList:true,subtree:true});scan();return()=>observer.disconnect();}
