type Budget={dailyLimitUsd:number;monthlyLimitUsd:number;warnPercent:number;enforcementMode:'observe'|'protect';todayUsd:number;monthUsd:number;dailyPercent:number;monthlyPercent:number;warning:boolean;exceeded:boolean;state:'ok'|'warning'|'exceeded';remainingTodayUsd:number;remainingMonthUsd:number};
type Breakdown={model:string;service:string;costUsd:number;requests:number;inputUnits:number;cachedInputUnits:number;outputUnits:number};
type BudgetResponse={budget:Budget;policy:{ordinary:{action:string;reason:string};sensitive:{action:string;reason:string};explicitHigh:{action:string;reason:string}};breakdown:Breakdown[]};
const api=async<T>(path:string,init?:RequestInit):Promise<T>=>{const headers=new Headers(init?.headers);headers.set('Accept','application/json');if(init?.body)headers.set('Content-Type','application/json');const response=await fetch(path,{credentials:'include',...init,headers});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'No disponible');return data as T;};
const el=<K extends keyof HTMLElementTagNameMap>(tag:K,className?:string,text?:string)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:4,maximumFractionDigits:4}).format(Number(value)||0);
function findSettingsPage(){return[...document.querySelectorAll<HTMLElement>('.cxPage')].find(page=>page.querySelector('h1')?.textContent?.trim()==='Ajustes');}
function metric(label:string,value:string,detail?:string){const node=el('div','cxBudgetMetric');node.append(el('span',undefined,label),el('strong',undefined,value));if(detail)node.append(el('small',undefined,detail));return node;}
export function installCognitiveBudgetEnhancer(){let mounted:HTMLElement|undefined;
 const render=async(root:HTMLElement)=>{if(root.dataset.cognitiveBudgetReady==='1')return;root.dataset.cognitiveBudgetReady='1';mounted=root;
  const section=el('section','cxCognitiveBudget'),head=el('div','cxBudgetHead'),copy=el('div');copy.append(el('span',undefined,'Control de costo'),el('h2',undefined,'Presupuesto cognitivo'),el('p',undefined,'Define límites, observa el consumo real y decide cuándo Héctor OS debe proteger el gasto.'));
  const badge=el('span','cxBudgetBadge','Cargando');head.append(copy,badge);
  const metrics=el('div','cxBudgetMetrics'),form=el('form','cxBudgetForm'),table=el('div','cxBudgetBreakdown'),notice=el('p','cxBudgetNotice');section.append(head,metrics,form,table,notice);
  const daily=document.createElement('input'),monthly=document.createElement('input'),warn=document.createElement('input'),mode=document.createElement('select'),save=el('button',undefined,'Guardar presupuesto');
  daily.type=monthly.type=warn.type='number';daily.min=monthly.min='0';daily.step=monthly.step='0.01';warn.min='1';warn.max='100';warn.step='1';
  mode.append(new Option('Solo observar','observe'),new Option('Proteger al exceder','protect'));save.type='submit';
  const field=(label:string,input:HTMLElement)=>{const wrap=el('label');wrap.append(el('span',undefined,label),input);return wrap;};
  form.append(field('Límite diario USD',daily),field('Límite mensual USD',monthly),field('Avisar al %',warn),field('Modo',mode),save);
  const load=async()=>{try{const data=await api<BudgetResponse>('/api/intelligence/budget');const b=data.budget;badge.textContent=b.state==='exceeded'?'Excedido':b.state==='warning'?'Advertencia':'Disponible';badge.className=`cxBudgetBadge ${b.state}`;daily.value=String(b.dailyLimitUsd);monthly.value=String(b.monthlyLimitUsd);warn.value=String(b.warnPercent);mode.value=b.enforcementMode;metrics.replaceChildren(metric('Hoy',money(b.todayUsd),`${b.dailyPercent}% de ${money(b.dailyLimitUsd)}`),metric('Mes',money(b.monthUsd),`${b.monthlyPercent}% de ${money(b.monthlyLimitUsd)}`),metric('Disponible hoy',money(b.remainingTodayUsd)),metric('Política ordinaria',data.policy.ordinary.action,data.policy.ordinary.reason));table.replaceChildren(el('h3',undefined,'Consumo de los últimos 30 días'));if(!data.breakdown.length)table.append(el('p','cxBudgetMuted','Todavía no hay consumo registrado.'));else{for(const item of data.breakdown){const row=el('div','cxBudgetRow');row.append(el('div',undefined,`${item.model} · ${item.service}`),el('span',undefined,`${item.requests} solicitudes`),el('strong',undefined,money(item.costUsd)));table.append(row);}}notice.textContent=b.enforcementMode==='protect'?'La protección está habilitada. Las tareas sensibles y el razonamiento alto explícito nunca se degradan automáticamente.':'Modo observación: se registran alertas, pero el router todavía no cambia de modelo.';notice.className='cxBudgetNotice good';}catch(error){badge.textContent='No disponible';badge.className='cxBudgetBadge bad';notice.textContent=error instanceof Error?error.message:'No se pudo cargar el presupuesto';notice.className='cxBudgetNotice bad';}};
  form.onsubmit=async event=>{event.preventDefault();save.disabled=true;notice.textContent='Guardando…';try{await api('/api/intelligence/budget',{method:'PUT',body:JSON.stringify({dailyLimitUsd:Number(daily.value),monthlyLimitUsd:Number(monthly.value),warnPercent:Number(warn.value),enforcementMode:mode.value})});await load();}catch(error){notice.textContent=error instanceof Error?error.message:'No se pudo guardar';notice.className='cxBudgetNotice bad';}finally{save.disabled=false;}};
  const anchor=root.querySelector('.cxSelfModel')||root.querySelector('.cxIntelligenceStatus')||root.querySelector('.cxStatus');anchor?.insertAdjacentElement('afterend',section);await load();
 };
 const scan=()=>{const page=findSettingsPage();if(page&&!page.dataset.cognitiveBudgetReady)void render(page);if(mounted&&!document.body.contains(mounted))mounted=undefined;};const observer=new MutationObserver(scan);observer.observe(document.body,{childList:true,subtree:true});scan();return()=>observer.disconnect();}
