export type NotificationSeverity='info'|'warning'|'critical';
export type OperationalNotification={key:string;source:'quality'|'budget'|'work'|'runner';severity:NotificationSeverity;title:string;message:string;action:string;createdAt?:string|null};
export type NotificationSummary={total:number;critical:number;warning:number;info:number};
export type NotificationFilter='all'|NotificationSeverity;

const api=async<T>(path:string,init?:RequestInit):Promise<T>=>{const headers=new Headers(init?.headers);headers.set('Accept','application/json');if(init?.body)headers.set('Content-Type','application/json');const response=await fetch(path,{credentials:'include',...init,headers});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error((data as any).error||'No disponible');return data as T;};
const el=<K extends keyof HTMLElementTagNameMap>(tag:K,className?:string,text?:string)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
const severityRank:Record<NotificationSeverity,number>={critical:3,warning:2,info:1};

export function filterNotifications(items:OperationalNotification[],filter:NotificationFilter){return filter==='all'?items:items.filter(item=>item.severity===filter);}
export function sortNotifications(items:OperationalNotification[]){return [...items].sort((a,b)=>severityRank[b.severity]-severityRank[a.severity]||new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime());}
export function notificationDestination(item:OperationalNotification){if(item.source==='work'||item.source==='runner')return'Trabajo';return'Ajustes';}
export function badgeLabel(summary:NotificationSummary){if(!summary.total)return'Operación estable';if(summary.critical)return`Operación ${summary.critical} crítica${summary.critical===1?'':'s'}`;return`Operación ${summary.total}`;}

function navButton(label:string){return[...document.querySelectorAll<HTMLButtonElement>('.cxSidebar nav button')].find(button=>button.textContent?.includes(label));}
function navigate(item:OperationalNotification){navButton(notificationDestination(item))?.click();}

export function installOperationalNotificationCenter(){
 let trigger:HTMLButtonElement|undefined,backdrop:HTMLElement|undefined,panel:HTMLElement|undefined,list:HTMLElement|undefined,stats:HTMLElement|undefined,notice:HTMLElement|undefined,timer:number|undefined,filter:NotificationFilter='all',items:OperationalNotification[]=[];
 const setNotice=(text:string,state='' as ''|'good'|'bad')=>{if(!notice)return;notice.className=`hxOpsNotice ${state}`;notice.textContent=text;};
 const close=()=>{backdrop?.classList.remove('open');trigger?.setAttribute('aria-expanded','false');document.body.classList.remove('hxOpsOpen');};
 const open=()=>{backdrop?.classList.add('open');trigger?.setAttribute('aria-expanded','true');document.body.classList.add('hxOpsOpen');void load();panel?.focus();};
 const act=async(item:OperationalNotification,action:'acknowledge'|'mute')=>{try{await api(`/api/notifications/${encodeURIComponent(item.key)}/action`,{method:'POST',body:JSON.stringify({action,...(action==='mute'?{muteHours:24}:{})})});setNotice(action==='acknowledge'?'Notificación reconocida.':'Notificación silenciada durante 24 horas.','good');await load();}catch(error){setNotice(error instanceof Error?error.message:'No se pudo actualizar','bad');}};
 const render=()=>{if(!list||!stats)return;const ordered=sortNotifications(items),visible=filterNotifications(ordered,filter);stats.replaceChildren();const summary={total:items.length,critical:items.filter(x=>x.severity==='critical').length,warning:items.filter(x=>x.severity==='warning').length,info:items.filter(x=>x.severity==='info').length};[['Total',summary.total],['Críticas',summary.critical],['Avisos',summary.warning],['Info',summary.info]].forEach(([label,value])=>{const box=el('button','hxOpsStat');box.type='button';box.append(el('span',undefined,String(label)),el('strong',undefined,String(value)));box.onclick=()=>{filter=label==='Críticas'?'critical':label==='Avisos'?'warning':label==='Info'?'info':'all';render();};stats!.append(box);});list.replaceChildren();if(!visible.length){list.append(el('div','hxOpsEmpty',items.length?'No hay notificaciones con este filtro.':'No hay incidentes operativos pendientes.'));return;}for(const item of visible){const card=el('article',`hxOpsCard ${item.severity}`),head=el('header'),copy=el('div');copy.append(el('span',undefined,item.source),el('h3',undefined,item.title));head.append(copy,el('strong','hxOpsSeverity',item.severity));card.append(head,el('p',undefined,item.message));const actions=el('div','hxOpsActions'),openButton=el('button',undefined,item.action||`Abrir ${notificationDestination(item)}`),ack=el('button',undefined,'Reconocer'),mute=el('button',undefined,'Silenciar 24 h');for(const button of [openButton,ack,mute])button.type='button';openButton.onclick=()=>{navigate(item);close();};ack.onclick=()=>void act(item,'acknowledge');mute.onclick=()=>void act(item,'mute');actions.append(openButton,ack,mute);card.append(actions);list.append(card);}};
 const load=async()=>{if(!trigger)return;try{const data=await api<{items:OperationalNotification[];summary:NotificationSummary}>('/api/notifications');items=data.items||[];trigger.textContent=badgeLabel(data.summary);trigger.classList.toggle('critical',data.summary.critical>0);trigger.classList.toggle('active',data.summary.total>0);trigger.setAttribute('aria-label',data.summary.total?`${data.summary.total} notificaciones operativas pendientes`:'Operación estable');render();}catch{trigger.textContent='Operación —';trigger.classList.remove('active','critical');}};
 const mount=()=>{const top=document.querySelector<HTMLElement>('.cxSidebarTop');if(!top)return false;if(!trigger){trigger=el('button','hxOpsTrigger','Operación estable');trigger.type='button';trigger.setAttribute('aria-haspopup','dialog');trigger.setAttribute('aria-expanded','false');trigger.onclick=open;top.append(trigger);}if(!backdrop){backdrop=el('div','hxOpsBackdrop');backdrop.onclick=event=>{if(event.target===backdrop)close();};panel=el('section','hxOpsPanel');panel.tabIndex=-1;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','Centro de notificaciones operativas');const head=el('header','hxOpsHead'),copy=el('div');copy.append(el('span',undefined,'Sistema'),el('h2',undefined,'Notificaciones operativas'),el('p',undefined,'Calidad, presupuesto, trabajos y runner en una sola bandeja.'));const closeButton=el('button',undefined,'Cerrar');closeButton.type='button';closeButton.onclick=close;head.append(copy,closeButton);stats=el('div','hxOpsStats');notice=el('p','hxOpsNotice');list=el('div','hxOpsList');panel.append(head,stats,notice,list);backdrop.append(panel);document.body.append(backdrop);document.addEventListener('keydown',event=>{if(event.key==='Escape')close();});}return true;};
 const scan=()=>{if(mount()&&!timer){void load();timer=window.setInterval(load,30000);}};const observer=new MutationObserver(scan);observer.observe(document.body,{childList:true,subtree:true});scan();return()=>{observer.disconnect();if(timer)window.clearInterval(timer);trigger?.remove();backdrop?.remove();};
}
