type Incident={id:string;task:string;model:string;costUsd:number;createdAt:string;planHash:string;planVersion:string;status:'active'|'acknowledged'|'recovery-requested'|'retrying'|'recovered'|'retry-failed';cause:string;summary:string;differences:string[];recoveryPrompt:string;retryAvailable:boolean;lastActionAt:string|null};
type Containment={cause:string;status:'healthy'|'watching'|'contained'|'probe-ready';incidents:number;active:number;recovered:number;retryFailed:number;nextProbeAt:string|null;reason:string};

const api=async<T>(path:string,init?:RequestInit):Promise<T>=>{const headers=new Headers(init?.headers);headers.set('Accept','application/json');if(init?.body)headers.set('Content-Type','application/json');const response=await fetch(path,{credentials:'include',...init,headers});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'No disponible');return data as T;};
function composer(){return document.querySelector<HTMLFormElement>('.cxComposer');}
function textArea(){return document.querySelector<HTMLTextAreaElement>('.cxComposer textarea');}
function formatProbe(value:string|null){if(!value)return'';const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleString('es-MX',{dateStyle:'short',timeStyle:'short'});}

export function installPlanDriftIncidentAlert(){
 let form:HTMLFormElement|undefined,strip:HTMLElement|undefined,timer:number|undefined,version=0;
 const remove=()=>{strip?.remove();strip=undefined;};
 const action=async(incident:Incident,kind:'acknowledged'|'recovery-requested',button:HTMLButtonElement)=>{button.disabled=true;try{await api(`/api/intelligence/plan-incidents/${incident.id}/action`,{method:'POST',body:JSON.stringify({action:kind,reason:kind==='acknowledged'?'Incidente revisado desde el chat':'Recuperación solicitada desde el chat'})});if(kind==='recovery-requested'){const input=textArea();if(input){input.value=incident.recoveryPrompt;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();}}await load();}catch{button.disabled=false;}};
 const retry=async(incident:Incident,button:HTMLButtonElement,status:HTMLElement)=>{button.disabled=true;status.textContent='Reintentando con el plan original…';try{await api(`/api/intelligence/plan-incidents/${incident.id}/retry`,{method:'POST',body:JSON.stringify({reason:'Reintento automático solicitado desde la alerta del chat'})});status.textContent='Recuperación completada. Actualizando conversación…';window.setTimeout(()=>location.reload(),600);}catch(error){status.textContent=error instanceof Error?error.message:'No se pudo recuperar';button.disabled=false;await load();}};
 const render=(items:Incident[],containment:Containment[])=>{if(!form)return;const incident=items.find(item=>item.status==='active'||item.status==='retry-failed'||item.status==='retrying');if(!incident){remove();return;}if(!strip){strip=document.createElement('aside');strip.className='cxPlanDriftIncident';strip.setAttribute('role','alert');form.insertAdjacentElement('beforebegin',strip);}strip.replaceChildren();const copy=document.createElement('div'),title=document.createElement('strong'),summary=document.createElement('span'),detail=document.createElement('small'),status=document.createElement('small'),actions=document.createElement('div'),retryNow=document.createElement('button'),recover=document.createElement('button'),ack=document.createElement('button'),group=containment.find(item=>item.cause===incident.cause);title.textContent=`Ejecución bloqueada: ${incident.task}`;summary.textContent=incident.summary;detail.textContent=`Causa: ${incident.cause} · plan ${incident.planHash.slice(0,12)} · ${incident.differences.join(' · ')}`;status.className='cxPlanDriftStatus';status.setAttribute('aria-live','polite');if(group?.status==='contained')status.textContent=`Contención recomendada: ${group.incidents} fallos en 24 h. Próxima prueba ${formatProbe(group.nextProbeAt)}.`;else if(group?.status==='probe-ready')status.textContent=`El enfriamiento terminó; ${incident.cause} está listo para una prueba controlada.`;else if(group?.status==='watching')status.textContent=`Causa bajo observación: ${group.incidents} desviaciones recientes.`;else if(incident.status==='retrying')status.textContent='Reintento en curso…';else if(incident.status==='retry-failed')status.textContent='El último reintento falló; puedes volver a intentarlo.';retryNow.type=recover.type=ack.type='button';retryNow.textContent='Reintentar ahora';recover.textContent='Preparar manual';ack.textContent='Marcar revisado';retryNow.disabled=!incident.retryAvailable||incident.status==='retrying';retryNow.title=incident.retryAvailable?'Ejecutar el mensaje original con el plan validado':'Los incidentes anteriores no conservan el plan completo';retryNow.onclick=()=>void retry(incident,retryNow,status);recover.onclick=()=>void action(incident,'recovery-requested',recover);ack.onclick=()=>void action(incident,'acknowledged',ack);actions.className='cxPlanDriftActions';actions.append(retryNow,recover,ack);copy.append(title,summary,detail,status);strip.append(copy,actions);};
 const load=async()=>{const current=++version;try{const response=await api<{items:Incident[];containment:Containment[]}>('/api/intelligence/plan-incidents');if(current===version)render(response.items||[],response.containment||[]);}catch{if(current===version)remove();}};
 const mount=(next:HTMLFormElement)=>{form=next;void load();if(timer)window.clearInterval(timer);timer=window.setInterval(()=>{if(form&&document.body.contains(form))void load();},15000);};
 const scan=()=>{const next=composer();if(next&&next!==form)mount(next);if(form&&!document.body.contains(form)){form=undefined;remove();if(timer)window.clearInterval(timer);timer=undefined;}};
 const observer=new MutationObserver(scan);observer.observe(document.body,{childList:true,subtree:true});scan();return()=>{observer.disconnect();remove();if(timer)window.clearInterval(timer);};
}
