type Incident={id:string;task:string;model:string;costUsd:number;createdAt:string;planHash:string;planVersion:string;status:'active'|'acknowledged'|'recovery-requested';cause:string;summary:string;differences:string[];recoveryPrompt:string};

const api=async<T>(path:string,init?:RequestInit):Promise<T>=>{const headers=new Headers(init?.headers);headers.set('Accept','application/json');if(init?.body)headers.set('Content-Type','application/json');const response=await fetch(path,{credentials:'include',...init,headers});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'No disponible');return data as T;};
function composer(){return document.querySelector<HTMLFormElement>('.cxComposer');}
function textArea(){return document.querySelector<HTMLTextAreaElement>('.cxComposer textarea');}

export function installPlanDriftIncidentAlert(){
 let form:HTMLFormElement|undefined,strip:HTMLElement|undefined,timer:number|undefined,version=0;
 const remove=()=>{strip?.remove();strip=undefined;};
 const action=async(incident:Incident,kind:'acknowledged'|'recovery-requested',button:HTMLButtonElement)=>{button.disabled=true;try{await api(`/api/intelligence/plan-incidents/${incident.id}/action`,{method:'POST',body:JSON.stringify({action:kind,reason:kind==='acknowledged'?'Incidente revisado desde el chat':'Recuperación solicitada desde el chat'})});if(kind==='recovery-requested'){const input=textArea();if(input){input.value=incident.recoveryPrompt;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();}}await load();}catch{button.disabled=false;}};
 const render=(items:Incident[])=>{if(!form)return;const incident=items.find(item=>item.status==='active');if(!incident){remove();return;}if(!strip){strip=document.createElement('aside');strip.className='cxPlanDriftIncident';strip.setAttribute('role','alert');form.insertAdjacentElement('beforebegin',strip);}strip.replaceChildren();const copy=document.createElement('div'),title=document.createElement('strong'),summary=document.createElement('span'),detail=document.createElement('small'),actions=document.createElement('div'),recover=document.createElement('button'),ack=document.createElement('button');title.textContent=`Ejecución bloqueada: ${incident.task}`;summary.textContent=incident.summary;detail.textContent=`Causa: ${incident.cause} · plan ${incident.planHash.slice(0,12)} · ${incident.differences.join(' · ')}`;recover.type=ack.type='button';recover.textContent='Preparar reintento';ack.textContent='Marcar revisado';recover.onclick=()=>void action(incident,'recovery-requested',recover);ack.onclick=()=>void action(incident,'acknowledged',ack);actions.className='cxPlanDriftActions';actions.append(recover,ack);copy.append(title,summary,detail);strip.append(copy,actions);};
 const load=async()=>{const current=++version;try{const response=await api<{items:Incident[]}>('/api/intelligence/plan-incidents');if(current===version)render(response.items||[]);}catch{if(current===version)remove();}};
 const mount=(next:HTMLFormElement)=>{form=next;void load();if(timer)window.clearInterval(timer);timer=window.setInterval(()=>{if(form&&document.body.contains(form))void load();},30000);};
 const scan=()=>{const next=composer();if(next&&next!==form)mount(next);if(form&&!document.body.contains(form)){form=undefined;remove();if(timer)window.clearInterval(timer);timer=undefined;}};
 const observer=new MutationObserver(scan);observer.observe(document.body,{childList:true,subtree:true});scan();return()=>{observer.disconnect();remove();if(timer)window.clearInterval(timer);};
}
