import {describe,expect,it} from 'vitest';
import {summarizeQualityProtectionImpact,type QualityImpactResponse} from './quality-impact-summary';

const base:QualityImpactResponse={alert:{id:'a1',task:'consulta general',state:'active',firstSeenAt:'2026-07-21T00:00:00Z',resolvedAt:null},impact:{before:{sampleCount:10,averageCostUsd:.01,acceptanceRate:.6,averageQualityScore:70,rejectedCount:4,negativeRatings:1,corrections:1,deepShare:.2},protected:{sampleCount:10,averageCostUsd:.02,acceptanceRate:.9,averageQualityScore:88,rejectedCount:1,negativeRatings:0,corrections:0,deepShare:.8},costDeltaUsd:.1,costDeltaPerResponseUsd:.01,acceptanceRateDelta:.3,qualityScoreDelta:18,estimatedErrorsAvoided:3,recoveryObserved:false,recoveredAt:null,recoveryHours:null,confidence:'medium'}};

describe('summarizeQualityProtectionImpact',()=>{
 it('no fabrica conclusiones cuando faltan muestras',()=>{const result=summarizeQualityProtectionImpact({...base,impact:{...base.impact,before:{...base.impact.before,sampleCount:2},protected:{...base.impact.protected,sampleCount:3},confidence:'insufficient',acceptanceRateDelta:null,qualityScoreDelta:null,costDeltaPerResponseUsd:null,estimatedErrorsAvoided:null}});expect(result.verdict).toBe('too-early');expect(result.title).toContain('Demasiado pronto');});
 it('reconoce una protección efectiva',()=>{const result=summarizeQualityProtectionImpact(base);expect(result.verdict).toBe('effective');expect(result.title).toBe('Protección efectiva');expect(result.metrics.join(' ')).toContain('+30 pp');});
 it('detecta costo alto sin mejora',()=>{const result=summarizeQualityProtectionImpact({...base,impact:{...base.impact,costDeltaPerResponseUsd:.03,acceptanceRateDelta:-.1,qualityScoreDelta:-4,estimatedErrorsAvoided:0}});expect(result.verdict).toBe('high-cost-no-proof');expect(result.tone).toBe('warning');});
 it('recomienda prueba cuando la categoría ya se recuperó',()=>{const result=summarizeQualityProtectionImpact({...base,alert:{...base.alert,state:'resolved',resolvedAt:'2026-07-21T12:00:00Z'},impact:{...base.impact,acceptanceRateDelta:.02,qualityScoreDelta:1,estimatedErrorsAvoided:0,recoveryObserved:true,recoveredAt:'2026-07-21T12:00:00Z',recoveryHours:12}});expect(result.verdict).toBe('candidate-probe');});
 it('destaca recuperación con costo razonable',()=>{const result=summarizeQualityProtectionImpact({...base,alert:{...base.alert,state:'resolved',resolvedAt:'2026-07-21T12:00:00Z'},impact:{...base.impact,recoveryObserved:true,recoveredAt:'2026-07-21T12:00:00Z',recoveryHours:12}});expect(result.verdict).toBe('recovered-reasonable-cost');expect(result.detail).toContain('12 h');});
});
