type Policy={category:string;strategy:'baseline'|'adaptive';status:string;sample_count:number;adaptive_win_rate:number;average_score_delta:number;average_cost_multiplier:number;reason:string;governance_mode?:'auto'|'frozen'|'excluded';governance_reason?:string|null};
type EventItem={id:string;category:string;action:string;strategy:string;status:string;reason:string;created_at:string};
const el=<K extends keyof HTMLElementTagNameMap>(tag:K,className?:string,text?:string)=>{const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n;};
async function api<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(path,{credentials:'include',...init,headers:{Accept:'application/json',...(init?.body?{'Content-Type':'application/json'}:{}),...(init?.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No disponible');return d as T;}
function findSettings(){return[...document.querySelectorAll<HTMLElement>('.cxPage')].find(x=>x.querySelector('h1')?.textContent?.trim()==='Ajustes');}
const pct=(v:number)=>`${Math.round(Number(v||0)*100)}%`;
export function installStrategyGovernanceEnhancer(){let root:HTMLElement|undefined,timer:number|undefined;const mount=async(page:HTMLElement)=>{if(page.dataset.strategyGovernanceReady==='1')return;page.dataset.strategyGovernanceReady='1';root=page;const section=el('section','cxStrategyGov'),head=el('div','cxStrategyGovHead');head.append(el('div',undefined,'Gobierno de inteligencia'),el('span',undefined,'Control humano'));const list=el('div','cxStrategyGovList'),history=el('details','cxStrategyGovHistory'),summary=el('summary',undefined,'Historial de decisiones'),events=el('div');history.append(summary,events);section.append(head,list,history);(page.querySelector('.cxIntelligenceStatus')||page.querySelector('.cxMemoryControl')||page.querySelector('.cxStatus'))?.insertAdjacentElement('afterend',section);
 const act=async(policy:Policy,action:string)=>{const reason=prompt('Motivo de la decisión:','Control manual desde Ajustes');if(!reason)return;await api(`/api/intelligence/benchmark/policies/${encodeURIComponent(policy.category)}/governance`,{method:'PUT',body:JSON.stringify({action,reason})});await load();};
 const load=async()=>{try{const data=await api<{items:Policy[];events:EventItem[]}>('/api/intelligence/benchmark/policies');list.replaceChildren();if(!data.items.length){list.append(el('p','cxStrategyGovEmpty','Aún no hay categorías evaluadas. Ejecuta benchmarks para generar políticas.'));}for(const p of data.items){const card=el('article','cxStrategyGovCard'),top=el('div','cxStrategyGovTop'),title=el('div');title.append(el('strong',undefined,p.category),el('small',undefined,`${p.strategy} · ${p.status}`));const mode=el('span',`mode ${p.governance_mode||'auto'}`,p.governance_mode||'auto');top.append(title,mode);const metrics=el('div','cxStrategyGovMetrics');for(const [k,v] of [['Muestras',p.sample_count],['Victorias',pct(p.adaptive_win_rate)],['Δ calidad',Number(p.average_score_delta||0).toFixed(1)],['Costo',`${Number(p.average_cost_multiplier||1).toFixed(1)}×`]]){const x=el('div');x.append(el('span',undefined,String(k)),el('b',undefined,String(v)));metrics.append(x);}const reason=el('p','cxStrategyGovReason',p.governance_reason||p.reason),actions=el('div','cxStrategyGovActions');const buttons:(readonly [string,string])[]=(p.governance_mode==='frozen'?[['Automático','unfreeze']]:p.governance_mode==='excluded'?[['Reactivar','include']]:[['Congelar','freeze'],['Excluir','exclude'],['Rollback','manual_rollback']]);for(const [label,action] of buttons){const b=el('button',action,label);b.type='button';b.onclick=()=>void act(p,action);actions.append(b);}card.append(top,metrics,reason,actions);list.append(card);}events.replaceChildren();for(const e of data.events.slice(0,12)){const row=el('div','cxStrategyGovEvent');row.append(el('strong',undefined,e.category),el('span',undefined,`${e.action} · ${e.reason}`));events.append(row);}}catch(err){list.replaceChildren(el('p','cxStrategyGovError',err instanceof Error?err.message:'No disponible'));}};await load();timer=window.setInterval(load,30000);};const scan=()=>{const page=findSettings();if(page&&!page.dataset.strategyGovernanceReady)void mount(page);if(root&&!document.body.contains(root)){root=undefined;if(timer)clearInterval(timer);timer=undefined;}};const o=new MutationObserver(scan);o.observe(document.body,{childList:true,subtree:true});scan();return()=>{o.disconnect();if(timer)clearInterval(timer);};}
