type WorkItem={id:string;title:string;prompt:string;status:string;progress:number;result?:string|null;last_error?:string|null;next_retry_at?:string|null;attempt_count:number;created_at:string;updated_at:string};
type WorkDetail={job:WorkItem;events:Array<{id:string;message:string;progress:number;created_at:string}>};

const request=async<T>(path:string,init?:RequestInit):Promise<T>=>{const headers=new Headers(init?.headers);headers.set('Accept','application/json');if(init?.body)headers.set('Content-Type','application/json');const response=await fetch(path,{credentials:'include',...init,headers});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'No disponible');return data as T;};
const el=<K extends keyof HTMLElementTagNameMap>(tag:K,className?:string,text?:string)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
const workPage=()=>[...document.querySelectorAll<HTMLElement>('.cxPage')].find(page=>page.querySelector('h1')?.textContent?.trim()==='Trabajo');
function date(value:string|null|undefined){if(!value)return'—';const normalized=value.includes('T')?value:`${value.replace(' ','T')}Z`,parsed=new Date(normalized);return Number.isNaN(parsed.getTime())?'—':parsed.toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'});}
function state(item:WorkItem){if(item.status==='working')return['Trabajando','working'];if(item.status==='completed')return['Completado','completed'];if(item.status==='blocked')return[item.last_error==='Pausado por el usuario'?'Pausado':'Necesita reanudarse','blocked'];if(item.status==='queued'&&item.next_retry_at&&Date.parse(item.next_retry_at)>Date.now())return['En espera','waiting'];return['Preparándose','queued'];}
const active=(status:string)=>['queued','working','testing','repairing'].includes(status);

export function installWorkModeEnhancer(){
 let root:HTMLElement|undefined,list:HTMLElement|undefined,detail:HTMLElement|undefined,notice:HTMLElement|undefined,timer:number|undefined,selected:string|undefined;
 const loadDetail=async(id:string)=>{if(!detail)return;selected=id;detail.replaceChildren(el('div','hxWorkLoading','Cargando actividad…'));try{const data=await request<WorkDetail>(`/api/work-mode/${id}`),item=data.job,[label,tone]=state(item);const head=el('header','hxWorkDetailHead'),copy=el('div');copy.append(el('span',undefined,label),el('h3',undefined,item.title));head.append(copy,el('strong',tone,`${Math.max(0,Math.min(100,Number(item.progress)||0))}%`));const goal=el('p','hxWorkGoal',item.prompt),result=el('section','hxWorkResult');result.append(el('h4',undefined,'Último avance'),el('p',undefined,item.result||item.last_error||'El primer ciclo todavía no termina.'));const events=el('section','hxWorkEvents');events.append(el('h4',undefined,'Actividad'));for(const event of data.events){const row=el('div');row.append(el('span',undefined,date(event.created_at)),el('p',undefined,event.message));events.append(row);}detail.replaceChildren(head,goal,result,events);const controls=el('div','hxWorkControls');if(active(item.status)){const pause=el('button','hxWorkPause','Pausar trabajo');pause.type='button';pause.onclick=async()=>{if(!window.confirm(`¿Pausar “${item.title}”? Podrás reanudarlo después.`))return;pause.disabled=true;try{await request(`/api/work-mode/${item.id}/pause`,{method:'POST'});notice!.className='hxWorkNotice good';notice!.textContent='Trabajo pausado. Conserva su progreso y puedes reanudarlo cuando quieras.';await load();await loadDetail(item.id);}catch(error){notice!.className='hxWorkNotice bad';notice!.textContent=error instanceof Error?error.message:'No se pudo pausar';}finally{pause.disabled=false;}};controls.append(pause);}else if(item.status==='blocked'||item.status==='completed'){const resume=el('button','hxWorkResume',item.last_error==='Pausado por el usuario'?'Reanudar trabajo':'Reanudar y buscar otra alternativa');resume.type='button';resume.onclick=async()=>{resume.disabled=true;try{await request(`/api/work-mode/${item.id}/resume`,{method:'POST'});notice!.className='hxWorkNotice good';notice!.textContent='Trabajo reanudado.';await load();await loadDetail(item.id);}catch(error){notice!.className='hxWorkNotice bad';notice!.textContent=error instanceof Error?error.message:'No se pudo reanudar';}finally{resume.disabled=false;}};controls.append(resume);}if(controls.childElementCount)detail.append(controls);}catch(error){detail.replaceChildren(el('div','hxWorkError',error instanceof Error?error.message:'No se pudo abrir el trabajo'));}};
 const load=async()=>{if(!list)return;try{const response=await request<{items:WorkItem[]}>('/api/work-mode'),items=response.items||[];list.replaceChildren();if(!items.length){list.append(el('div','hxWorkEmpty','Activa el Modo Trabajo con una meta. Héctor OS continuará por ciclos hasta verificarla.'));return;}for(const item of items){const [label,tone]=state(item),button=el('button',`hxWorkCard ${tone}${selected===item.id?' active':''}`);button.type='button';const top=el('div');top.append(el('strong',undefined,item.title),el('span',tone,label));const meta=el('small',undefined,`${item.attempt_count||0} ciclo${item.attempt_count===1?'':'s'} · ${date(item.updated_at)}`);const progress=document.createElement('progress');progress.max=100;progress.value=Math.max(0,Math.min(100,Number(item.progress)||0));button.append(top,meta,progress);button.onclick=()=>void loadDetail(item.id);list.append(button);}if(!selected&&items[0])void loadDetail(items[0].id);if(selected&&!items.some(x=>x.id===selected)){selected=undefined;detail?.replaceChildren(el('div','hxWorkEmpty','Selecciona un trabajo para ver su actividad.'));}}catch(error){list.replaceChildren(el('div','hxWorkError',error instanceof Error?error.message:'No se pudieron cargar los trabajos'));}};
 const moveLegacy=(page:HTMLElement,container:HTMLElement)=>{for(const selector of ['.cxWorkEmpty','.cxProjectGrid','.cxProjectWorkspace','.cxWorkRuns']){for(const node of page.querySelectorAll<HTMLElement>(`:scope > ${selector}`))container.append(node);}};
 const mount=async(page:HTMLElement)=>{if(page.dataset.workModeReady==='1')return;page.dataset.workModeReady='1';root=page;const section=el('section','hxWorkMode'),hero=el('div','hxWorkHero'),copy=el('div');copy.append(el('span',undefined,'Modo Trabajo'),el('h2',undefined,'Dile qué debe lograr'),el('p',undefined,'Se mantiene activo durante muchos ciclos. Ante errores busca otra solución; cuando necesita tiempo entra en espera y vuelve a intentarlo.'));hero.append(copy);const form=el('form','hxWorkForm'),goal=document.createElement('textarea');goal.required=true;goal.minLength=10;goal.maxLength=12000;goal.rows=4;goal.placeholder='Ej. Termina la aplicación, prueba cada cambio, corrige los errores y no te detengas hasta dejarla funcionando.';goal.setAttribute('aria-label','Objetivo del Modo Trabajo');const submit=el('button','hxWorkStart','Activar Modo Trabajo');submit.type='submit';notice=el('p','hxWorkNotice');notice.setAttribute('aria-live','polite');form.append(goal,submit,notice);section.append(hero,form);const layout=el('div','hxWorkLayout');list=el('div','hxWorkList');detail=el('section','hxWorkDetail');detail.append(el('div','hxWorkEmpty','Selecciona un trabajo para ver su actividad.'));layout.append(list,detail);section.append(layout);page.querySelector('.cxPageHead')?.insertAdjacentElement('afterend',section);const advanced=document.createElement('details');advanced.className='hxAdvancedProjects';const summary=document.createElement('summary');summary.textContent='Herramientas avanzadas';const legacy=el('div','hxAdvancedProjectsBody');advanced.append(summary,legacy);page.append(advanced);moveLegacy(page,legacy);form.onsubmit=async event=>{event.preventDefault();submit.disabled=true;notice!.className='hxWorkNotice';notice!.textContent='Activando…';try{const response=await request<{item:WorkItem}>('/api/work-mode',{method:'POST',body:JSON.stringify({goal:goal.value.trim()})});goal.value='';notice!.className='hxWorkNotice good';notice!.textContent='Modo Trabajo activo. Puedes cerrar la app; continuará desde el Worker.';await load();await loadDetail(response.item.id);}catch(error){notice!.className='hxWorkNotice bad';notice!.textContent=error instanceof Error?error.message:'No se pudo activar';}finally{submit.disabled=false;}};await load();timer=window.setInterval(()=>{if(root&&document.body.contains(root)){void load();if(selected)void loadDetail(selected);}},5000);};
 const scan=()=>{const page=workPage();if(page&&!page.dataset.workModeReady)void mount(page);if(page&&page.dataset.workModeReady){const legacy=page.querySelector<HTMLElement>('.hxAdvancedProjectsBody');if(legacy)moveLegacy(page,legacy);}if(root&&!document.body.contains(root)){root=undefined;list=undefined;detail=undefined;notice=undefined;selected=undefined;if(timer)window.clearInterval(timer);timer=undefined;}};
 const observer=new MutationObserver(scan);observer.observe(document.body,{childList:true,subtree:true});scan();return()=>{observer.disconnect();if(timer)window.clearInterval(timer);};
}