type WorkItem={id:string;title:string;objective:string;status:string;checkpoint:string;lastError:string|null;attemptCount:number;nextRunAt:string|null;heartbeatAt:string|null;createdAt:string;updatedAt:string};
type WorkDetail={item:WorkItem;events:Array<{message:string;created_at:string}>};

const request=async<T>(path:string,init?:RequestInit):Promise<T>=>{const headers=new Headers(init?.headers);headers.set('Accept','application/json');if(init?.body)headers.set('Content-Type','application/json');const response=await fetch(path,{credentials:'include',...init,headers});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'No disponible');return data as T;};
const el=<K extends keyof HTMLElementTagNameMap>(tag:K,className?:string,text?:string)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
function findWorkPage(){return[...document.querySelectorAll<HTMLElement>('.cxPage')].find(page=>page.querySelector('h1')?.textContent?.trim()==='Trabajo');}
function formatDate(value:string|null){if(!value)return'';const normalized=value.includes('T')?value:`${value.replace(' ','T')}Z`;const date=new Date(normalized);return Number.isNaN(date.getTime())?'':date.toLocaleString('es-MX',{dateStyle:'short',timeStyle:'short'});}
function state(item:WorkItem){if(item.status==='completed')return{label:'Completado',tone:'done'};if(item.status==='working'||item.status==='testing'||item.status==='repairing')return{label:'Trabajando',tone:'active'};if(item.status==='queued'&&item.nextRunAt&&Date.parse(item.nextRunAt)>Date.now()+10_000)return{label:'En espera',tone:'waiting'};if(item.status==='queued')return{label:'Continuando',tone:'active'};return{label:'Reanudable',tone:'waiting'};}
function short(value:string,limit=220){const clean=value.replace(/\s+/g,' ').trim();return clean.length>limit?`${clean.slice(0,limit).trim()}…`:clean;}

export function installWorkModeEnhancer(){
 let root:HTMLElement|undefined,list:HTMLElement|undefined,detail:HTMLElement|undefined,notice:HTMLElement|undefined,timer:number|undefined;
 const setNotice=(message:string,tone:''|'good'|'bad'='')=>{if(!notice)return;notice.className=`hxWorkNotice ${tone}`;notice.textContent=message;};
 const open=async(id:string)=>{if(!detail)return;detail.replaceChildren(el('div','hxWorkLoading','Abriendo trabajo…'));try{const data=await request<WorkDetail>(`/api/work-mode/${id}`),item=data.item,meta=state(item),panel=el('article','hxWorkDetail');const head=el('header'),copy=el('div');copy.append(el('span',`hxWorkState ${meta.tone}`,meta.label),el('h3',undefined,item.title),el('p',undefined,item.objective));head.append(copy);panel.append(head);if(item.checkpoint){const checkpoint=el('section');checkpoint.append(el('h4',undefined,item.status==='completed'?'Resultado':'Último avance'),el('p','hxWorkCheckpoint',item.checkpoint));panel.append(checkpoint);}if(item.lastError){const error=el('section','hxWorkError');error.append(el('h4',undefined,'Último error resuelto o en revisión'),el('p',undefined,item.lastError));panel.append(error);}const facts=el('div','hxWorkFacts');facts.append(el('span',undefined,`Ciclos: ${item.attemptCount}`),el('span',undefined,`Actualizado: ${formatDate(item.updatedAt)}`));if(item.nextRunAt&&item.status!=='completed')facts.append(el('span',undefined,`Reanuda: ${formatDate(item.nextRunAt)}`));panel.append(facts);if(data.events?.length){const events=el('details','hxWorkEvents'),summary=el('summary',undefined,'Ver actividad');events.append(summary);for(const event of data.events){const row=el('div');row.append(el('time',undefined,formatDate(event.created_at)),el('p',undefined,event.message));events.append(row);}panel.append(events);}if(!['queued','working','testing','repairing'].includes(item.status)){const run=el('button','hxWorkRun','Continuar trabajo');run.type='button';run.onclick=async()=>{run.disabled=true;try{await request(`/api/work-mode/${item.id}/run`,{method:'POST'});setNotice('Trabajo reanudado.','good');await load();await open(item.id);}catch(error){setNotice(error instanceof Error?error.message:'No se pudo reanudar','bad');}finally{run.disabled=false;}};panel.append(run);}detail.replaceChildren(panel);}catch(error){detail.replaceChildren(el('div','hxWorkError',error instanceof Error?error.message:'No se pudo abrir el trabajo'));}};
 const load=async()=>{if(!list)return;try{const response=await request<{items:WorkItem[]}>('/api/work-mode'),items=response.items||[];list.replaceChildren();if(!items.length){const empty=el('div','hxWorkEmpty');empty.append(el('strong',undefined,'Todavía no hay trabajos'),el('p',undefined,'Escribe el objetivo arriba. Héctor decidirá los pasos, corregirá errores y seguirá hasta terminar.'));list.append(empty);return;}for(const item of items){const meta=state(item),button=el('button','hxWorkCard');button.type='button';button.onclick=()=>void open(item.id);const head=el('div','hxWorkCardHead'),copy=el('div');copy.append(el('strong',undefined,item.title),el('span',undefined,short(item.objective,110)));head.append(copy,el('span',`hxWorkState ${meta.tone}`,meta.label));button.append(head);if(item.checkpoint)button.append(el('p',undefined,short(item.checkpoint)));const footer=el('footer');footer.append(el('span',undefined,`Ciclo ${item.attemptCount||0}`),el('span',undefined,item.nextRunAt&&item.status!=='completed'?`Reanuda ${formatDate(item.nextRunAt)}`:`Actualizado ${formatDate(item.updatedAt)}`));button.append(footer);list.append(button);}}catch(error){list.replaceChildren(el('div','hxWorkError',error instanceof Error?error.message:'No se pudieron cargar los trabajos'));}};
 const render=async(page:HTMLElement)=>{if(page.dataset.workModeReady==='1')return;page.dataset.workModeReady='1';root=page;const pageHead=page.querySelector<HTMLElement>('.cxPageHead');const eyebrow=pageHead?.querySelector('span'),title=pageHead?.querySelector('h1'),description=pageHead?.querySelector('p');if(eyebrow)eyebrow.textContent='Modo persistente';if(title)title.textContent='Trabajo';if(description)description.textContent='Describe el resultado. Héctor continuará, resolverá errores y esperará solo cuando sea necesario.';
  const section=el('section','hxWorkMode'),intro=el('div','hxWorkIntro');intro.append(el('div','hxWorkOrb','H'),el('div','hxWorkCopy'));const introCopy=intro.querySelector<HTMLElement>('.hxWorkCopy')!;introCopy.append(el('h2',undefined,'¿Qué debe lograr Héctor?'),el('p',undefined,'No necesitas dividir pasos, elegir agentes ni configurar rondas.'));const form=el('form','hxWorkForm'),objective=document.createElement('textarea');objective.required=true;objective.minLength=10;objective.maxLength=12000;objective.rows=5;objective.placeholder='Ejemplo: termina Héctor OS, prueba cada cambio, corrige errores y no te detengas hasta que quede validado.';objective.setAttribute('aria-label','Objetivo del Modo Trabajo');const submit=el('button','hxWorkStart','Iniciar trabajo');submit.type='submit';notice=el('p','hxWorkNotice');form.append(objective,submit,notice);section.append(intro,form);const body=el('div','hxWorkBody');list=el('div','hxWorkList');detail=el('div','hxWorkDetailHost');body.append(list,detail);section.append(body);pageHead?.insertAdjacentElement('afterend',section);
  const programmed=el('section','hxProgrammedMount');section.insertAdjacentElement('afterend',programmed);const legacy=el('button','hxLegacyToggle','Mostrar proyectos y agentes anteriores');legacy.type='button';legacy.onclick=()=>{const visible=page.classList.toggle('hxShowLegacy');legacy.textContent=visible?'Ocultar proyectos y agentes anteriores':'Mostrar proyectos y agentes anteriores';};programmed.insertAdjacentElement('afterend',legacy);
  form.onsubmit=async event=>{event.preventDefault();if(!objective.value.trim())return;submit.disabled=true;setNotice('Iniciando Modo Trabajo…');try{const response=await request<{item:WorkItem}>('/api/work-mode',{method:'POST',body:JSON.stringify({objective:objective.value.trim()})});objective.value='';setNotice('Trabajo iniciado. Puedes cerrar la app; continuará desde el Worker.','good');await load();await open(response.item.id);}catch(error){setNotice(error instanceof Error?error.message:'No se pudo iniciar','bad');}finally{submit.disabled=false;}};
  await load();timer=window.setInterval(()=>{if(document.body.contains(page))void load();},5000);
 };
 const scan=()=>{const page=findWorkPage();if(page&&!page.dataset.workModeReady)void render(page);if(root&&!document.body.contains(root)){root=undefined;list=undefined;detail=undefined;notice=undefined;if(timer)window.clearInterval(timer);timer=undefined;}};const observer=new MutationObserver(scan);observer.observe(document.body,{childList:true,subtree:true});scan();return()=>{observer.disconnect();if(timer)window.clearInterval(timer);};
}
